// Generated by question-bank/u2.py (verified). Do not edit by hand.
import type { Unit } from '../types';

const unit: Unit = {
  "id": "u2",
  "number": 2,
  "semester": 1,
  "title": "المتطابقات والمعادلات المثلثية",
  "description": "المتطابقات الأساسية ومتطابقات المجموع والفرق، متطابقات ضعف الزاوية ونصفها وتقليص القوة وتحويل الضرب إلى مجموع والمجموع إلى ضرب، وحل المعادلات المثلثية.",
  "lessons": [
    {
      "id": "u2-l1",
      "title": "المتطابقات المثلثية 1"
    },
    {
      "id": "u2-l2",
      "title": "المتطابقات المثلثية 2"
    },
    {
      "id": "u2-l3",
      "title": "حلُّ المعادلات المثلثية"
    }
  ],
  "exams": [
    {
      "id": "u2-e1",
      "title": "الاختبار الأول",
      "questions": [
        {
          "id": "u2e1q1",
          "lesson": "u2-l1",
          "difficulty": "easy",
          "text": "أيّ الآتية مكافئ للمقدار: $\\frac{\\sec x-\\cos x}{\\tan x}$ ؟",
          "options": [
            "$\\sin x$",
            "$\\cos x$",
            "$\\tan x$",
            "$\\sec x$"
          ],
          "answer": 0,
          "solution": "$\\sec x-\\cos x=\\dfrac{1-\\cos^2x}{\\cos x}=\\dfrac{\\sin^2x}{\\cos x}$\nبالقسمة على $\\tan x=\\dfrac{\\sin x}{\\cos x}$: $\\dfrac{\\sin^2x}{\\cos x}\\cdot\\dfrac{\\cos x}{\\sin x}=\\sin x$"
        },
        {
          "id": "u2e1q2",
          "lesson": "u2-l1",
          "difficulty": "medium",
          "text": "أبسط صورة للمقدار: $\\cos(x-\\frac{\\pi}{3})-\\frac{1}{2}\\cos x$ هي:",
          "options": [
            "$\\frac{\\sqrt{3}}{2}\\sin x$",
            "$\\frac{1}{2}\\sin x$",
            "$\\frac{\\sqrt{3}}{2}\\cos x$",
            "$\\cos x$"
          ],
          "answer": 0,
          "solution": "$\\cos\\left(x-\\frac{\\pi}{3}\\right)=\\cos x\\cos\\frac{\\pi}{3}+\\sin x\\sin\\frac{\\pi}{3}=\\frac12\\cos x+\\frac{\\sqrt3}{2}\\sin x$\nبطرح $\\frac12\\cos x$ يبقى $\\frac{\\sqrt3}{2}\\sin x$"
        },
        {
          "id": "u2e1q3",
          "lesson": "u2-l1",
          "difficulty": "medium",
          "text": "إذا كان $\\sin A=\\frac{5}{13}$ حيث $\\frac{\\pi}{2}<A<\\pi$ ، و $\\cos B=-\\frac{3}{5}$ حيث $\\pi<B<\\frac{3\\pi}{2}$ ، فإنّ قيمة $\\cos(A-B)$ هي:",
          "options": [
            "$\\frac{16}{65}$",
            "$\\frac{56}{65}$",
            "$-\\frac{16}{65}$",
            "$-\\frac{56}{65}$"
          ],
          "answer": 0,
          "solution": "$A$ في الربع الثاني: $\\cos A=-\\frac{12}{13}$ ، و $B$ في الربع الثالث: $\\sin B=-\\frac45$\n$\\cos(A-B)=\\cos A\\cos B+\\sin A\\sin B=\\left(-\\frac{12}{13}\\right)\\left(-\\frac35\\right)+\\frac{5}{13}\\left(-\\frac45\\right)=\\frac{36}{65}-\\frac{20}{65}=\\frac{16}{65}$"
        },
        {
          "id": "u2e1q4",
          "lesson": "u2-l1",
          "difficulty": "easy",
          "text": "إحدى المعادلات الآتية **ليست** متطابقة:",
          "options": [
            "$\\sec(-x)=-\\sec x$",
            "$\\sin(-x)=-\\sin x$",
            "$\\tan(\\frac{\\pi}{2}-x)=\\cot x$",
            "$\\cos(-x)=\\cos x$"
          ],
          "answer": 0,
          "solution": "الاقتران $\\sec x$ زوجي مثل $\\cos x$ ، أي $\\sec(-x)=\\dfrac{1}{\\cos(-x)}=\\dfrac{1}{\\cos x}=\\sec x$ ، فالمعادلة $\\sec(-x)=-\\sec x$ ليست متطابقة.\nأما البقية فمتطابقات: $\\sin$ فردي، $\\cos$ زوجي، و $\\tan\\left(\\frac{\\pi}{2}-x\\right)=\\cot x$"
        },
        {
          "id": "u2e1q5",
          "lesson": "u2-l2",
          "difficulty": "easy",
          "text": "إذا كان $\\tan\\theta=2$ ، حيث $\\theta$ زاوية حادّة، فإنّ قيمة $\\sin2\\theta$ هي:",
          "options": [
            "$\\frac{4}{5}$",
            "$\\frac{3}{5}$",
            "$-\\frac{3}{5}$",
            "$\\frac{2}{5}$"
          ],
          "answer": 0,
          "solution": "من مثلث قائم: المقابل $2$ والمجاور $1$ والوتر $\\sqrt5$ ، فيكون $\\sin\\theta=\\frac{2}{\\sqrt5}$ و $\\cos\\theta=\\frac{1}{\\sqrt5}$\n$\\sin2\\theta=2\\sin\\theta\\cos\\theta=2\\cdot\\frac{2}{\\sqrt5}\\cdot\\frac{1}{\\sqrt5}=\\frac45$"
        },
        {
          "id": "u2e1q6",
          "lesson": "u2-l2",
          "difficulty": "medium",
          "text": "قيمة المقدار: $8\\sin\\frac{\\pi}{8}\\cos\\frac{\\pi}{8}\\cos\\frac{\\pi}{4}$ هي:",
          "options": [
            "$2$",
            "$4$",
            "$1$",
            "$\\sqrt{2}$"
          ],
          "answer": 0,
          "solution": "$8\\sin\\frac{\\pi}{8}\\cos\\frac{\\pi}{8}=4\\sin\\frac{\\pi}{4}$ ، فيصبح المقدار $4\\sin\\frac{\\pi}{4}\\cos\\frac{\\pi}{4}=2\\sin\\frac{\\pi}{2}=2$"
        },
        {
          "id": "u2e1q7",
          "lesson": "u2-l2",
          "difficulty": "medium",
          "text": "إذا كان $\\cos\\theta=\\frac{1}{4}$ ، حيث $\\frac{3\\pi}{2}<\\theta<2\\pi$ ، فإنّ قيمة $\\sin\\frac{\\theta}{2}$ هي:",
          "options": [
            "$\\frac{\\sqrt{6}}{4}$",
            "$-\\frac{\\sqrt{6}}{4}$",
            "$\\frac{\\sqrt{10}}{4}$",
            "$-\\frac{\\sqrt{10}}{4}$"
          ],
          "answer": 0,
          "solution": "$\\frac{3\\pi}{4}<\\frac{\\theta}{2}<\\pi$ ، أي $\\frac{\\theta}{2}$ في الربع الثاني فالجيب موجب\n$\\sin\\frac{\\theta}{2}=\\sqrt{\\dfrac{1-\\cos\\theta}{2}}=\\sqrt{\\dfrac{1-\\frac14}{2}}=\\sqrt{\\dfrac38}=\\dfrac{\\sqrt6}{4}$"
        },
        {
          "id": "u2e1q8",
          "lesson": "u2-l2",
          "difficulty": "hard",
          "text": "قيمة المقدار: $\\sin75^\\circ-\\sin15^\\circ$ هي:",
          "options": [
            "$\\frac{\\sqrt{2}}{2}$",
            "$\\frac{\\sqrt{6}}{2}$",
            "$\\frac{1}{2}$",
            "$\\frac{\\sqrt{3}}{2}$"
          ],
          "answer": 0,
          "solution": "$\\sin A-\\sin B=2\\cos\\dfrac{A+B}{2}\\sin\\dfrac{A-B}{2}$\n$\\sin75^\\circ-\\sin15^\\circ=2\\cos45^\\circ\\sin30^\\circ=2\\cdot\\frac{\\sqrt2}{2}\\cdot\\frac12=\\frac{\\sqrt2}{2}$"
        },
        {
          "id": "u2e1q9",
          "lesson": "u2-l3",
          "difficulty": "easy",
          "text": "مجموعة حلّ المعادلة: $2\\sin^{2}x+\\sin x-1=0$ في الفترة $[0,\\,2\\pi)$ هي:",
          "options": [
            "$x=\\frac{\\pi}{6},\\ x=\\frac{5\\pi}{6},\\ x=\\frac{3\\pi}{2}$",
            "$x=\\frac{\\pi}{2},\\ x=\\frac{7\\pi}{6},\\ x=\\frac{11\\pi}{6}$",
            "$x=\\frac{\\pi}{6},\\ x=\\frac{5\\pi}{6},\\ x=\\frac{\\pi}{2}$",
            "$x=\\frac{\\pi}{6},\\ x=\\frac{5\\pi}{6}$"
          ],
          "answer": 0,
          "solution": "بالتحليل: $(2\\sin x-1)(\\sin x+1)=0$\n$\\sin x=\\frac12 \\Rightarrow x=\\frac{\\pi}{6},\\ \\frac{5\\pi}{6}$ ، أو $\\sin x=-1 \\Rightarrow x=\\frac{3\\pi}{2}$"
        },
        {
          "id": "u2e1q10",
          "lesson": "u2-l3",
          "difficulty": "medium",
          "text": "مجموعة حلّ المعادلة: $\\tan 2x=\\sqrt{3}$ في الفترة $[0,\\,\\pi)$ هي:",
          "options": [
            "$x=\\frac{\\pi}{6},\\ x=\\frac{2\\pi}{3}$",
            "$x=\\frac{\\pi}{6},\\ x=\\frac{7\\pi}{6}$",
            "$x=\\frac{\\pi}{3},\\ x=\\frac{4\\pi}{3}$",
            "$x=\\frac{\\pi}{6}$"
          ],
          "answer": 0,
          "solution": "بما أن $0\\le x<\\pi$ فإن $0\\le 2x<2\\pi$\n$\\tan2x=\\sqrt3 \\Rightarrow 2x=\\frac{\\pi}{3}$ أو $2x=\\frac{\\pi}{3}+\\pi=\\frac{4\\pi}{3}$\nإذن $x=\\frac{\\pi}{6}$ أو $x=\\frac{2\\pi}{3}$"
        },
        {
          "id": "u2e1q11",
          "lesson": "u2-l3",
          "difficulty": "hard",
          "text": "حلول المعادلة: $\\cos 2x=-\\cos x$ في الفترة $(0,\\,2\\pi)$ هي:",
          "options": [
            "$x=\\frac{\\pi}{3},\\ x=\\pi,\\ x=\\frac{5\\pi}{3}$",
            "$x=\\frac{\\pi}{3},\\ x=\\frac{5\\pi}{3}$",
            "$x=\\frac{2\\pi}{3},\\ x=\\pi,\\ x=\\frac{4\\pi}{3}$",
            "$x=0,\\ x=\\frac{\\pi}{3},\\ x=\\frac{5\\pi}{3}$"
          ],
          "answer": 0,
          "solution": "نعوّض $\\cos2x=2\\cos^2x-1$: $2\\cos^2x-1=-\\cos x \\Rightarrow 2\\cos^2x+\\cos x-1=0$\nبالتحليل: $(2\\cos x-1)(\\cos x+1)=0$\n$\\cos x=\\frac12 \\Rightarrow x=\\frac{\\pi}{3},\\ \\frac{5\\pi}{3}$ ، أو $\\cos x=-1 \\Rightarrow x=\\pi$"
        },
        {
          "id": "u2e1q12",
          "lesson": "u2-l3",
          "difficulty": "medium",
          "text": "أحد الآتية **لا** يُعَدّ حلًّا للمعادلة: $2\\cos x+\\sqrt{3}=0$",
          "options": [
            "$\\frac{13\\pi}{6}$",
            "$\\frac{17\\pi}{6}$",
            "$\\frac{19\\pi}{6}$",
            "$-\\frac{5\\pi}{6}$"
          ],
          "answer": 0,
          "solution": "$\\cos x=-\\frac{\\sqrt3}{2}$ ، فالحل العام: $x=\\frac{5\\pi}{6}+2n\\pi$ أو $x=\\frac{7\\pi}{6}+2n\\pi$\n$\\frac{17\\pi}{6}=\\frac{5\\pi}{6}+2\\pi$ ✔ ، $\\frac{19\\pi}{6}=\\frac{7\\pi}{6}+2\\pi$ ✔ ، $-\\frac{5\\pi}{6}=\\frac{7\\pi}{6}-2\\pi$ ✔\nأما $\\frac{13\\pi}{6}=\\frac{\\pi}{6}+2\\pi$ فجيب تمامها $\\frac{\\sqrt3}{2}$ ، إذن ليست حلًّا."
        }
      ]
    },
    {
      "id": "u2-e2",
      "title": "الاختبار الثاني",
      "questions": [
        {
          "id": "u2e2q1",
          "lesson": "u2-l1",
          "difficulty": "easy",
          "text": "أبسط صورة للمقدار: $(1-\\sin^{2}x)(1+\\tan^{2}x)$ هي:",
          "options": [
            "$1$",
            "$\\cos^{2}x$",
            "$\\sin^{2}x$",
            "$\\sec^{2}x$"
          ],
          "answer": 0,
          "solution": "$1-\\sin^2x=\\cos^2x$ ، و $1+\\tan^2x=\\sec^2x$ ، إذن المقدار $=\\cos^2x\\cdot\\dfrac{1}{\\cos^2x}=1$"
        },
        {
          "id": "u2e2q2",
          "lesson": "u2-l1",
          "difficulty": "easy",
          "text": "قيمة المقدار: $\\cos80^\\circ\\cos20^\\circ+\\sin80^\\circ\\sin20^\\circ$ هي:",
          "options": [
            "$\\frac{1}{2}$",
            "$\\frac{\\sqrt{3}}{2}$",
            "$-\\frac{1}{2}$",
            "$1$"
          ],
          "answer": 0,
          "solution": "المقدار على صورة $\\cos(A-B)$: $\\cos(80^\\circ-20^\\circ)=\\cos60^\\circ=\\frac12$"
        },
        {
          "id": "u2e2q3",
          "lesson": "u2-l1",
          "difficulty": "medium",
          "text": "إذا كان $\\tan x=3$ ، فإنّ قيمة $\\tan\\left(\\frac{\\pi}{4}-x\\right)$ هي:",
          "options": [
            "$-\\frac{1}{2}$",
            "$\\frac{1}{2}$",
            "$-2$",
            "$2$"
          ],
          "answer": 0,
          "solution": "$\\tan\\left(\\frac{\\pi}{4}-x\\right)=\\dfrac{\\tan\\frac{\\pi}{4}-\\tan x}{1+\\tan\\frac{\\pi}{4}\\tan x}=\\dfrac{1-3}{1+3}=-\\dfrac12$"
        },
        {
          "id": "u2e2q4",
          "lesson": "u2-l1",
          "difficulty": "hard",
          "text": "إذا كان $\\tan A=\\frac{1}{2}$ و $\\tan B=\\frac{1}{3}$ ، حيث $A,\\ B$ زاويتان حادّتان، فإنّ $A+B$ تساوي:",
          "options": [
            "$\\frac{\\pi}{4}$",
            "$\\frac{\\pi}{3}$",
            "$\\frac{\\pi}{6}$",
            "$\\frac{\\pi}{2}$"
          ],
          "answer": 0,
          "solution": "$\\tan(A+B)=\\dfrac{\\frac12+\\frac13}{1-\\frac12\\cdot\\frac13}=\\dfrac{\\frac56}{\\frac56}=1$\nوبما أن $0<A+B<\\pi$ و $\\tan(A+B)>0$ فإن $A+B=\\frac{\\pi}{4}$"
        },
        {
          "id": "u2e2q5",
          "lesson": "u2-l2",
          "difficulty": "easy",
          "text": "أيّ الآتية مكافئ للمقدار: $\\frac{\\sin 2x}{1+\\cos 2x}$ ؟",
          "options": [
            "$\\tan x$",
            "$\\cot x$",
            "$\\sin x$",
            "$2\\tan x$"
          ],
          "answer": 0,
          "solution": "$\\dfrac{2\\sin x\\cos x}{1+(2\\cos^2x-1)}=\\dfrac{2\\sin x\\cos x}{2\\cos^2x}=\\dfrac{\\sin x}{\\cos x}=\\tan x$"
        },
        {
          "id": "u2e2q6",
          "lesson": "u2-l2",
          "difficulty": "easy",
          "text": "إذا كان $\\sin\\theta=-\\frac{2}{3}$ ، فإنّ قيمة $\\cos2\\theta$ هي:",
          "options": [
            "$\\frac{1}{9}$",
            "$-\\frac{1}{9}$",
            "$\\frac{5}{9}$",
            "$\\frac{7}{9}$"
          ],
          "answer": 0,
          "solution": "$\\cos2\\theta=1-2\\sin^2\\theta=1-2\\cdot\\frac49=\\frac19$ (لا نحتاج إلى معرفة الربع)"
        },
        {
          "id": "u2e2q7",
          "lesson": "u2-l2",
          "difficulty": "medium",
          "text": "باستعمال متطابقات تقليص القوة، المقدار $\\cos^{4}x$ يساوي:",
          "options": [
            "$\\frac{3+4\\cos 2x+\\cos 4x}{8}$",
            "$\\frac{3+4\\cos 2x+\\cos 4x}{4}$",
            "$\\frac{3-4\\cos 2x+\\cos 4x}{8}$",
            "$\\frac{1+2\\cos 2x+\\cos 4x}{8}$"
          ],
          "answer": 0,
          "solution": "$\\cos^4x=\\left(\\dfrac{1+\\cos2x}{2}\\right)^2=\\dfrac{1+2\\cos2x+\\cos^22x}{4}$\nو $\\cos^22x=\\dfrac{1+\\cos4x}{2}$ ، إذن $\\cos^4x=\\dfrac{2+4\\cos2x+1+\\cos4x}{8}=\\dfrac{3+4\\cos2x+\\cos4x}{8}$"
        },
        {
          "id": "u2e2q8",
          "lesson": "u2-l2",
          "difficulty": "hard",
          "text": "قيمة المقدار: $2\\sin\\frac{5\\pi}{12}\\cos\\frac{\\pi}{12}$ هي:",
          "options": [
            "$1+\\frac{\\sqrt{3}}{2}$",
            "$1-\\frac{\\sqrt{3}}{2}$",
            "$\\frac{\\sqrt{3}}{2}$",
            "$1+\\sqrt{3}$"
          ],
          "answer": 0,
          "solution": "$2\\sin A\\cos B=\\sin(A+B)+\\sin(A-B)$\n$=\\sin\\frac{6\\pi}{12}+\\sin\\frac{4\\pi}{12}=\\sin\\frac{\\pi}{2}+\\sin\\frac{\\pi}{3}=1+\\frac{\\sqrt3}{2}$"
        },
        {
          "id": "u2e2q9",
          "lesson": "u2-l3",
          "difficulty": "easy",
          "text": "حلّ المعادلة: $\\cos^{2}x+2\\cos x-3=0$ في الفترة $[0,\\,2\\pi)$ هو:",
          "options": [
            "$x=0$",
            "$x=\\pi$",
            "$x=\\frac{\\pi}{2}$",
            "$x=\\frac{3\\pi}{2}$"
          ],
          "answer": 0,
          "solution": "بالتحليل: $(\\cos x+3)(\\cos x-1)=0$\n$\\cos x=-3$ مرفوض (لأن $-1\\le\\cos x\\le1$) ، و $\\cos x=1 \\Rightarrow x=0$"
        },
        {
          "id": "u2e2q10",
          "lesson": "u2-l3",
          "difficulty": "medium",
          "text": "حلول المعادلة: $3\\tan^{2}x-1=0$ في الفترة $\\left(\\frac{\\pi}{2},\\,\\frac{3\\pi}{2}\\right)$ هي:",
          "options": [
            "$x=\\frac{5\\pi}{6},\\ x=\\frac{7\\pi}{6}$",
            "$x=\\frac{\\pi}{6},\\ x=\\frac{7\\pi}{6}$",
            "$x=\\frac{5\\pi}{6},\\ x=\\frac{11\\pi}{6}$",
            "$x=\\frac{\\pi}{6},\\ x=\\frac{5\\pi}{6}$"
          ],
          "answer": 0,
          "solution": "$\\tan^2x=\\frac13 \\Rightarrow \\tan x=\\pm\\frac{1}{\\sqrt3}$\nفي الفترة $\\left(\\frac{\\pi}{2},\\frac{3\\pi}{2}\\right)$: $\\tan x=-\\frac{1}{\\sqrt3} \\Rightarrow x=\\frac{5\\pi}{6}$ ، و $\\tan x=\\frac{1}{\\sqrt3} \\Rightarrow x=\\frac{7\\pi}{6}$"
        },
        {
          "id": "u2e2q11",
          "lesson": "u2-l3",
          "difficulty": "hard",
          "text": "حلول المعادلة: $2\\sin x\\cos x+\\sqrt{2}\\cos x=0$ في الفترة $(\\pi,\\,2\\pi)$ هي:",
          "options": [
            "$x=\\frac{5\\pi}{4},\\ x=\\frac{3\\pi}{2},\\ x=\\frac{7\\pi}{4}$",
            "$x=\\frac{5\\pi}{4},\\ x=\\frac{7\\pi}{4}$",
            "$x=\\frac{\\pi}{2},\\ x=\\frac{5\\pi}{4},\\ x=\\frac{7\\pi}{4}$",
            "$x=\\frac{3\\pi}{4},\\ x=\\frac{3\\pi}{2},\\ x=\\frac{7\\pi}{4}$"
          ],
          "answer": 0,
          "solution": "بإخراج العامل المشترك: $\\cos x(2\\sin x+\\sqrt2)=0$\n$\\cos x=0 \\Rightarrow x=\\frac{3\\pi}{2}$ (في الفترة) ، أو $\\sin x=-\\frac{\\sqrt2}{2} \\Rightarrow x=\\frac{5\\pi}{4},\\ \\frac{7\\pi}{4}$\nتنبيه: لا نقسم على $\\cos x$ حتى لا نفقد الحل $\\frac{3\\pi}{2}$"
        },
        {
          "id": "u2e2q12",
          "lesson": "u2-l3",
          "difficulty": "medium",
          "text": "مجموعة حلّ المعادلة: $\\sin\\frac{x}{2}=\\cos\\frac{x}{2}$ في الفترة $[0,\\,2\\pi)$ هي:",
          "options": [
            "$x=\\frac{\\pi}{2}$",
            "$x=\\frac{\\pi}{2},\\ x=\\frac{5\\pi}{2}$",
            "$x=\\frac{\\pi}{4}$",
            "$x=\\frac{\\pi}{4},\\ x=\\frac{5\\pi}{4}$"
          ],
          "answer": 0,
          "solution": "بالقسمة على $\\cos\\frac{x}{2}$: $\\tan\\frac{x}{2}=1$ ، وبما أن $0\\le\\frac{x}{2}<\\pi$ فإن $\\frac{x}{2}=\\frac{\\pi}{4}$ فقط\nإذن $x=\\frac{\\pi}{2}$ ($\\frac{5\\pi}{2}$ خارج الفترة)"
        }
      ]
    },
    {
      "id": "u2-e3",
      "title": "الاختبار الثالث",
      "questions": [
        {
          "id": "u2e3q1",
          "lesson": "u2-l1",
          "difficulty": "easy",
          "text": "إذا كان $\\cot\\theta=\\frac{3}{4}$ ، حيث $\\pi<\\theta<\\frac{3\\pi}{2}$ ، فإنّ قيمة $\\sin\\theta$ هي:",
          "options": [
            "$-\\frac{4}{5}$",
            "$\\frac{4}{5}$",
            "$-\\frac{3}{5}$",
            "$\\frac{3}{5}$"
          ],
          "answer": 0,
          "solution": "$\\cot\\theta=\\frac34 \\Rightarrow \\tan\\theta=\\frac43$ ، ومن مثلث قائم أضلاعه $3,\\ 4,\\ 5$: $|\\sin\\theta|=\\frac45$\n$\\theta$ في الربع الثالث فالجيب سالب: $\\sin\\theta=-\\frac45$"
        },
        {
          "id": "u2e3q2",
          "lesson": "u2-l1",
          "difficulty": "medium",
          "text": "أبسط صورة للمقدار: $\\cos(x+\\frac{\\pi}{6})-\\cos(x-\\frac{\\pi}{6})$ هي:",
          "options": [
            "$-\\sin x$",
            "$\\sin x$",
            "$-\\sqrt{3}\\sin x$",
            "$\\sqrt{3}\\cos x$"
          ],
          "answer": 0,
          "solution": "بفك المقدارين: $\\left(\\cos x\\cos\\frac{\\pi}{6}-\\sin x\\sin\\frac{\\pi}{6}\\right)-\\left(\\cos x\\cos\\frac{\\pi}{6}+\\sin x\\sin\\frac{\\pi}{6}\\right)$\n$=-2\\sin x\\sin\\frac{\\pi}{6}=-2\\cdot\\frac12\\sin x=-\\sin x$"
        },
        {
          "id": "u2e3q3",
          "lesson": "u2-l1",
          "difficulty": "medium",
          "text": "أيّ الآتية مكافئ للمقدار: $\\frac{1+\\tan^{2}x}{1+\\cot^{2}x}$ ؟",
          "options": [
            "$\\tan^{2}x$",
            "$\\cot^{2}x$",
            "$1$",
            "$\\sec^{2}x$"
          ],
          "answer": 0,
          "solution": "$\\dfrac{\\sec^2x}{\\csc^2x}=\\dfrac{1/\\cos^2x}{1/\\sin^2x}=\\dfrac{\\sin^2x}{\\cos^2x}=\\tan^2x$"
        },
        {
          "id": "u2e3q4",
          "lesson": "u2-l1",
          "difficulty": "hard",
          "text": "المقدار: $\\sin(\\alpha+\\beta)\\sin(\\alpha-\\beta)$ يساوي:",
          "options": [
            "$\\sin^{2}\\alpha-\\sin^{2}\\beta$",
            "$\\sin^{2}\\alpha+\\sin^{2}\\beta$",
            "$\\cos^{2}\\alpha-\\cos^{2}\\beta$",
            "$\\sin^{2}\\alpha-\\cos^{2}\\beta$"
          ],
          "answer": 0,
          "solution": "$(\\sin\\alpha\\cos\\beta+\\cos\\alpha\\sin\\beta)(\\sin\\alpha\\cos\\beta-\\cos\\alpha\\sin\\beta)=\\sin^2\\alpha\\cos^2\\beta-\\cos^2\\alpha\\sin^2\\beta$\n$=\\sin^2\\alpha(1-\\sin^2\\beta)-(1-\\sin^2\\alpha)\\sin^2\\beta=\\sin^2\\alpha-\\sin^2\\beta$\n(لاحظ أن الخيار $\\cos^2\\alpha-\\cos^2\\beta$ يساوي $\\sin^2\\beta-\\sin^2\\alpha$ أي سالب الإجابة)"
        },
        {
          "id": "u2e3q5",
          "lesson": "u2-l2",
          "difficulty": "easy",
          "text": "إذا كانت $0<x<\\frac{\\pi}{6}$ ، فإنّ أبسط صورة للمقدار $\\sqrt{\\frac{1+\\cos 6x}{2}}$ هي:",
          "options": [
            "$\\cos 3x$",
            "$\\cos 6x$",
            "$\\sin 3x$",
            "$\\cos 12x$"
          ],
          "answer": 0,
          "solution": "من متطابقة نصف الزاوية: $\\dfrac{1+\\cos6x}{2}=\\cos^23x$ ، فالمقدار $=|\\cos3x|$\nوبما أن $0<3x<\\frac{\\pi}{2}$ فإن $\\cos3x>0$ ، إذن المقدار $=\\cos3x$"
        },
        {
          "id": "u2e3q6",
          "lesson": "u2-l2",
          "difficulty": "medium",
          "text": "إذا كان $\\cos\\theta=\\frac{3}{5}$ ، حيث $\\frac{3\\pi}{2}<\\theta<2\\pi$ ، فإنّ قيمة $\\tan2\\theta$ هي:",
          "options": [
            "$\\frac{24}{7}$",
            "$-\\frac{24}{7}$",
            "$\\frac{7}{24}$",
            "$-\\frac{7}{24}$"
          ],
          "answer": 0,
          "solution": "$\\theta$ في الربع الرابع: $\\sin\\theta=-\\frac45$ ، $\\tan\\theta=-\\frac43$\n$\\tan2\\theta=\\dfrac{2\\tan\\theta}{1-\\tan^2\\theta}=\\dfrac{-\\frac83}{1-\\frac{16}{9}}=\\dfrac{-\\frac83}{-\\frac79}=\\dfrac{24}{7}$"
        },
        {
          "id": "u2e3q7",
          "lesson": "u2-l2",
          "difficulty": "medium",
          "text": "المقدار $\\cos 3x$ يساوي:",
          "options": [
            "$4\\cos^{3}x-3\\cos x$",
            "$3\\cos x-4\\cos^{3}x$",
            "$4\\cos^{3}x+3\\cos x$",
            "$\\cos^{3}x-3\\cos x$"
          ],
          "answer": 0,
          "solution": "$\\cos3x=\\cos(2x+x)=\\cos2x\\cos x-\\sin2x\\sin x$\n$=(2\\cos^2x-1)\\cos x-2\\sin^2x\\cos x=(2\\cos^2x-1)\\cos x-2(1-\\cos^2x)\\cos x=4\\cos^3x-3\\cos x$"
        },
        {
          "id": "u2e3q8",
          "lesson": "u2-l2",
          "difficulty": "hard",
          "text": "قيمة المقدار: $\\cos105^\\circ+\\cos15^\\circ$ هي:",
          "options": [
            "$\\frac{\\sqrt{2}}{2}$",
            "$\\frac{\\sqrt{6}}{2}$",
            "$-\\frac{\\sqrt{2}}{2}$",
            "$\\frac{\\sqrt{3}}{2}$"
          ],
          "answer": 0,
          "solution": "$\\cos A+\\cos B=2\\cos\\dfrac{A+B}{2}\\cos\\dfrac{A-B}{2}$\n$=2\\cos60^\\circ\\cos45^\\circ=2\\cdot\\frac12\\cdot\\frac{\\sqrt2}{2}=\\frac{\\sqrt2}{2}$"
        },
        {
          "id": "u2e3q9",
          "lesson": "u2-l3",
          "difficulty": "easy",
          "text": "مجموعة حلّ المعادلة: $4\\cos^{2}x-3=0$ في الفترة $[0,\\,\\pi]$ هي:",
          "options": [
            "$x=\\frac{\\pi}{6},\\ x=\\frac{5\\pi}{6}$",
            "$x=\\frac{\\pi}{6},\\ x=\\frac{11\\pi}{6}$",
            "$x=\\frac{\\pi}{3},\\ x=\\frac{2\\pi}{3}$",
            "$x=\\frac{\\pi}{6}$"
          ],
          "answer": 0,
          "solution": "$\\cos^2x=\\frac34 \\Rightarrow \\cos x=\\pm\\frac{\\sqrt3}{2}$\nفي $[0,\\pi]$: $\\cos x=\\frac{\\sqrt3}{2} \\Rightarrow x=\\frac{\\pi}{6}$ ، و $\\cos x=-\\frac{\\sqrt3}{2} \\Rightarrow x=\\frac{5\\pi}{6}$"
        },
        {
          "id": "u2e3q10",
          "lesson": "u2-l3",
          "difficulty": "medium",
          "text": "عدد حلول المعادلة: $\\sin 2x=-\\cos x$ في الفترة $[0,\\,2\\pi)$ هو:",
          "options": [
            "$4$",
            "$2$",
            "$3$",
            "$6$"
          ],
          "answer": 0,
          "solution": "$2\\sin x\\cos x+\\cos x=0 \\Rightarrow \\cos x(2\\sin x+1)=0$\n$\\cos x=0 \\Rightarrow x=\\frac{\\pi}{2},\\ \\frac{3\\pi}{2}$ ، و $\\sin x=-\\frac12 \\Rightarrow x=\\frac{7\\pi}{6},\\ \\frac{11\\pi}{6}$ ، إذن $4$ حلول."
        },
        {
          "id": "u2e3q11",
          "lesson": "u2-l3",
          "difficulty": "hard",
          "text": "مجموعة حلّ المعادلة: $\\sec^{2}x-2\\tan x=0$ في الفترة $[0,\\,2\\pi)$ هي:",
          "options": [
            "$x=\\frac{\\pi}{4},\\ x=\\frac{5\\pi}{4}$",
            "$x=\\frac{\\pi}{4}$",
            "$x=\\frac{\\pi}{4},\\ x=\\frac{3\\pi}{4}$",
            "$x=\\frac{3\\pi}{4},\\ x=\\frac{7\\pi}{4}$"
          ],
          "answer": 0,
          "solution": "نعوّض $\\sec^2x=1+\\tan^2x$: $\\tan^2x-2\\tan x+1=0 \\Rightarrow (\\tan x-1)^2=0 \\Rightarrow \\tan x=1$\n$x=\\frac{\\pi}{4}$ أو $x=\\frac{5\\pi}{4}$"
        },
        {
          "id": "u2e3q12",
          "lesson": "u2-l3",
          "difficulty": "medium",
          "text": "مجموع حلول المعادلة: $2\\sin x=\\sqrt{3}$ في الفترة $[0,\\,2\\pi)$ هو:",
          "options": [
            "$\\pi$",
            "$\\frac{2\\pi}{3}$",
            "$\\frac{4\\pi}{3}$",
            "$2\\pi$"
          ],
          "answer": 0,
          "solution": "$\\sin x=\\frac{\\sqrt3}{2} \\Rightarrow x=\\frac{\\pi}{3}$ أو $x=\\frac{2\\pi}{3}$ ، ومجموعهما $\\pi$"
        }
      ]
    }
  ]
};

export default unit;
