// Generated by question-bank/u3.py (verified). Do not edit by hand.
import type { Unit } from '../types';

const unit: Unit = {
  "id": "u3",
  "number": 3,
  "semester": 1,
  "title": "التفاضل وتطبيقاته",
  "description": "مشتقات الاقترانات الأسية واللوغاريتمية والمثلثية وتطبيقاتها (المماس والعمودي والحركة)، مشتقتا الضرب والقسمة والمشتقات العليا، قاعدة السلسلة والمعادلات الوسيطية، الاشتقاق الضمني، والمعدلات المرتبطة.",
  "lessons": [
    {
      "id": "u3-l1",
      "title": "مشتقة اقترانات خاصة"
    },
    {
      "id": "u3-l2",
      "title": "مشتقتا الضرب والقسمة والمشتقات العليا"
    },
    {
      "id": "u3-l3",
      "title": "قاعدة السلسلة"
    },
    {
      "id": "u3-l4",
      "title": "الاشتقاق الضمني"
    },
    {
      "id": "u3-l5",
      "title": "المُعدَّلات المرتبطة"
    }
  ],
  "exams": [
    {
      "id": "u3-e1",
      "title": "الاختبار الأول",
      "questions": [
        {
          "id": "u3e1q1",
          "lesson": "u3-l1",
          "difficulty": "easy",
          "text": "إذا كان: $f(x)=3e^{x}-2\\ln x+5^{x}$ ، فإنّ $f'(1)$ تساوي:",
          "options": [
            "$3e-2+5\\ln 5$",
            "$3e+2+5\\ln 5$",
            "$3e-2+5$",
            "$3e-2+\\ln 5$"
          ],
          "answer": 0,
          "solution": "$f'(x)=3e^x-\\dfrac{2}{x}+5^x\\ln5$ ، إذن $f'(1)=3e-2+5\\ln5$"
        },
        {
          "id": "u3e1q2",
          "lesson": "u3-l1",
          "difficulty": "medium",
          "text": "معادلة العمودي على المماس لمنحنى الاقتران: $y=2\\sin x+\\cos x$ عند $x=0$ هي:",
          "options": [
            "$y=-\\frac{1}{2}x+1$",
            "$y=2x+1$",
            "$y=-2x+1$",
            "$y=\\frac{1}{2}x+1$"
          ],
          "answer": 0,
          "solution": "نقطة التماس: $y(0)=0+1=1$ ، أي $(0,\\,1)$\n$y'=2\\cos x-\\sin x \\Rightarrow$ ميل المماس عند $x=0$ يساوي $2$ ، فميل العمودي $-\\frac12$\n$y-1=-\\frac12(x-0) \\Rightarrow y=-\\frac12x+1$"
        },
        {
          "id": "u3e1q3",
          "lesson": "u3-l1",
          "difficulty": "medium",
          "text": "يتحرّك جُسيم في مسار مستقيم، ويُعطى موقعه بالاقتران: $s(t)=t^{2}-6\\ln t$ ، حيث $t>0$ الزمن بالثواني، و $s$ الموقع بالأمتار. الزمن الذي يكون عنده الجُسيم في حالة سكون لحظي هو:",
          "options": [
            "$\\sqrt{3}\\ \\text{s}$",
            "$3\\ \\text{s}$",
            "$\\sqrt{6}\\ \\text{s}$",
            "$6\\ \\text{s}$"
          ],
          "answer": 0,
          "solution": "$v(t)=s'(t)=2t-\\dfrac{6}{t}$\n$v(t)=0 \\Rightarrow 2t^2=6 \\Rightarrow t^2=3 \\Rightarrow t=\\sqrt3$ (لأن $t>0$)"
        },
        {
          "id": "u3e1q4",
          "lesson": "u3-l2",
          "difficulty": "easy",
          "text": "إذا كان: $f(x)=x^{2}e^{x}$ ، فإنّ $f'(1)$ تساوي:",
          "options": [
            "$3e$",
            "$2e$",
            "$e$",
            "$e^{2}$"
          ],
          "answer": 0,
          "solution": "بقاعدة مشتقة الضرب: $f'(x)=2xe^x+x^2e^x=e^x(x^2+2x)$ ، إذن $f'(1)=3e$"
        },
        {
          "id": "u3e1q5",
          "lesson": "u3-l2",
          "difficulty": "hard",
          "text": "إذا كان: $f(x)=xe^{x}$ ، فإنّ $f''(x)-2f'(x)+f(x)$ يساوي:",
          "options": [
            "$0$",
            "$e^{x}$",
            "$xe^{x}$",
            "$2e^{x}$"
          ],
          "answer": 0,
          "solution": "$f'(x)=e^x+xe^x=e^x(x+1)$ ، $f''(x)=e^x(x+1)+e^x=e^x(x+2)$\n$f''-2f'+f=e^x\\left[(x+2)-2(x+1)+x\\right]=e^x(0)=0$"
        },
        {
          "id": "u3e1q6",
          "lesson": "u3-l3",
          "difficulty": "easy",
          "text": "إذا كان: $y=\\ln(\\cos x)$ ، حيث $0<x<\\frac{\\pi}{2}$ ، فإنّ $\\dfrac{dy}{dx}$ تساوي:",
          "options": [
            "$-\\tan x$",
            "$\\tan x$",
            "$-\\cot x$",
            "$\\frac{1}{\\cos x}$"
          ],
          "answer": 0,
          "solution": "بقاعدة السلسلة: $\\dfrac{dy}{dx}=\\dfrac{1}{\\cos x}\\cdot(-\\sin x)=-\\tan x$"
        },
        {
          "id": "u3e1q7",
          "lesson": "u3-l3",
          "difficulty": "medium",
          "text": "إذا كان: $x=3\\sin t$ ، $y=2\\cos t$ ، فإنّ $\\dfrac{dy}{dx}$ عندما $t=\\frac{\\pi}{3}$ هي:",
          "options": [
            "$-\\frac{2\\sqrt{3}}{3}$",
            "$\\frac{2\\sqrt{3}}{3}$",
            "$-\\frac{\\sqrt{3}}{2}$",
            "$-\\frac{3\\sqrt{3}}{2}$"
          ],
          "answer": 0,
          "solution": "$\\dfrac{dy}{dx}=\\dfrac{dy/dt}{dx/dt}=\\dfrac{-2\\sin t}{3\\cos t}=-\\frac23\\tan t$\nعند $t=\\frac{\\pi}{3}$: $-\\frac23\\sqrt3=-\\dfrac{2\\sqrt3}{3}$"
        },
        {
          "id": "u3e1q8",
          "lesson": "u3-l3",
          "difficulty": "medium",
          "text": "يُبيّن الشكل الآتي منحنيي الاقترانين $f(x)$ و $g(x)$. إذا كان: $h(x)=f\\big(g(x)\\big)$ ، فإنّ $h'(1)$ تساوي:",
          "options": [
            "$-2$",
            "$2$",
            "$-1$",
            "$4$"
          ],
          "answer": 0,
          "solution": "بقاعدة السلسلة: $h'(1)=f'\\big(g(1)\\big)\\cdot g'(1)$\nمن الشكل: $g(1)=2$ و $g'(1)=$ ميل القطعة من $(0,0)$ إلى $(2,4)$ $=2$\n$f'(2)=$ ميل القطعة من $(0,5)$ إلى $(3,2)$ $=-1$ ، إذن $h'(1)=(-1)(2)=-2$",
          "figure": "fig/u3e1q8.svg"
        },
        {
          "id": "u3e1q9",
          "lesson": "u3-l4",
          "difficulty": "easy",
          "text": "ميل المماس لمنحنى العلاقة: $x^{2}+3xy+y^{2}=11$ عند النقطة $(1,\\,2)$ هو:",
          "options": [
            "$-\\frac{8}{7}$",
            "$\\frac{8}{7}$",
            "$-\\frac{7}{8}$",
            "$-2$"
          ],
          "answer": 0,
          "solution": "باشتقاق الطرفين ضمنيًّا: $2x+3y+3x\\dfrac{dy}{dx}+2y\\dfrac{dy}{dx}=0 \\Rightarrow \\dfrac{dy}{dx}=-\\dfrac{2x+3y}{3x+2y}$\nعند $(1,2)$: $\\dfrac{dy}{dx}=-\\dfrac{2+6}{3+4}=-\\dfrac87$"
        },
        {
          "id": "u3e1q10",
          "lesson": "u3-l4",
          "difficulty": "hard",
          "text": "إذا مثّل المستقيم $l$ مماسًّا لمنحنى العلاقة: $x^{2}y+y^{3}=10$ عند النقطة $(3,\\,1)$ ، فإنّ المقطع $x$ للمستقيم $l$ هو:",
          "options": [
            "$5$",
            "$\\frac{5}{2}$",
            "$3$",
            "$1$"
          ],
          "answer": 0,
          "solution": "باشتقاق الطرفين: $2xy+x^2y'+3y^2y'=0 \\Rightarrow y'=\\dfrac{-2xy}{x^2+3y^2}$ ، عند $(3,1)$: $y'=\\dfrac{-6}{12}=-\\dfrac12$\nمعادلة المماس: $y-1=-\\frac12(x-3)$ ، وعند $y=0$: $-1=-\\frac12(x-3) \\Rightarrow x=5$"
        },
        {
          "id": "u3e1q11",
          "lesson": "u3-l5",
          "difficulty": "medium",
          "text": "خزّان على شكل أسطوانة دائرية قائمة، طول قُطر قاعدتها $2\\ \\text{m}$. يُضَخّ إليه الماء بمعدّل $300\\ \\text{L/min}$ ، فإنّ معدّل ارتفاع الماء في الخزّان عند أيّ لحظة هو:",
          "options": [
            "$\\frac{3}{10\\pi}\\ \\text{m/min}$",
            "$\\frac{300}{\\pi}\\ \\text{m/min}$",
            "$\\frac{3}{40\\pi}\\ \\text{m/min}$",
            "$\\frac{10}{3\\pi}\\ \\text{m/min}$"
          ],
          "answer": 0,
          "solution": "نحوّل الوحدة: $300\\ \\text{L}=0.3\\ \\text{m}^3$ (لأن $1\\ \\text{m}^3=1000\\ \\text{L}$)\nنصف القطر $r=1\\ \\text{m}$ ، $V=\\pi r^2h=\\pi h \\Rightarrow \\dfrac{dV}{dt}=\\pi\\dfrac{dh}{dt}$\n$0.3=\\pi\\dfrac{dh}{dt} \\Rightarrow \\dfrac{dh}{dt}=\\dfrac{0.3}{\\pi}=\\dfrac{3}{10\\pi}\\ \\text{m/min}$"
        },
        {
          "id": "u3e1q12",
          "lesson": "u3-l5",
          "difficulty": "medium",
          "text": "مربّع تزداد مساحته بمعدّل $24\\ \\text{cm}^2/\\text{s}$. معدّل تغيّر محيطه في اللحظة التي يكون فيها طول ضلعه $6\\ \\text{cm}$ هو:",
          "options": [
            "$8\\ \\text{cm/s}$",
            "$2\\ \\text{cm/s}$",
            "$4\\ \\text{cm/s}$",
            "$12\\ \\text{cm/s}$"
          ],
          "answer": 0,
          "solution": "$A=s^2 \\Rightarrow \\dfrac{dA}{dt}=2s\\dfrac{ds}{dt} \\Rightarrow 24=12\\dfrac{ds}{dt} \\Rightarrow \\dfrac{ds}{dt}=2\\ \\text{cm/s}$\nالمحيط $P=4s \\Rightarrow \\dfrac{dP}{dt}=4\\dfrac{ds}{dt}=8\\ \\text{cm/s}$"
        }
      ]
    },
    {
      "id": "u3-e2",
      "title": "الاختبار الثاني",
      "questions": [
        {
          "id": "u3e2q1",
          "lesson": "u3-l1",
          "difficulty": "easy",
          "text": "إذا كان: $f(x)=4\\tan x-3\\sec x$ ، فإنّ $f'\\left(\\frac{\\pi}{4}\\right)$ تساوي:",
          "options": [
            "$8-3\\sqrt{2}$",
            "$8+3\\sqrt{2}$",
            "$4-3\\sqrt{2}$",
            "$2-3\\sqrt{2}$"
          ],
          "answer": 0,
          "solution": "$f'(x)=4\\sec^2x-3\\sec x\\tan x$\n$\\sec\\frac{\\pi}{4}=\\sqrt2$ ، $\\tan\\frac{\\pi}{4}=1$ ، إذن $f'\\left(\\frac{\\pi}{4}\\right)=4(2)-3\\sqrt2=8-3\\sqrt2$"
        },
        {
          "id": "u3e2q2",
          "lesson": "u3-l1",
          "difficulty": "hard",
          "text": "معادلة المماس لمنحنى الاقتران $y=e^{x}$ ، والمارّ بنقطة الأصل، هي:",
          "options": [
            "$y=ex$",
            "$y=x+1$",
            "$y=ex-e$",
            "$y=2x$"
          ],
          "answer": 0,
          "solution": "نفرض نقطة التماس $(a,\\,e^a)$ ، فميل المماس $e^a$ ومعادلته: $y-e^a=e^a(x-a)$\nيمر بالأصل: $0-e^a=e^a(0-a) \\Rightarrow a=1$\nإذن المماس: $y-e=e(x-1) \\Rightarrow y=ex$"
        },
        {
          "id": "u3e2q3",
          "lesson": "u3-l1",
          "difficulty": "medium",
          "text": "يتحرّك جُسيم في مسار مستقيم، ويُعطى موقعه بالاقتران: $s(t)=2\\sin t+t$ ، حيث $0\\le t\\le2\\pi$. الأزمنة التي تنعدم عندها سرعة الجُسيم هي:",
          "options": [
            "$t=\\frac{2\\pi}{3},\\ t=\\frac{4\\pi}{3}$",
            "$t=\\frac{\\pi}{3},\\ t=\\frac{5\\pi}{3}$",
            "$t=\\frac{5\\pi}{6},\\ t=\\frac{7\\pi}{6}$",
            "$t=\\frac{\\pi}{2},\\ t=\\frac{3\\pi}{2}$"
          ],
          "answer": 0,
          "solution": "$v(t)=2\\cos t+1=0 \\Rightarrow \\cos t=-\\frac12$\n$t=\\frac{2\\pi}{3}$ أو $t=\\frac{4\\pi}{3}$"
        },
        {
          "id": "u3e2q4",
          "lesson": "u3-l2",
          "difficulty": "easy",
          "text": "إذا كان: $f(x)=\\frac{x-1}{x+1}$ ، فإنّ $f'(x)$ تساوي:",
          "options": [
            "$\\frac{2}{(x+1)^{2}}$",
            "$-\\frac{2}{(x+1)^{2}}$",
            "$\\frac{1}{(x+1)^{2}}$",
            "$\\frac{2x}{(x+1)^{2}}$"
          ],
          "answer": 0,
          "solution": "بقاعدة مشتقة القسمة: $f'(x)=\\dfrac{(1)(x+1)-(x-1)(1)}{(x+1)^2}=\\dfrac{2}{(x+1)^2}$"
        },
        {
          "id": "u3e2q5",
          "lesson": "u3-l2",
          "difficulty": "medium",
          "text": "إذا كان: $f(x)=\\ln x$ ، فإنّ المشتقة الرابعة $f^{(4)}(x)$ تساوي:",
          "options": [
            "$-\\frac{6}{x^{4}}$",
            "$\\frac{6}{x^{4}}$",
            "$-\\frac{24}{x^{5}}$",
            "$\\frac{2}{x^{3}}$"
          ],
          "answer": 0,
          "solution": "$f'(x)=\\dfrac1x$ ، $f''(x)=-\\dfrac{1}{x^2}$ ، $f'''(x)=\\dfrac{2}{x^3}$ ، $f^{(4)}(x)=-\\dfrac{6}{x^4}$"
        },
        {
          "id": "u3e2q6",
          "lesson": "u3-l3",
          "difficulty": "easy",
          "text": "إذا كان: $f(x)=(3x^{2}-1)^{4}$ ، فإنّ $f'(1)$ تساوي:",
          "options": [
            "$192$",
            "$32$",
            "$96$",
            "$384$"
          ],
          "answer": 0,
          "solution": "$f'(x)=4(3x^2-1)^3\\cdot6x$ ، إذن $f'(1)=4(2)^3(6)=192$"
        },
        {
          "id": "u3e2q7",
          "lesson": "u3-l3",
          "difficulty": "medium",
          "text": "يُمثّل الاقتران: $P(t)=\\frac{500}{1+e^{-t}}$ عدد أفراد مجتمع من الطيور بعد $t$ سنة. معدّل تغيّر عدد الطيور (طائر/سنة) عندما $t=0$ هو:",
          "options": [
            "$125$",
            "$250$",
            "$-125$",
            "$500$"
          ],
          "answer": 0,
          "solution": "$P(t)=500(1+e^{-t})^{-1} \\Rightarrow P'(t)=-500(1+e^{-t})^{-2}\\cdot(-e^{-t})=\\dfrac{500e^{-t}}{(1+e^{-t})^2}$\n$P'(0)=\\dfrac{500(1)}{(2)^2}=125$ طائرًا في السنة"
        },
        {
          "id": "u3e2q8",
          "lesson": "u3-l3",
          "difficulty": "hard",
          "text": "إذا أُعطي منحنى بالمعادلتين الوسيطيتين: $x=t^{2}-1$ ، $y=t^{3}-3t$ ، فإنّ النقاط على المنحنى التي يكون عندها المماس أفقيًّا هي:",
          "options": [
            "$(0,-2),\\ (0,2)$",
            "$(0,2)$",
            "$(-1,0),\\ (3,2)$",
            "$(1,-2),\\ (1,2)$"
          ],
          "answer": 0,
          "solution": "المماس أفقي عندما $\\dfrac{dy}{dt}=0$ و $\\dfrac{dx}{dt}\\ne0$: $3t^2-3=0 \\Rightarrow t=\\pm1$ ، و $\\dfrac{dx}{dt}=2t\\ne0$ عندهما\n$t=1$: $(0,\\,-2)$ ، $t=-1$: $(0,\\,2)$"
        },
        {
          "id": "u3e2q9",
          "lesson": "u3-l4",
          "difficulty": "medium",
          "text": "إذا كان: $x\\sin y+y=1$ ، فإنّ $\\dfrac{dy}{dx}$ عند النقطة $(0,\\,1)$ تساوي:",
          "options": [
            "$-\\sin 1$",
            "$\\sin 1$",
            "$-\\cos 1$",
            "$-1$"
          ],
          "answer": 0,
          "solution": "باشتقاق الطرفين: $\\sin y+x\\cos y\\,\\dfrac{dy}{dx}+\\dfrac{dy}{dx}=0 \\Rightarrow \\dfrac{dy}{dx}=\\dfrac{-\\sin y}{x\\cos y+1}$\nعند $(0,1)$: $\\dfrac{dy}{dx}=\\dfrac{-\\sin1}{0+1}=-\\sin1$"
        },
        {
          "id": "u3e2q10",
          "lesson": "u3-l4",
          "difficulty": "hard",
          "text": "إذا كان: $x^{2}+4y^{2}=8$ ، فإنّ $\\dfrac{d^{2}y}{dx^{2}}$ عند النقطة $(2,\\,1)$ تساوي:",
          "options": [
            "$-\\frac{1}{2}$",
            "$\\frac{1}{2}$",
            "$-\\frac{1}{4}$",
            "$-2$"
          ],
          "answer": 0,
          "solution": "$2x+8yy'=0 \\Rightarrow y'=-\\dfrac{x}{4y}$ ، وعند $(2,1)$: $y'=-\\frac12$\n$y''=-\\dfrac{4y-x\\cdot4y'}{16y^2}=-\\dfrac{y-xy'}{4y^2}$ ، وعند $(2,1)$: $y''=-\\dfrac{1-2\\left(-\\frac12\\right)}{4}=-\\dfrac{2}{4}=-\\dfrac12$"
        },
        {
          "id": "u3e2q11",
          "lesson": "u3-l5",
          "difficulty": "easy",
          "text": "تزداد مساحة دائرة بمعدّل $10\\pi\\ \\text{cm}^2/\\text{s}$. معدّل تزايد نصف قطرها عندما يكون نصف قطرها $5\\ \\text{cm}$ هو:",
          "options": [
            "$1\\ \\text{cm/s}$",
            "$2\\ \\text{cm/s}$",
            "$5\\ \\text{cm/s}$",
            "$10\\ \\text{cm/s}$"
          ],
          "answer": 0,
          "solution": "$A=\\pi r^2 \\Rightarrow \\dfrac{dA}{dt}=2\\pi r\\dfrac{dr}{dt} \\Rightarrow 10\\pi=2\\pi(5)\\dfrac{dr}{dt} \\Rightarrow \\dfrac{dr}{dt}=1\\ \\text{cm/s}$"
        },
        {
          "id": "u3e2q12",
          "lesson": "u3-l5",
          "difficulty": "hard",
          "text": "سُلّم طوله $5\\ \\text{m}$ يستند طرفه العلوي إلى جدار رأسي وطرفه السفلي على أرض أفقية. إذا انزلق طرفه العلوي إلى الأسفل بمعدّل $0.6\\ \\text{m/s}$ ، فإنّ معدّل ابتعاد طرفه السفلي عن الجدار عندما يكون طرفه العلوي على ارتفاع $4\\ \\text{m}$ هو:",
          "options": [
            "$0.8\\ \\text{m/s}$",
            "$0.45\\ \\text{m/s}$",
            "$0.6\\ \\text{m/s}$",
            "$1.2\\ \\text{m/s}$"
          ],
          "answer": 0,
          "solution": "$x^2+y^2=25$ ، وعند $y=4$: $x=3$\n$2x\\dfrac{dx}{dt}+2y\\dfrac{dy}{dt}=0 \\Rightarrow 3\\dfrac{dx}{dt}+4(-0.6)=0 \\Rightarrow \\dfrac{dx}{dt}=0.8\\ \\text{m/s}$"
        }
      ]
    },
    {
      "id": "u3-e3",
      "title": "الاختبار الثالث",
      "questions": [
        {
          "id": "u3e3q1",
          "lesson": "u3-l1",
          "difficulty": "easy",
          "text": "إذا كان: $f(x)=x^{3}+2^{x}$ ، فإنّ $f'(0)$ تساوي:",
          "options": [
            "$\\ln 2$",
            "$1$",
            "$0$",
            "$2$"
          ],
          "answer": 0,
          "solution": "$f'(x)=3x^2+2^x\\ln2$ ، إذن $f'(0)=0+1\\cdot\\ln2=\\ln2$"
        },
        {
          "id": "u3e3q2",
          "lesson": "u3-l1",
          "difficulty": "medium",
          "text": "إذا كان المماس لمنحنى الاقتران: $y=a\\ln x$ عند $x=2$ يوازي المستقيم $y=3x$ ، فإنّ قيمة الثابت $a$ هي:",
          "options": [
            "$6$",
            "$\\frac{3}{2}$",
            "$3$",
            "$2$"
          ],
          "answer": 0,
          "solution": "$y'=\\dfrac{a}{x}$ ، والمماس يوازي المستقيم إذا تساوى الميلان: $\\dfrac{a}{2}=3 \\Rightarrow a=6$"
        },
        {
          "id": "u3e3q3",
          "lesson": "u3-l1",
          "difficulty": "hard",
          "text": "يتحرّك جُسيم في مسار مستقيم، ويُعطى موقعه بالاقتران: $s(t)=e^{t}-6t$ ، حيث $t\\ge0$ بالثواني و $s$ بالأمتار. تسارع الجُسيم عندما تنعدم سرعته هو:",
          "options": [
            "$6\\ \\text{m/s}^2$",
            "$0\\ \\text{m/s}^2$",
            "$\\ln 6\\ \\text{m/s}^2$",
            "$e^{6}\\ \\text{m/s}^2$"
          ],
          "answer": 0,
          "solution": "$v(t)=e^t-6=0 \\Rightarrow t=\\ln6$\n$a(t)=e^t \\Rightarrow a(\\ln6)=e^{\\ln6}=6\\ \\text{m/s}^2$"
        },
        {
          "id": "u3e3q4",
          "lesson": "u3-l2",
          "difficulty": "medium",
          "text": "إذا كان: $f(2)=3,\\ f'(2)=-1,\\ g(2)=4,\\ g'(2)=2$ ، فإنّ $\\left(\\dfrac{f}{g}\\right)'(2)$ تساوي:",
          "options": [
            "$-\\frac{5}{8}$",
            "$\\frac{5}{8}$",
            "$-\\frac{1}{8}$",
            "$-\\frac{1}{2}$"
          ],
          "answer": 0,
          "solution": "$\\left(\\dfrac{f}{g}\\right)'(2)=\\dfrac{f'(2)g(2)-f(2)g'(2)}{\\big(g(2)\\big)^2}=\\dfrac{(-1)(4)-(3)(2)}{16}=\\dfrac{-10}{16}=-\\dfrac58$"
        },
        {
          "id": "u3e3q5",
          "lesson": "u3-l2",
          "difficulty": "medium",
          "text": "إذا كان: $f(x)=(x+b)e^{x}$ ، وكان $f'(0)=3$ ، فإنّ قيمة الثابت $b$ هي:",
          "options": [
            "$2$",
            "$3$",
            "$1$",
            "$-2$"
          ],
          "answer": 0,
          "solution": "$f'(x)=e^x+(x+b)e^x$ ، إذن $f'(0)=1+b=3 \\Rightarrow b=2$"
        },
        {
          "id": "u3e3q6",
          "lesson": "u3-l3",
          "difficulty": "easy",
          "text": "إذا كان: $y=\\sec 3x$ ، فإنّ $\\dfrac{dy}{dx}$ تساوي:",
          "options": [
            "$3\\sec 3x\\tan 3x$",
            "$\\sec 3x\\tan 3x$",
            "$3\\sec^{2}3x$",
            "$3\\tan^{2}3x$"
          ],
          "answer": 0,
          "solution": "بقاعدة السلسلة: $\\dfrac{dy}{dx}=\\sec3x\\tan3x\\cdot3=3\\sec3x\\tan3x$"
        },
        {
          "id": "u3e3q7",
          "lesson": "u3-l3",
          "difficulty": "medium",
          "text": "إذا كان $h(x)=\\sqrt{f(x)}$ ، وكان $f(1)=4$ و $f'(1)=6$ ، فإنّ $h'(1)$ تساوي:",
          "options": [
            "$\\frac{3}{2}$",
            "$3$",
            "$\\frac{1}{2}$",
            "$6$"
          ],
          "answer": 0,
          "solution": "$h'(x)=\\dfrac{f'(x)}{2\\sqrt{f(x)}} \\Rightarrow h'(1)=\\dfrac{6}{2\\sqrt4}=\\dfrac64=\\dfrac32$"
        },
        {
          "id": "u3e3q8",
          "lesson": "u3-l3",
          "difficulty": "hard",
          "text": "إذا كان: $f(x)=\\log_{2}(x^{2}+4)$ ، فإنّ $f'(2)$ تساوي:",
          "options": [
            "$\\frac{1}{\\ln 4}$",
            "$\\frac{1}{2}$",
            "$\\frac{1}{\\ln 2}$",
            "$\\frac{2}{\\ln 2}$"
          ],
          "answer": 0,
          "solution": "$f'(x)=\\dfrac{2x}{(x^2+4)\\ln2}$ ، إذن $f'(2)=\\dfrac{4}{8\\ln2}=\\dfrac{1}{2\\ln2}=\\dfrac{1}{\\ln4}$"
        },
        {
          "id": "u3e3q9",
          "lesson": "u3-l4",
          "difficulty": "easy",
          "text": "إذا كان: $y^{3}+xy=3$ ، فإنّ $\\dfrac{dy}{dx}$ عند النقطة $(2,\\,1)$ تساوي:",
          "options": [
            "$-\\frac{1}{5}$",
            "$\\frac{1}{5}$",
            "$-\\frac{1}{3}$",
            "$-1$"
          ],
          "answer": 0,
          "solution": "باشتقاق الطرفين: $3y^2y'+y+xy'=0 \\Rightarrow y'=\\dfrac{-y}{3y^2+x}$\nعند $(2,1)$: $y'=\\dfrac{-1}{3+2}=-\\dfrac15$"
        },
        {
          "id": "u3e3q10",
          "lesson": "u3-l4",
          "difficulty": "hard",
          "text": "إذا كان: $x=e^{t}$ ، $y=t^{2}$ ، فإنّ $\\dfrac{d^{2}y}{dx^{2}}$ عندما $t=0$ تساوي:",
          "options": [
            "$2$",
            "$0$",
            "$-2$",
            "$1$"
          ],
          "answer": 0,
          "solution": "$\\dfrac{dy}{dx}=\\dfrac{2t}{e^t}=2te^{-t}$\n$\\dfrac{d^2y}{dx^2}=\\dfrac{\\frac{d}{dt}\\left(2te^{-t}\\right)}{dx/dt}=\\dfrac{2e^{-t}-2te^{-t}}{e^t}$ ، وعند $t=0$: $\\dfrac{2-0}{1}=2$"
        },
        {
          "id": "u3e3q11",
          "lesson": "u3-l5",
          "difficulty": "medium",
          "text": "يتمدّد مكعّب بحيث يزداد حجمه بمعدّل $36\\ \\text{cm}^3/\\text{s}$. معدّل تزايد مساحة سطحه الكلية عندما يكون طول حرفه $2\\ \\text{cm}$ هو:",
          "options": [
            "$72\\ \\text{cm}^2\\text{/s}$",
            "$36\\ \\text{cm}^2\\text{/s}$",
            "$24\\ \\text{cm}^2\\text{/s}$",
            "$144\\ \\text{cm}^2\\text{/s}$"
          ],
          "answer": 0,
          "solution": "$V=s^3 \\Rightarrow 36=3(2)^2\\dfrac{ds}{dt} \\Rightarrow \\dfrac{ds}{dt}=3\\ \\text{cm/s}$\n$A=6s^2 \\Rightarrow \\dfrac{dA}{dt}=12s\\dfrac{ds}{dt}=12(2)(3)=72\\ \\text{cm}^2/\\text{s}$"
        },
        {
          "id": "u3e3q12",
          "lesson": "u3-l5",
          "difficulty": "hard",
          "text": "رجل طوله $1.8\\ \\text{m}$ يسير مبتعدًا عن عمود إنارة ارتفاعه $6\\ \\text{m}$ بسرعة $1.4\\ \\text{m/s}$. معدّل تغيّر طول ظلّه هو:",
          "options": [
            "$0.6\\ \\text{m/s}$",
            "$1.4\\ \\text{m/s}$",
            "$2\\ \\text{m/s}$",
            "$0.42\\ \\text{m/s}$"
          ],
          "answer": 0,
          "solution": "نفرض $x$ بُعد الرجل عن العمود، و $s$ طول ظله. من تشابه المثلثين: $\\dfrac{s}{1.8}=\\dfrac{x+s}{6}$\n$6s=1.8x+1.8s \\Rightarrow 4.2s=1.8x \\Rightarrow s=\\dfrac37x$\n$\\dfrac{ds}{dt}=\\dfrac37\\cdot\\dfrac{dx}{dt}=\\dfrac37(1.4)=0.6\\ \\text{m/s}$"
        }
      ]
    },
    {
      "id": "u3-e4",
      "title": "الاختبار الرابع",
      "questions": [
        {
          "id": "u3e4q1",
          "lesson": "u3-l1",
          "difficulty": "easy",
          "text": "إذا كان: $f(x)=7\\log x$ ، حيث $\\log$ هو اللوغاريتم للأساس $10$ ، فإنّ $f'(x)$ تساوي:",
          "options": [
            "$\\frac{7}{x\\ln 10}$",
            "$\\frac{7}{x}$",
            "$\\frac{7\\ln 10}{x}$",
            "$\\frac{7}{10x}$"
          ],
          "answer": 0,
          "solution": "$\\dfrac{d}{dx}\\log_ax=\\dfrac{1}{x\\ln a}$ ، إذن $f'(x)=\\dfrac{7}{x\\ln10}$"
        },
        {
          "id": "u3e4q2",
          "lesson": "u3-l1",
          "difficulty": "medium",
          "text": "يتحرّك جُسيم في مسار مستقيم، ويُعطى موقعه بالاقتران: $s(t)=3\\cos t+4\\sin t$ ، حيث $t$ بالثواني و $s$ بالأمتار. تسارع الجُسيم عندما $t=\\frac{\\pi}{2}$ هو:",
          "options": [
            "$-4\\ \\text{m/s}^2$",
            "$4\\ \\text{m/s}^2$",
            "$-3\\ \\text{m/s}^2$",
            "$3\\ \\text{m/s}^2$"
          ],
          "answer": 0,
          "solution": "$v(t)=-3\\sin t+4\\cos t$ ، $a(t)=-3\\cos t-4\\sin t$\n$a\\left(\\frac{\\pi}{2}\\right)=0-4=-4\\ \\text{m/s}^2$"
        },
        {
          "id": "u3e4q3",
          "lesson": "u3-l1",
          "difficulty": "medium",
          "text": "النقطة على منحنى الاقتران: $y=e^{x}-2x$ التي يكون عندها المماس أفقيًّا هي:",
          "options": [
            "$(\\ln 2,\\ 2-2\\ln 2)$",
            "$(\\ln 2,\\ 2+2\\ln 2)$",
            "$(2,\\ e^{2}-4)$",
            "$(0,\\ 1)$"
          ],
          "answer": 0,
          "solution": "$y'=e^x-2=0 \\Rightarrow x=\\ln2$\n$y(\\ln2)=e^{\\ln2}-2\\ln2=2-2\\ln2$"
        },
        {
          "id": "u3e4q4",
          "lesson": "u3-l2",
          "difficulty": "easy",
          "text": "إذا كان: $f(x)=x\\ln x-x$ ، فإنّ $f'(x)$ تساوي:",
          "options": [
            "$\\ln x$",
            "$\\ln x-1$",
            "$\\frac{1}{x}$",
            "$x\\ln x$"
          ],
          "answer": 0,
          "solution": "$f'(x)=\\left(1\\cdot\\ln x+x\\cdot\\dfrac1x\\right)-1=\\ln x+1-1=\\ln x$"
        },
        {
          "id": "u3e4q5",
          "lesson": "u3-l2",
          "difficulty": "medium",
          "text": "يُبيّن الشكل الآتي منحنيي الاقترانين $f(x)$ و $g(x)$. إذا كان: $q(x)=\\dfrac{f(x)}{g(x)}$ ، فإنّ $q'(2)$ تساوي:",
          "options": [
            "$-1$",
            "$1$",
            "$-\\frac{1}{2}$",
            "$0$"
          ],
          "answer": 0,
          "solution": "من الشكل: $f(2)=4$ ، $f'(2)=$ ميل القطعة من $(0,6)$ إلى $(4,2)$ $=-1$\n$g(2)=2$ ، $g'(2)=$ ميل القطعة من $(0,1)$ إلى $(6,4)$ $=\\frac12$\n$q'(2)=\\dfrac{f'(2)g(2)-f(2)g'(2)}{\\big(g(2)\\big)^2}=\\dfrac{(-1)(2)-(4)\\left(\\frac12\\right)}{4}=\\dfrac{-4}{4}=-1$",
          "figure": "fig/u3e4q5.svg"
        },
        {
          "id": "u3e4q6",
          "lesson": "u3-l3",
          "difficulty": "medium",
          "text": "إذا كان: $f(x)=\\sin^{2}(3x)$ ، فإنّ $f'(x)$ تساوي:",
          "options": [
            "$3\\sin 6x$",
            "$6\\sin 3x$",
            "$2\\sin 3x$",
            "$6\\sin 6x$"
          ],
          "answer": 0,
          "solution": "$f'(x)=2\\sin3x\\cdot\\cos3x\\cdot3=3(2\\sin3x\\cos3x)=3\\sin6x$"
        },
        {
          "id": "u3e4q7",
          "lesson": "u3-l3",
          "difficulty": "hard",
          "text": "إذا كان: $f(x)=e^{x^{2}}\\ln x$ ، فإنّ $f'(1)$ تساوي:",
          "options": [
            "$e$",
            "$2e$",
            "$0$",
            "$1$"
          ],
          "answer": 0,
          "solution": "$f'(x)=2xe^{x^2}\\ln x+e^{x^2}\\cdot\\dfrac1x$\n$f'(1)=2e(0)+e(1)=e$"
        },
        {
          "id": "u3e4q8",
          "lesson": "u3-l3",
          "difficulty": "medium",
          "text": "إذا كان: $x=1+\\cos 2t$ ، $y=\\sin 2t$ ، فإنّ $\\dfrac{dy}{dx}$ عندما $t=\\frac{\\pi}{8}$ تساوي:",
          "options": [
            "$-1$",
            "$1$",
            "$-\\sqrt{2}$",
            "$\\frac{\\sqrt{2}}{2}$"
          ],
          "answer": 0,
          "solution": "$\\dfrac{dy}{dx}=\\dfrac{2\\cos2t}{-2\\sin2t}=-\\cot2t$\nعند $t=\\frac{\\pi}{8}$: $-\\cot\\frac{\\pi}{4}=-1$"
        },
        {
          "id": "u3e4q9",
          "lesson": "u3-l4",
          "difficulty": "medium",
          "text": "إذا كان: $2^{x}y+\\ln y=2$ ، فإنّ $\\dfrac{dy}{dx}$ عند النقطة $(1,\\,1)$ تساوي:",
          "options": [
            "$-\\frac{2\\ln 2}{3}$",
            "$\\frac{2\\ln 2}{3}$",
            "$-\\frac{\\ln 2}{3}$",
            "$-\\frac{2}{3}$"
          ],
          "answer": 0,
          "solution": "باشتقاق الطرفين: $2^x\\ln2\\cdot y+2^xy'+\\dfrac{y'}{y}=0$\nعند $(1,1)$: $2\\ln2+2y'+y'=0 \\Rightarrow y'=-\\dfrac{2\\ln2}{3}$"
        },
        {
          "id": "u3e4q10",
          "lesson": "u3-l4",
          "difficulty": "hard",
          "text": "المماس لمنحنى العلاقة: $x^{2}+y^{2}=25$ عند النقطة $(3,\\,4)$ يقطع محور $x$ عند النقطة التي إحداثيها $x$ يساوي:",
          "options": [
            "$\\frac{25}{3}$",
            "$3$",
            "$\\frac{16}{3}$",
            "$\\frac{25}{4}$"
          ],
          "answer": 0,
          "solution": "$2x+2yy'=0 \\Rightarrow y'=-\\dfrac{x}{y}=-\\dfrac34$ عند $(3,4)$\nالمماس: $y-4=-\\frac34(x-3)$ ، وعند $y=0$: $x-3=\\frac{16}{3} \\Rightarrow x=\\frac{25}{3}$"
        },
        {
          "id": "u3e4q11",
          "lesson": "u3-l5",
          "difficulty": "medium",
          "text": "خزّان على شكل مخروط دائري قائم رأسه إلى الأسفل، ارتفاعه $10\\ \\text{m}$ ونصف قطر قاعدته $5\\ \\text{m}$. يتسرّب منه الماء فينخفض مستوى الماء بمعدّل $0.2\\ \\text{m/min}$. معدّل تناقص حجم الماء عندما يكون عمقه $4\\ \\text{m}$ هو:",
          "options": [
            "$0.8\\pi\\ \\text{m}^3\\text{/min}$",
            "$3.2\\pi\\ \\text{m}^3\\text{/min}$",
            "$0.2\\pi\\ \\text{m}^3\\text{/min}$",
            "$1.6\\pi\\ \\text{m}^3\\text{/min}$"
          ],
          "answer": 0,
          "solution": "من تشابه المثلثات: $\\dfrac{r}{h}=\\dfrac{5}{10} \\Rightarrow r=\\dfrac{h}{2}$ ، و $V=\\frac13\\pi r^2h=\\dfrac{\\pi h^3}{12}$\n$\\dfrac{dV}{dt}=\\dfrac{\\pi h^2}{4}\\cdot\\dfrac{dh}{dt}=\\dfrac{16\\pi}{4}(-0.2)=-0.8\\pi$ ، أي يتناقص الحجم بمعدّل $0.8\\pi\\ \\text{m}^3/\\text{min}$"
        },
        {
          "id": "u3e4q12",
          "lesson": "u3-l5",
          "difficulty": "hard",
          "text": "انطلقت سيارتان في اللحظة نفسها من النقطة نفسها، الأولى نحو الشرق بسرعة $60\\ \\text{km/h}$ ، والثانية نحو الشمال بسرعة $80\\ \\text{km/h}$. معدّل تزايد المسافة بينهما بعد ساعتين من انطلاقهما هو:",
          "options": [
            "$100\\ \\text{km/h}$",
            "$140\\ \\text{km/h}$",
            "$20\\ \\text{km/h}$",
            "$70\\ \\text{km/h}$"
          ],
          "answer": 0,
          "solution": "بعد ساعتين: $x=120$ ، $y=160$ ، والمسافة $D=\\sqrt{120^2+160^2}=200$\n$D^2=x^2+y^2 \\Rightarrow D\\dfrac{dD}{dt}=x\\dfrac{dx}{dt}+y\\dfrac{dy}{dt}$\n$200\\dfrac{dD}{dt}=120(60)+160(80)=20000 \\Rightarrow \\dfrac{dD}{dt}=100\\ \\text{km/h}$"
        }
      ]
    }
  ]
};

export default unit;
