// Generated by question-bank/u5.py (verified). Do not edit by hand.
import type { Unit } from '../types';

const unit: Unit = {
  "id": "u5",
  "number": 5,
  "semester": 2,
  "title": "التكامل",
  "description": "تكامل الاقترانات الأسية واللوغاريتمية والمثلثية وتطبيقاته في الحركة، التكامل بالتعويض وبالكسور الجزئية وبالأجزاء، المساحات والحجوم الدورانية، والمعادلات التفاضلية.",
  "lessons": [
    {
      "id": "u5-l1",
      "title": "تكامل اقترانات خاصة"
    },
    {
      "id": "u5-l2",
      "title": "التكامل بالتعويض"
    },
    {
      "id": "u5-l3",
      "title": "التكامل بالكسور الجزئية"
    },
    {
      "id": "u5-l4",
      "title": "التكامل بالأجزاء"
    },
    {
      "id": "u5-l5",
      "title": "المساحات والحجوم"
    },
    {
      "id": "u5-l6",
      "title": "المعادلات التفاضلية"
    }
  ],
  "exams": [
    {
      "id": "u5-e1",
      "title": "الاختبار الأول",
      "questions": [
        {
          "id": "u5e1q1",
          "lesson": "u5-l1",
          "difficulty": "easy",
          "text": "ناتج: $\\displaystyle\\int\\left(2e^{x}-\\frac{3}{x}+\\sec^{2}x\\right)dx$ هو:",
          "options": [
            "$2e^{x}-3\\ln|x|+\\tan x+C$",
            "$2e^{x}+\\frac{3}{x^{2}}+\\tan x+C$",
            "$2e^{x}-3\\ln|x|-\\tan x+C$",
            "$2xe^{x}-3\\ln|x|+\\tan x+C$"
          ],
          "answer": 0,
          "solution": "$\\displaystyle\\int e^x\\,dx=e^x$ ، $\\displaystyle\\int\\frac1x\\,dx=\\ln|x|$ ، $\\displaystyle\\int\\sec^2x\\,dx=\\tan x$\nإذن الناتج $2e^x-3\\ln|x|+\\tan x+C$"
        },
        {
          "id": "u5e1q2",
          "lesson": "u5-l1",
          "difficulty": "medium",
          "text": "إذا كان: $\\displaystyle\\int_{0}^{\\ln a}4e^{2x}\\,dx=30$ ، حيث $a>0$ ، فإنّ قيمة الثابت $a$ هي:",
          "options": [
            "$4$",
            "$2$",
            "$16$",
            "$\\sqrt{15}$"
          ],
          "answer": 0,
          "solution": "$\\displaystyle\\int_0^{\\ln a}4e^{2x}dx=\\big[2e^{2x}\\big]_0^{\\ln a}=2e^{2\\ln a}-2=2a^2-2$\n$2a^2-2=30 \\Rightarrow a^2=16 \\Rightarrow a=4$ (لأن $a>0$)"
        },
        {
          "id": "u5e1q3",
          "lesson": "u5-l1",
          "difficulty": "medium",
          "text": "يُمثّل الاقتران: $f'(x)=6x-e^{-x}$ ميل المماس لمنحنى الاقتران $f(x)$. إذا كان منحنى $f(x)$ يمرّ بالنقطة $(0,\\,4)$ ، فإنّ قاعدة الاقتران $f(x)$ هي:",
          "options": [
            "$f(x)=3x^{2}+e^{-x}+3$",
            "$f(x)=3x^{2}-e^{-x}+5$",
            "$f(x)=3x^{2}+e^{-x}+4$",
            "$f(x)=6x^{2}+e^{-x}+3$"
          ],
          "answer": 0,
          "solution": "$f(x)=\\displaystyle\\int(6x-e^{-x})dx=3x^2+e^{-x}+C$\n$f(0)=4 \\Rightarrow 0+1+C=4 \\Rightarrow C=3$"
        },
        {
          "id": "u5e1q4",
          "lesson": "u5-l2",
          "difficulty": "easy",
          "text": "ناتج: $\\displaystyle\\int x^{2}e^{x^{3}}\\,dx$ هو:",
          "options": [
            "$\\frac{1}{3}e^{x^{3}}+C$",
            "$3e^{x^{3}}+C$",
            "$e^{x^{3}}+C$",
            "$\\frac{x^{3}}{3}e^{x^{3}}+C$"
          ],
          "answer": 0,
          "solution": "بالتعويض $u=x^3 \\Rightarrow du=3x^2dx$: $\\displaystyle\\frac13\\int e^u\\,du=\\frac13e^{x^3}+C$"
        },
        {
          "id": "u5e1q5",
          "lesson": "u5-l2",
          "difficulty": "hard",
          "text": "ناتج: $\\displaystyle\\int x\\sqrt{x-1}\\,dx$ هو:",
          "options": [
            "$\\frac{2}{5}(x-1)^{\\frac{5}{2}}+\\frac{2}{3}(x-1)^{\\frac{3}{2}}+C$",
            "$\\frac{2}{5}(x-1)^{\\frac{5}{2}}-\\frac{2}{3}(x-1)^{\\frac{3}{2}}+C$",
            "$\\frac{x^{2}}{2}\\cdot\\frac{2}{3}(x-1)^{\\frac{3}{2}}+C$",
            "$\\frac{2}{3}x(x-1)^{\\frac{3}{2}}+C$"
          ],
          "answer": 0,
          "solution": "بالتعويض $u=x-1 \\Rightarrow x=u+1$ ، $dx=du$:\n$\\displaystyle\\int(u+1)\\sqrt u\\,du=\\int\\left(u^{\\frac32}+u^{\\frac12}\\right)du=\\frac25u^{\\frac52}+\\frac23u^{\\frac32}+C$\n$=\\frac25(x-1)^{\\frac52}+\\frac23(x-1)^{\\frac32}+C$"
        },
        {
          "id": "u5e1q6",
          "lesson": "u5-l3",
          "difficulty": "medium",
          "text": "ناتج: $\\displaystyle\\int \\frac{5x+4}{(x-1)(x+2)}\\,dx$ هو:",
          "options": [
            "$3\\ln|x-1|+2\\ln|x+2|+C$",
            "$2\\ln|x-1|+3\\ln|x+2|+C$",
            "$3\\ln|x-1|-2\\ln|x+2|+C$",
            "$5\\ln|(x-1)(x+2)|+C$"
          ],
          "answer": 0,
          "solution": "$\\dfrac{5x+4}{(x-1)(x+2)}=\\dfrac{A}{x-1}+\\dfrac{B}{x+2}$ ، عند $x=1$: $9=3A \\Rightarrow A=3$ ، عند $x=-2$: $-6=-3B \\Rightarrow B=2$\nإذن التكامل $=3\\ln|x-1|+2\\ln|x+2|+C$"
        },
        {
          "id": "u5e1q7",
          "lesson": "u5-l3",
          "difficulty": "hard",
          "text": "قيمة: $\\displaystyle\\int_{2}^{3}\\frac{x^{2}+1}{x^{2}-1}\\,dx$ هي:",
          "options": [
            "$1+\\ln\\frac{3}{2}$",
            "$1+\\ln\\frac{2}{3}$",
            "$\\ln\\frac{3}{2}$",
            "$1+\\ln 6$"
          ],
          "answer": 0,
          "solution": "الكسر غير فعلي: $\\dfrac{x^2+1}{x^2-1}=1+\\dfrac{2}{x^2-1}=1+\\dfrac{1}{x-1}-\\dfrac{1}{x+1}$\n$\\big[x+\\ln|x-1|-\\ln|x+1|\\big]_2^3=(3+\\ln2-\\ln4)-(2+0-\\ln3)=1+\\ln\\dfrac{2\\cdot3}{4}=1+\\ln\\dfrac32$"
        },
        {
          "id": "u5e1q8",
          "lesson": "u5-l4",
          "difficulty": "easy",
          "text": "ناتج: $\\displaystyle\\int xe^{3x}\\,dx$ هو:",
          "options": [
            "$\\frac{x}{3}e^{3x}-\\frac{1}{9}e^{3x}+C$",
            "$\\frac{x}{3}e^{3x}-\\frac{1}{3}e^{3x}+C$",
            "$3xe^{3x}-9e^{3x}+C$",
            "$\\frac{x^{2}}{6}e^{3x}+C$"
          ],
          "answer": 0,
          "solution": "بالأجزاء: $u=x$ ، $dv=e^{3x}dx \\Rightarrow v=\\frac13e^{3x}$\n$\\displaystyle\\frac{x}{3}e^{3x}-\\int\\frac13e^{3x}dx=\\frac{x}{3}e^{3x}-\\frac19e^{3x}+C$"
        },
        {
          "id": "u5e1q9",
          "lesson": "u5-l4",
          "difficulty": "medium",
          "text": "ناتج: $\\displaystyle\\int x\\sec^{2}x\\,dx$ هو:",
          "options": [
            "$x\\tan x+\\ln|\\cos x|+C$",
            "$x\\tan x-\\ln|\\cos x|+C$",
            "$x\\tan x+\\ln|\\sin x|+C$",
            "$\\frac{x^{2}}{2}\\tan x+C$"
          ],
          "answer": 0,
          "solution": "بالأجزاء: $u=x$ ، $dv=\\sec^2x\\,dx \\Rightarrow v=\\tan x$\n$\\displaystyle x\\tan x-\\int\\tan x\\,dx=x\\tan x-(-\\ln|\\cos x|)+C=x\\tan x+\\ln|\\cos x|+C$"
        },
        {
          "id": "u5e1q10",
          "lesson": "u5-l5",
          "difficulty": "medium",
          "text": "اعتمادًا على الشكل الآتي الذي يُبيّن منحنى الاقتران: $f(x)=x^{2}-4x$ ، فإنّ مساحة المنطقة المُظلَّلة (بالوحدات المربعة) هي:",
          "options": [
            "$\\frac{32}{3}$",
            "$-\\frac{32}{3}$",
            "$\\frac{16}{3}$",
            "$\\frac{64}{3}$"
          ],
          "answer": 0,
          "solution": "المنطقة تحت محور $x$ بين نقطتي التقاطع $x=0$ و $x=4$ ، فالمساحة $=\\left|\\displaystyle\\int_0^4(x^2-4x)dx\\right|$\n$=\\left|\\left[\\frac{x^3}{3}-2x^2\\right]_0^4\\right|=\\left|\\frac{64}{3}-32\\right|=\\frac{32}{3}$ (المساحة لا تكون سالبة)",
          "figure": "fig/u5e1q10.svg"
        },
        {
          "id": "u5e1q11",
          "lesson": "u5-l5",
          "difficulty": "hard",
          "text": "حجم المُجسَّم الناتج من دوران المنطقة المحصورة بين منحنى الاقتران: $f(x)=\\sqrt{\\cos x}$ والمحور $x$ في الفترة $\\left[0,\\,\\frac{\\pi}{2}\\right]$ حول المحور $x$ (بالوحدات المكعبة) هو:",
          "options": [
            "$\\pi$",
            "$2\\pi$",
            "$\\frac{\\pi}{2}$",
            "$\\pi^{2}$"
          ],
          "answer": 0,
          "solution": "$V=\\pi\\displaystyle\\int_0^{\\pi/2}\\left(\\sqrt{\\cos x}\\right)^2dx=\\pi\\int_0^{\\pi/2}\\cos x\\,dx=\\pi\\big[\\sin x\\big]_0^{\\pi/2}=\\pi(1-0)=\\pi$"
        },
        {
          "id": "u5e1q12",
          "lesson": "u5-l6",
          "difficulty": "medium",
          "text": "الحلّ الخاص للمعادلة التفاضلية: $\\dfrac{dy}{dx}=xy^{2}$ الذي يُحقّق الشرط الأوّلي $y(0)=1$ هو:",
          "options": [
            "$y=\\frac{2}{2-x^{2}}$",
            "$y=\\frac{2}{2+x^{2}}$",
            "$y=\\frac{1}{1-x^{2}}$",
            "$y=1-\\frac{x^{2}}{2}$"
          ],
          "answer": 0,
          "solution": "بفصل المتغيرات: $\\dfrac{dy}{y^2}=x\\,dx \\Rightarrow -\\dfrac1y=\\dfrac{x^2}{2}+C$\n$y(0)=1 \\Rightarrow -1=C$ ، إذن $-\\dfrac1y=\\dfrac{x^2}{2}-1=\\dfrac{x^2-2}{2} \\Rightarrow y=\\dfrac{2}{2-x^2}$"
        }
      ]
    },
    {
      "id": "u5-e2",
      "title": "الاختبار الثاني",
      "questions": [
        {
          "id": "u5e2q1",
          "lesson": "u5-l1",
          "difficulty": "easy",
          "text": "ناتج: $\\displaystyle\\int\\left(\\cot^{2}x+3\\right)dx$ هو:",
          "options": [
            "$-\\cot x+2x+C$",
            "$-\\cot x+3x+C$",
            "$\\cot x+2x+C$",
            "$-\\csc x+2x+C$"
          ],
          "answer": 0,
          "solution": "$\\cot^2x=\\csc^2x-1$ ، إذن $\\displaystyle\\int(\\csc^2x-1+3)dx=\\int(\\csc^2x+2)dx=-\\cot x+2x+C$"
        },
        {
          "id": "u5e2q2",
          "lesson": "u5-l1",
          "difficulty": "medium",
          "text": "ناتج: $\\displaystyle\\int 3^{2x+1}\\,dx$ هو:",
          "options": [
            "$\\frac{3^{2x+1}}{2\\ln 3}+C$",
            "$\\frac{3^{2x+1}}{\\ln 3}+C$",
            "$2\\cdot3^{2x+1}\\ln 3+C$",
            "$\\frac{3^{2x+1}}{(\\ln 3)^{2}}+C$"
          ],
          "answer": 0,
          "solution": "$\\displaystyle\\int a^{kx+b}dx=\\frac{a^{kx+b}}{k\\ln a}+C$ ، إذن الناتج $\\dfrac{3^{2x+1}}{2\\ln3}+C$"
        },
        {
          "id": "u5e2q3",
          "lesson": "u5-l1",
          "difficulty": "hard",
          "text": "إذا تحرّك جُسيم في مسار مستقيم، وكانت سرعته تُعطى بالاقتران: $v(t)=t^{2}-4t+3$ ، حيث $v$ بالمتر لكل ثانية، و $t$ الزمن بالثواني، فإنّ المسافة الكلية بالأمتار التي قطعها الجُسيم في الفترة $[0,\\,3]$ هي:",
          "options": [
            "$\\frac{8}{3}$",
            "$0$",
            "$\\frac{4}{3}$",
            "$3$"
          ],
          "answer": 0,
          "solution": "$v(t)=(t-1)(t-3)$ موجبة في $(0,1)$ وسالبة في $(1,3)$\n$\\displaystyle\\int_0^1v\\,dt=\\left[\\frac{t^3}{3}-2t^2+3t\\right]_0^1=\\frac43$ ، $\\displaystyle\\int_1^3v\\,dt=0-\\frac43=-\\frac43$\nالمسافة $=\\frac43+\\left|-\\frac43\\right|=\\frac83\\ \\text{m}$ (لاحظ أن الإزاحة $=0$)"
        },
        {
          "id": "u5e2q4",
          "lesson": "u5-l2",
          "difficulty": "medium",
          "text": "ناتج: $\\displaystyle\\int \\frac{\\cos x}{(1+\\sin x)^{2}}\\,dx$ هو:",
          "options": [
            "$-\\frac{1}{1+\\sin x}+C$",
            "$\\frac{1}{1+\\sin x}+C$",
            "$\\ln|1+\\sin x|+C$",
            "$-\\frac{2}{(1+\\sin x)^{3}}+C$"
          ],
          "answer": 0,
          "solution": "بالتعويض $u=1+\\sin x \\Rightarrow du=\\cos x\\,dx$: $\\displaystyle\\int u^{-2}du=-u^{-1}+C=-\\frac{1}{1+\\sin x}+C$"
        },
        {
          "id": "u5e2q5",
          "lesson": "u5-l2",
          "difficulty": "medium",
          "text": "قيمة: $\\displaystyle\\int_{0}^{\\pi/3}\\frac{\\sin x}{\\cos^{2}x}\\,dx$ هي:",
          "options": [
            "$1$",
            "$2$",
            "$-1$",
            "$\\frac{1}{2}$"
          ],
          "answer": 0,
          "solution": "بالتعويض $u=\\cos x \\Rightarrow du=-\\sin x\\,dx$ ، أو بملاحظة أن $\\dfrac{\\sin x}{\\cos^2x}=\\sec x\\tan x$:\n$\\big[\\sec x\\big]_0^{\\pi/3}=\\sec\\frac{\\pi}{3}-\\sec0=2-1=1$"
        },
        {
          "id": "u5e2q6",
          "lesson": "u5-l3",
          "difficulty": "easy",
          "text": "ناتج: $\\displaystyle\\int \\frac{3x+1}{x^{2}-1}\\,dx$ هو:",
          "options": [
            "$2\\ln|x-1|+\\ln|x+1|+C$",
            "$\\ln|x-1|+2\\ln|x+1|+C$",
            "$2\\ln|x-1|-\\ln|x+1|+C$",
            "$\\frac{3}{2}\\ln|x^{2}-1|+C$"
          ],
          "answer": 0,
          "solution": "$\\dfrac{3x+1}{(x-1)(x+1)}=\\dfrac{A}{x-1}+\\dfrac{B}{x+1}$ ، عند $x=1$: $4=2A \\Rightarrow A=2$ ، عند $x=-1$: $-2=-2B \\Rightarrow B=1$"
        },
        {
          "id": "u5e2q7",
          "lesson": "u5-l3",
          "difficulty": "hard",
          "text": "ناتج: $\\displaystyle\\int \\frac{2x^{2}+3}{x^{3}+3x}\\,dx$ هو:",
          "options": [
            "$\\ln|x|+\\frac{1}{2}\\ln(x^{2}+3)+C$",
            "$\\ln|x|+\\ln(x^{2}+3)+C$",
            "$\\ln|x|-\\frac{1}{2}\\ln(x^{2}+3)+C$",
            "$2\\ln|x|+\\frac{1}{2}\\ln(x^{2}+3)+C$"
          ],
          "answer": 0,
          "solution": "$x^3+3x=x(x^2+3)$ ، و $2x^2+3=A(x^2+3)+(Bx+C)x$: عند $x=0$: $A=1$ ، ثم $B=1$ ، $C=0$\n$\\displaystyle\\int\\left(\\frac1x+\\frac{x}{x^2+3}\\right)dx=\\ln|x|+\\frac12\\ln(x^2+3)+C$"
        },
        {
          "id": "u5e2q8",
          "lesson": "u5-l4",
          "difficulty": "easy",
          "text": "ناتج: $\\displaystyle\\int \\ln(2x)\\,dx$ هو:",
          "options": [
            "$x\\ln(2x)-x+C$",
            "$x\\ln(2x)-2x+C$",
            "$\\frac{1}{2x}+C$",
            "$2x\\ln(2x)-x+C$"
          ],
          "answer": 0,
          "solution": "بالأجزاء: $u=\\ln(2x) \\Rightarrow du=\\frac1xdx$ ، $dv=dx \\Rightarrow v=x$\n$\\displaystyle x\\ln(2x)-\\int x\\cdot\\frac1x\\,dx=x\\ln(2x)-x+C$"
        },
        {
          "id": "u5e2q9",
          "lesson": "u5-l4",
          "difficulty": "hard",
          "text": "ناتج: $\\displaystyle\\int x^{2}\\cos x\\,dx$ هو:",
          "options": [
            "$x^{2}\\sin x+2x\\cos x-2\\sin x+C$",
            "$x^{2}\\sin x-2x\\cos x+2\\sin x+C$",
            "$x^{2}\\sin x+2x\\cos x+2\\sin x+C$",
            "$-x^{2}\\sin x+2x\\cos x-2\\sin x+C$"
          ],
          "answer": 0,
          "solution": "بالأجزاء مرتين (أو بالجدول): $u=x^2$ ، $dv=\\cos x\\,dx$\n$\\displaystyle\\int x^2\\cos x\\,dx=x^2\\sin x-\\int2x\\sin x\\,dx=x^2\\sin x-\\left(-2x\\cos x+2\\sin x\\right)$\n$=x^2\\sin x+2x\\cos x-2\\sin x+C$"
        },
        {
          "id": "u5e2q10",
          "lesson": "u5-l5",
          "difficulty": "medium",
          "text": "مساحة المنطقة المحصورة بين منحنيي الاقترانين: $f(x)=2x$ و $g(x)=x^{2}-3$ (بالوحدات المربعة) هي:",
          "options": [
            "$\\frac{32}{3}$",
            "$\\frac{16}{3}$",
            "$9$",
            "$\\frac{64}{3}$"
          ],
          "answer": 0,
          "solution": "نقاط التقاطع: $x^2-3=2x \\Rightarrow x^2-2x-3=0 \\Rightarrow x=-1,\\ x=3$ ، وفي $(-1,3)$ يكون $2x\\ge x^2-3$\n$\\displaystyle A=\\int_{-1}^{3}(2x-x^2+3)dx=\\left[x^2-\\frac{x^3}{3}+3x\\right]_{-1}^{3}=9-\\left(-\\frac53\\right)=\\frac{32}{3}$"
        },
        {
          "id": "u5e2q11",
          "lesson": "u5-l5",
          "difficulty": "hard",
          "text": "حجم المُجسَّم الناتج من دوران المنطقة المحصورة بين منحنيي الاقترانين: $f(x)=\\sqrt{x}$ و $g(x)=x$ حول المحور $x$ (بالوحدات المكعبة) هو:",
          "options": [
            "$\\frac{\\pi}{6}$",
            "$\\frac{\\pi}{3}$",
            "$\\frac{\\pi}{2}$",
            "$\\frac{\\pi}{12}$"
          ],
          "answer": 0,
          "solution": "نقاط التقاطع: $\\sqrt x=x \\Rightarrow x=0,\\ x=1$ ، وفي $(0,1)$ يكون $\\sqrt x>x$ (المنحنى الخارجي $\\sqrt x$)\n$\\displaystyle V=\\pi\\int_0^1\\left((\\sqrt x)^2-x^2\\right)dx=\\pi\\int_0^1(x-x^2)dx=\\pi\\left(\\frac12-\\frac13\\right)=\\frac{\\pi}{6}$"
        },
        {
          "id": "u5e2q12",
          "lesson": "u5-l6",
          "difficulty": "medium",
          "text": "يتغيّر عدد البكتيريا $P$ في مزرعة وفق المعادلة التفاضلية $\\dfrac{dP}{dt}=kP$ ، حيث $t$ الزمن بالساعات. إذا كان العدد الابتدائي $200$ ، وأصبح بعد $3$ ساعات $1600$ ، فإنّ عدد البكتيريا بعد $5$ ساعات هو:",
          "options": [
            "$6400$",
            "$3200$",
            "$4000$",
            "$12800$"
          ],
          "answer": 0,
          "solution": "الحل العام: $P=P_0e^{kt}=200e^{kt}$ ، و $P(3)=1600 \\Rightarrow e^{3k}=8 \\Rightarrow e^{k}=2$\nإذن $P(t)=200\\cdot2^t$ ، و $P(5)=200(32)=6400$"
        }
      ]
    },
    {
      "id": "u5-e3",
      "title": "الاختبار الثالث",
      "questions": [
        {
          "id": "u5e3q1",
          "lesson": "u5-l1",
          "difficulty": "easy",
          "text": "قيمة: $\\displaystyle\\int_{1}^{e}\\frac{x+1}{x}\\,dx$ هي:",
          "options": [
            "$e$",
            "$e-1$",
            "$e+1$",
            "$1$"
          ],
          "answer": 0,
          "solution": "$\\displaystyle\\int_1^e\\left(1+\\frac1x\\right)dx=\\big[x+\\ln x\\big]_1^e=(e+1)-(1+0)=e$"
        },
        {
          "id": "u5e3q2",
          "lesson": "u5-l1",
          "difficulty": "medium",
          "text": "إذا كان: $\\displaystyle\\int_{0}^{\\pi/2}\\cos^{2}x\\,dx=a\\pi$ ، فإنّ قيمة الثابت $a$ هي:",
          "options": [
            "$\\frac{1}{4}$",
            "$\\frac{1}{2}$",
            "$-\\frac{1}{4}$",
            "$1$"
          ],
          "answer": 0,
          "solution": "$\\cos^2x=\\dfrac{1+\\cos2x}{2}$ ، إذن $\\displaystyle\\int_0^{\\pi/2}\\frac{1+\\cos2x}{2}dx=\\left[\\frac x2+\\frac{\\sin2x}{4}\\right]_0^{\\pi/2}=\\frac{\\pi}{4}$\n$a\\pi=\\dfrac{\\pi}{4} \\Rightarrow a=\\dfrac14$"
        },
        {
          "id": "u5e3q3",
          "lesson": "u5-l1",
          "difficulty": "hard",
          "text": "يتحرّك جسم في مسار مستقيم، وتُعطى سرعته بالاقتران: $v(t)=\\begin{cases}3t^{2}, & 0\\le t\\le2\\\\ 12, & t>2\\end{cases}$ ، حيث $t$ الزمن بالثواني، و $v$ سرعته بالمتر لكل ثانية. إذا انطلق الجسم من نقطة الأصل، فإنّ موقعه بعد $5$ ثوانٍ من بدء الحركة هو:",
          "options": [
            "$44\\ \\text{m}$",
            "$36\\ \\text{m}$",
            "$75\\ \\text{m}$",
            "$48\\ \\text{m}$"
          ],
          "answer": 0,
          "solution": "$s(5)=s(0)+\\displaystyle\\int_0^5v(t)dt=0+\\int_0^2 3t^2dt+\\int_2^5 12\\,dt$\n$=\\big[t^3\\big]_0^2+12(5-2)=8+36=44\\ \\text{m}$"
        },
        {
          "id": "u5e3q4",
          "lesson": "u5-l2",
          "difficulty": "easy",
          "text": "ناتج: $\\displaystyle\\int \\frac{e^{x}}{e^{x}+3}\\,dx$ هو:",
          "options": [
            "$\\ln(e^{x}+3)+C$",
            "$e^{x}\\ln(e^{x}+3)+C$",
            "$\\frac{1}{e^{x}+3}+C$",
            "$x+\\ln 3+C$"
          ],
          "answer": 0,
          "solution": "البسط مشتقة المقام: $\\displaystyle\\int\\frac{f'(x)}{f(x)}dx=\\ln|f(x)|+C=\\ln(e^x+3)+C$ (لأن $e^x+3>0$)"
        },
        {
          "id": "u5e3q5",
          "lesson": "u5-l2",
          "difficulty": "hard",
          "text": "ناتج: $\\displaystyle\\int \\frac{\\sin 2x}{1+\\cos^{2}x}\\,dx$ هو:",
          "options": [
            "$-\\ln(1+\\cos^{2}x)+C$",
            "$\\ln(1+\\cos^{2}x)+C$",
            "$-2\\ln(1+\\cos^{2}x)+C$",
            "$-\\frac{1}{2}\\ln(1+\\cos^{2}x)+C$"
          ],
          "answer": 0,
          "solution": "بالتعويض $u=1+\\cos^2x \\Rightarrow du=-2\\sin x\\cos x\\,dx=-\\sin2x\\,dx$\n$\\displaystyle\\int\\frac{-du}{u}=-\\ln|u|+C=-\\ln(1+\\cos^2x)+C$"
        },
        {
          "id": "u5e3q6",
          "lesson": "u5-l3",
          "difficulty": "medium",
          "text": "قيمة: $\\displaystyle\\int_{3}^{4}\\frac{2x-1}{(x-1)(x-2)}\\,dx$ هي:",
          "options": [
            "$\\ln\\frac{16}{3}$",
            "$\\ln\\frac{3}{16}$",
            "$\\ln 16$",
            "$4\\ln 2+\\ln 3$"
          ],
          "answer": 0,
          "solution": "$\\dfrac{2x-1}{(x-1)(x-2)}=\\dfrac{-1}{x-1}+\\dfrac{3}{x-2}$ (عند $x=1$: $A=-1$ ، عند $x=2$: $B=3$)\n$\\big[-\\ln|x-1|+3\\ln|x-2|\\big]_3^4=(-\\ln3+3\\ln2)-(-\\ln2+0)=4\\ln2-\\ln3=\\ln\\dfrac{16}{3}$"
        },
        {
          "id": "u5e3q7",
          "lesson": "u5-l3",
          "difficulty": "hard",
          "text": "ناتج: $\\displaystyle\\int \\frac{x^{3}}{x^{2}-1}\\,dx$ هو:",
          "options": [
            "$\\frac{x^{2}}{2}+\\frac{1}{2}\\ln|x^{2}-1|+C$",
            "$\\frac{x^{2}}{2}+\\ln|x^{2}-1|+C$",
            "$\\frac{x^{2}}{2}-\\frac{1}{2}\\ln|x^{2}-1|+C$",
            "$\\frac{x^{4}}{4}\\ln|x^{2}-1|+C$"
          ],
          "answer": 0,
          "solution": "الكسر غير فعلي: $x^3=x(x^2-1)+x$ ، إذن $\\dfrac{x^3}{x^2-1}=x+\\dfrac{x}{x^2-1}=x+\\dfrac{1/2}{x-1}+\\dfrac{1/2}{x+1}$\n$\\displaystyle\\int=\\frac{x^2}{2}+\\frac12\\ln|x-1|+\\frac12\\ln|x+1|+C=\\frac{x^2}{2}+\\frac12\\ln|x^2-1|+C$"
        },
        {
          "id": "u5e3q8",
          "lesson": "u5-l4",
          "difficulty": "medium",
          "text": "ناتج: $\\displaystyle\\int x\\cos 2x\\,dx$ هو:",
          "options": [
            "$\\frac{x}{2}\\sin 2x+\\frac{1}{4}\\cos 2x+C$",
            "$\\frac{x}{2}\\sin 2x-\\frac{1}{4}\\cos 2x+C$",
            "$2x\\sin 2x+4\\cos 2x+C$",
            "$\\frac{x^{2}}{2}\\sin 2x+C$"
          ],
          "answer": 0,
          "solution": "بالأجزاء: $u=x$ ، $dv=\\cos2x\\,dx \\Rightarrow v=\\frac12\\sin2x$\n$\\displaystyle\\frac x2\\sin2x-\\int\\frac12\\sin2x\\,dx=\\frac x2\\sin2x+\\frac14\\cos2x+C$"
        },
        {
          "id": "u5e3q9",
          "lesson": "u5-l4",
          "difficulty": "hard",
          "text": "قيمة: $\\displaystyle\\int_{1}^{e}x\\ln x\\,dx$ هي:",
          "options": [
            "$\\frac{e^{2}+1}{4}$",
            "$\\frac{e^{2}-1}{4}$",
            "$\\frac{e^{2}}{4}$",
            "$\\frac{e^{2}+1}{2}$"
          ],
          "answer": 0,
          "solution": "بالأجزاء: $u=\\ln x$ ، $dv=x\\,dx$: $\\displaystyle\\int x\\ln x\\,dx=\\frac{x^2}{2}\\ln x-\\frac{x^2}{4}$\n$\\left[\\frac{x^2}{2}\\ln x-\\frac{x^2}{4}\\right]_1^e=\\left(\\frac{e^2}{2}-\\frac{e^2}{4}\\right)-\\left(0-\\frac14\\right)=\\dfrac{e^2+1}{4}$"
        },
        {
          "id": "u5e3q10",
          "lesson": "u5-l5",
          "difficulty": "medium",
          "text": "يُبيّن الشكل الآتي منحنى السرعة–الزمن لجسم يتحرّك على المحور $x$ في الفترة الزمنية $[0,\\,8]$. المسافة الكلية التي قطعها الجسم في هذه الفترة هي:",
          "options": [
            "$20\\ \\text{m}$",
            "$8\\ \\text{m}$",
            "$16\\ \\text{m}$",
            "$12\\ \\text{m}$"
          ],
          "answer": 0,
          "solution": "المسافة الكلية = مجموع المساحات (كلها موجبة) بين المنحنى ومحور $t$:\n$[0,2]$: مثلث $=\\frac12(2)(4)=4$ ، $[2,4]$: مستطيل $=8$ ، $[4,5]$: مثلث $=2$ ، $[5,6]$: مثلث تحت المحور $=2$ ، $[6,8]$: مثلث تحت المحور $=4$\nالمسافة $=4+8+2+2+4=20\\ \\text{m}$ (أما الإزاحة فهي $4+8+2-2-4=8\\ \\text{m}$)",
          "figure": "fig/u5e3q10.svg"
        },
        {
          "id": "u5e3q11",
          "lesson": "u5-l5",
          "difficulty": "medium",
          "text": "إذا كانت مساحة المنطقة المحصورة بين منحنى الاقتران: $f(x)=\\frac{6}{x}$ ، والمحور $x$ ، والمستقيمين: $x=1,\\ x=a$ تساوي $12$ وحدة مربعة، حيث $a>1$ ، فإنّ قيمة الثابت $a$ هي:",
          "options": [
            "$e^{2}$",
            "$e$",
            "$e^{3}$",
            "$e^{6}$"
          ],
          "answer": 0,
          "solution": "$\\displaystyle\\int_1^a\\frac6x\\,dx=\\big[6\\ln x\\big]_1^a=6\\ln a=12 \\Rightarrow \\ln a=2 \\Rightarrow a=e^2$"
        },
        {
          "id": "u5e3q12",
          "lesson": "u5-l6",
          "difficulty": "hard",
          "text": "الحلّ الخاص للمعادلة التفاضلية: $\\dfrac{dy}{dx}=e^{x-y}$ الذي يُحقّق الشرط الأوّلي $y(0)=\\ln 2$ هو:",
          "options": [
            "$y=\\ln(e^{x}+1)$",
            "$y=\\ln(e^{x}+2)$",
            "$y=x+\\ln 2$",
            "$y=\\ln(2e^{x})-x$"
          ],
          "answer": 0,
          "solution": "$\\dfrac{dy}{dx}=\\dfrac{e^x}{e^y} \\Rightarrow e^y\\,dy=e^x\\,dx \\Rightarrow e^y=e^x+C$\n$y(0)=\\ln2 \\Rightarrow 2=1+C \\Rightarrow C=1$ ، إذن $e^y=e^x+1 \\Rightarrow y=\\ln(e^x+1)$"
        }
      ]
    },
    {
      "id": "u5-e4",
      "title": "الاختبار الرابع",
      "questions": [
        {
          "id": "u5e4q1",
          "lesson": "u5-l1",
          "difficulty": "easy",
          "text": "ناتج: $\\displaystyle\\int\\left(\\sqrt{x}+\\frac{1}{\\sqrt{x}}\\right)dx$ هو:",
          "options": [
            "$\\frac{2}{3}x^{\\frac{3}{2}}+2\\sqrt{x}+C$",
            "$\\frac{3}{2}x^{\\frac{3}{2}}+2\\sqrt{x}+C$",
            "$\\frac{2}{3}x^{\\frac{3}{2}}+\\frac{1}{2}\\sqrt{x}+C$",
            "$\\frac{2}{3}x^{\\frac{3}{2}}-2\\sqrt{x}+C$"
          ],
          "answer": 0,
          "solution": "$\\displaystyle\\int\\left(x^{\\frac12}+x^{-\\frac12}\\right)dx=\\frac{x^{\\frac32}}{\\frac32}+\\frac{x^{\\frac12}}{\\frac12}+C=\\frac23x^{\\frac32}+2\\sqrt x+C$"
        },
        {
          "id": "u5e4q2",
          "lesson": "u5-l1",
          "difficulty": "medium",
          "text": "ناتج: $\\displaystyle\\int (\\sin x+\\cos x)^{2}\\,dx$ هو:",
          "options": [
            "$x-\\frac{1}{2}\\cos 2x+C$",
            "$x+\\frac{1}{2}\\cos 2x+C$",
            "$x-\\cos 2x+C$",
            "$\\frac{(\\sin x+\\cos x)^{3}}{3}+C$"
          ],
          "answer": 0,
          "solution": "$(\\sin x+\\cos x)^2=\\sin^2x+2\\sin x\\cos x+\\cos^2x=1+\\sin2x$\n$\\displaystyle\\int(1+\\sin2x)dx=x-\\frac12\\cos2x+C$"
        },
        {
          "id": "u5e4q3",
          "lesson": "u5-l1",
          "difficulty": "medium",
          "text": "ناتج: $\\displaystyle\\int \\frac{e^{2x}-1}{e^{x}}\\,dx$ هو:",
          "options": [
            "$e^{x}+e^{-x}+C$",
            "$e^{x}-e^{-x}+C$",
            "$e^{x}-x+C$",
            "$e^{2x}-x+C$"
          ],
          "answer": 0,
          "solution": "نقسم كل حد على $e^x$: $\\dfrac{e^{2x}-1}{e^x}=e^x-e^{-x}$\n$\\displaystyle\\int(e^x-e^{-x})dx=e^x+e^{-x}+C$"
        },
        {
          "id": "u5e4q4",
          "lesson": "u5-l2",
          "difficulty": "easy",
          "text": "ناتج: $\\displaystyle\\int \\frac{(\\ln x)^{3}}{x}\\,dx$ هو:",
          "options": [
            "$\\frac{(\\ln x)^{4}}{4}+C$",
            "$(\\ln x)^{4}+C$",
            "$\\frac{3(\\ln x)^{2}}{x}+C$",
            "$\\frac{(\\ln x)^{4}}{4x}+C$"
          ],
          "answer": 0,
          "solution": "بالتعويض $u=\\ln x \\Rightarrow du=\\frac1xdx$: $\\displaystyle\\int u^3du=\\frac{u^4}{4}+C=\\frac{(\\ln x)^4}{4}+C$"
        },
        {
          "id": "u5e4q5",
          "lesson": "u5-l2",
          "difficulty": "hard",
          "text": "ناتج: $\\displaystyle\\int x^{3}\\sqrt{x^{2}+1}\\,dx$ هو:",
          "options": [
            "$\\frac{1}{5}(x^{2}+1)^{\\frac{5}{2}}-\\frac{1}{3}(x^{2}+1)^{\\frac{3}{2}}+C$",
            "$\\frac{1}{5}(x^{2}+1)^{\\frac{5}{2}}+\\frac{1}{3}(x^{2}+1)^{\\frac{3}{2}}+C$",
            "$\\frac{2}{5}(x^{2}+1)^{\\frac{5}{2}}-\\frac{2}{3}(x^{2}+1)^{\\frac{3}{2}}+C$",
            "$\\frac{x^{4}}{4}\\cdot\\frac{2}{3}(x^{2}+1)^{\\frac{3}{2}}+C$"
          ],
          "answer": 0,
          "solution": "بالتعويض $u=x^2+1 \\Rightarrow du=2x\\,dx$ ، و $x^2=u-1$:\n$\\displaystyle\\int x^2\\sqrt{x^2+1}\\cdot x\\,dx=\\frac12\\int(u-1)\\sqrt u\\,du=\\frac12\\left(\\frac25u^{\\frac52}-\\frac23u^{\\frac32}\\right)+C$\n$=\\frac15(x^2+1)^{\\frac52}-\\frac13(x^2+1)^{\\frac32}+C$"
        },
        {
          "id": "u5e4q6",
          "lesson": "u5-l3",
          "difficulty": "medium",
          "text": "ناتج: $\\displaystyle\\int \\frac{4}{x^{2}-4x}\\,dx$ هو:",
          "options": [
            "$\\ln|x-4|-\\ln|x|+C$",
            "$\\ln|x|-\\ln|x-4|+C$",
            "$4\\ln|x-4|-4\\ln|x|+C$",
            "$\\ln|x^{2}-4x|+C$"
          ],
          "answer": 0,
          "solution": "$\\dfrac{4}{x(x-4)}=\\dfrac{A}{x}+\\dfrac{B}{x-4}$ ، عند $x=0$: $4=-4A \\Rightarrow A=-1$ ، عند $x=4$: $4=4B \\Rightarrow B=1$\nالتكامل $=-\\ln|x|+\\ln|x-4|+C$"
        },
        {
          "id": "u5e4q7",
          "lesson": "u5-l3",
          "difficulty": "hard",
          "text": "قيمة: $\\displaystyle\\int_{0}^{1}\\frac{x+3}{x^{2}+3x+2}\\,dx$ هي:",
          "options": [
            "$\\ln\\frac{8}{3}$",
            "$\\ln\\frac{3}{8}$",
            "$\\ln 4$",
            "$\\ln\\frac{4}{3}$"
          ],
          "answer": 0,
          "solution": "$x^2+3x+2=(x+1)(x+2)$ ، و $\\dfrac{x+3}{(x+1)(x+2)}=\\dfrac{2}{x+1}-\\dfrac{1}{x+2}$\n$\\big[2\\ln|x+1|-\\ln|x+2|\\big]_0^1=(2\\ln2-\\ln3)-(0-\\ln2)=3\\ln2-\\ln3=\\ln\\dfrac83$"
        },
        {
          "id": "u5e4q8",
          "lesson": "u5-l4",
          "difficulty": "medium",
          "text": "ناتج: $\\displaystyle\\int x^{2}e^{x}\\,dx$ هو:",
          "options": [
            "$e^{x}(x^{2}-2x+2)+C$",
            "$e^{x}(x^{2}+2x+2)+C$",
            "$e^{x}(x^{2}-2x-2)+C$",
            "$\\frac{x^{3}}{3}e^{x}+C$"
          ],
          "answer": 0,
          "solution": "بالأجزاء مرتين: $\\displaystyle\\int x^2e^xdx=x^2e^x-\\int2xe^xdx=x^2e^x-(2xe^x-2e^x)$\n$=e^x(x^2-2x+2)+C$"
        },
        {
          "id": "u5e4q9",
          "lesson": "u5-l4",
          "difficulty": "hard",
          "text": "ناتج: $\\displaystyle\\int e^{2x}\\cos x\\,dx$ هو:",
          "options": [
            "$\\frac{e^{2x}}{5}(2\\cos x+\\sin x)+C$",
            "$\\frac{e^{2x}}{5}(2\\cos x-\\sin x)+C$",
            "$\\frac{e^{2x}}{3}(2\\cos x+\\sin x)+C$",
            "$\\frac{e^{2x}}{5}(\\cos x+2\\sin x)+C$"
          ],
          "answer": 0,
          "solution": "بالأجزاء مرتين (تكامل دوري): نفرض $I=\\displaystyle\\int e^{2x}\\cos x\\,dx$\n$I=e^{2x}\\sin x-\\displaystyle\\int2e^{2x}\\sin x\\,dx=e^{2x}\\sin x-2\\left(-e^{2x}\\cos x+\\int2e^{2x}\\cos x\\,dx\\right)$\n$I=e^{2x}\\sin x+2e^{2x}\\cos x-4I \\Rightarrow 5I=e^{2x}(2\\cos x+\\sin x)$"
        },
        {
          "id": "u5e4q10",
          "lesson": "u5-l5",
          "difficulty": "medium",
          "text": "اعتمادًا على الشكل الآتي الذي يُبيّن منحنيي الاقترانين: $f(x)=6-x^{2}$ و $g(x)=x+4$ ، فإنّ مساحة المنطقة المُظلَّلة (بالوحدات المربعة) هي:",
          "options": [
            "$\\frac{9}{2}$",
            "$9$",
            "$\\frac{7}{6}$",
            "$\\frac{10}{3}$"
          ],
          "answer": 0,
          "solution": "نقاط التقاطع: $6-x^2=x+4 \\Rightarrow x^2+x-2=0 \\Rightarrow x=-2,\\ x=1$\n$\\displaystyle A=\\int_{-2}^{1}\\big((6-x^2)-(x+4)\\big)dx=\\int_{-2}^{1}(2-x-x^2)dx=\\left[2x-\\frac{x^2}{2}-\\frac{x^3}{3}\\right]_{-2}^{1}=\\frac76+\\frac{10}{3}=\\frac92$",
          "figure": "fig/u5e4q10.svg"
        },
        {
          "id": "u5e4q11",
          "lesson": "u5-l5",
          "difficulty": "hard",
          "text": "حجم المُجسَّم الناتج من دوران المنطقة المحصورة بين منحنيي الاقترانين: $f(x)=5-x^{2}$ و $g(x)=x+3$ حول المحور $x$ (بالوحدات المكعبة) هو:",
          "options": [
            "$\\frac{153\\pi}{5}$",
            "$\\frac{9\\pi}{2}$",
            "$\\frac{81\\pi}{4}$",
            "$\\frac{168\\pi}{5}$"
          ],
          "answer": 0,
          "solution": "نقاط التقاطع: $5-x^2=x+3 \\Rightarrow x=-2,\\ x=1$ ، وفي الفترة يكون $5-x^2\\ge x+3\\ge0$ (طريقة الحلقات)\n$\\displaystyle V=\\pi\\int_{-2}^{1}\\left((5-x^2)^2-(x+3)^2\\right)dx=\\pi\\int_{-2}^{1}(x^4-11x^2-6x+16)dx$\n$=\\pi\\left[\\frac{x^5}{5}-\\frac{11x^3}{3}-3x^2+16x\\right]_{-2}^{1}=\\pi\\left(\\frac{143}{15}+\\frac{316}{15}\\right)=\\frac{153\\pi}{5}$",
          "figure": "fig/u5e4q11.svg"
        },
        {
          "id": "u5e4q12",
          "lesson": "u5-l6",
          "difficulty": "medium",
          "text": "الحلّ الخاص للمعادلة التفاضلية: $\\dfrac{dy}{dx}=\\frac{2x+1}{2y}$ ، حيث $y>0$ ، الذي يُحقّق الشرط الأوّلي $y(0)=3$ هو:",
          "options": [
            "$y^{2}=x^{2}+x+9$",
            "$y^{2}=x^{2}+x+3$",
            "$y^{2}=2x^{2}+x+9$",
            "$y=x^{2}+x+3$"
          ],
          "answer": 0,
          "solution": "بفصل المتغيرات: $2y\\,dy=(2x+1)dx \\Rightarrow y^2=x^2+x+C$\n$y(0)=3 \\Rightarrow 9=C$ ، إذن $y^2=x^2+x+9$"
        }
      ]
    }
  ]
};

export default unit;
