// Generated by question-bank/u6.py (verified). Do not edit by hand.
import type { Unit } from '../types';

const unit: Unit = {
  "id": "u6",
  "number": 6,
  "semester": 2,
  "title": "المتجهات",
  "description": "النقاط والمتجهات في الفضاء: المقدار ومتجه الوحدة والتوازي ونقطة المنتصف ومسائل النسبة، معادلة المستقيم في الفضاء والعلاقة بين مستقيمين ونقطة التقاطع، والضرب القياسي والزاوية بين متجهين.",
  "lessons": [
    {
      "id": "u6-l1",
      "title": "المتجهات في الفضاء"
    },
    {
      "id": "u6-l2",
      "title": "المستقيمات في الفضاء"
    },
    {
      "id": "u6-l3",
      "title": "الضرب القياسي"
    }
  ],
  "exams": [
    {
      "id": "u6-e1",
      "title": "الاختبار الأول",
      "questions": [
        {
          "id": "u6e1q1",
          "lesson": "u6-l1",
          "difficulty": "easy",
          "text": "إذا كانت: $A(3,\\,-2,\\,2)$ ، $B(-3,\\,1,\\,4)$ نقطتين في الفضاء، فإنّ مقدار المتجه $\\overrightarrow{AB}$ هو:",
          "options": [
            "$7$",
            "$49$",
            "$5$",
            "$\\sqrt{13}$"
          ],
          "answer": 0,
          "solution": "$\\overrightarrow{AB}=\\langle -3-3,\\,1+2,\\,4-2\\rangle=\\langle -6,\\,3,\\,2\\rangle$ ، و $|\\overrightarrow{AB}|=\\sqrt{36+9+4}=\\sqrt{49}=7$"
        },
        {
          "id": "u6e1q2",
          "lesson": "u6-l1",
          "difficulty": "medium",
          "text": "إذا كانت: $A(1,\\,2,\\,-3)$ ، $B(4,\\,-1,\\,2)$ ، وكانت $D$ نقطة في الفضاء بحيث $\\overrightarrow{AB}=\\overrightarrow{BD}$ ، فإنّ متجه الموقع للنقطة $D$ هو:",
          "options": [
            "$\\langle 7,\\,-4,\\,7\\rangle$",
            "$\\langle -7,\\,4,\\,-7\\rangle$",
            "$\\langle 3,\\,-3,\\,5\\rangle$",
            "$\\langle \\frac{5}{2},\\,\\frac{1}{2},\\,- \\frac{1}{2}\\rangle$"
          ],
          "answer": 0,
          "solution": "$\\overrightarrow{AB}=\\overrightarrow{BD} \\Rightarrow B-A=D-B \\Rightarrow D=2B-A$\n$D=\\langle 8-1,\\,-2-2,\\,4+3\\rangle=\\langle 7,\\,-4,\\,7\\rangle$ (أي أن $B$ منتصف $\\overline{AD}$)"
        },
        {
          "id": "u6e1q3",
          "lesson": "u6-l1",
          "difficulty": "medium",
          "text": "إذا كانت: $A(1,\\,2,\\,-3)$ ، $C(\\alpha,\\,3,\\,2)$ ، وكان: $|\\overrightarrow{AC}|=\\sqrt{30}$ ، حيث $\\alpha>0$ ، فإنّ قيمة الثابت $\\alpha$ هي:",
          "options": [
            "$3$",
            "$-1$",
            "$5$",
            "$1$"
          ],
          "answer": 0,
          "solution": "$\\overrightarrow{AC}=\\langle \\alpha-1,\\,1,\\,5\\rangle$ ، و $(\\alpha-1)^2+1+25=30 \\Rightarrow (\\alpha-1)^2=4$\n$\\alpha-1=\\pm2 \\Rightarrow \\alpha=3$ أو $\\alpha=-1$ ، وبما أن $\\alpha>0$ فإن $\\alpha=3$"
        },
        {
          "id": "u6e1q4",
          "lesson": "u6-l1",
          "difficulty": "easy",
          "text": "إذا كان: $\\vec{\\mathbf{v}}=\\langle 6,\\,-2,\\,3\\rangle$ ، فإنّ متجه الوحدة في اتجاه المتجه $\\vec{\\mathbf{v}}$ هو:",
          "options": [
            "$\\langle \\frac{6}{7},\\,- \\frac{2}{7},\\,\\frac{3}{7}\\rangle$",
            "$\\langle \\frac{6}{49},\\,- \\frac{2}{49},\\,\\frac{3}{49}\\rangle$",
            "$\\langle - \\frac{6}{7},\\,\\frac{2}{7},\\,- \\frac{3}{7}\\rangle$",
            "$\\langle \\frac{6}{11},\\,- \\frac{2}{11},\\,\\frac{3}{11}\\rangle$"
          ],
          "answer": 0,
          "solution": "$|\\vec{\\mathbf{v}}|=\\sqrt{36+4+9}=7$ ، ومتجه الوحدة $\\dfrac{\\vec{\\mathbf{v}}}{|\\vec{\\mathbf{v}}|}=\\left\\langle \\frac67,\\,-\\frac27,\\,\\frac37\\right\\rangle$"
        },
        {
          "id": "u6e1q5",
          "lesson": "u6-l1",
          "difficulty": "hard",
          "text": "في الشكل الآتي $OAB$ مثلث فيه: $\\overrightarrow{OA}=2\\vec{\\mathbf{a}}$ ، $\\overrightarrow{OB}=3\\vec{\\mathbf{b}}$ ، والنقطة $M$ تقع على الضلع $\\overline{AB}$ بحيث $AM:MB=1:2$. المتجه $\\overrightarrow{OM}$ بدلالة $\\vec{\\mathbf{a}}$ و $\\vec{\\mathbf{b}}$ هو:",
          "options": [
            "$\\frac{4}{3}\\vec{\\mathbf{a}}+\\vec{\\mathbf{b}}$",
            "$\\frac{2}{3}\\vec{\\mathbf{a}}+2\\vec{\\mathbf{b}}$",
            "$2\\vec{\\mathbf{a}}+\\vec{\\mathbf{b}}$",
            "$\\vec{\\mathbf{a}}+\\frac{3}{2}\\vec{\\mathbf{b}}$"
          ],
          "answer": 0,
          "solution": "$\\overrightarrow{AB}=\\overrightarrow{OB}-\\overrightarrow{OA}=3\\vec{\\mathbf{b}}-2\\vec{\\mathbf{a}}$ ، و $\\overrightarrow{AM}=\\frac13\\overrightarrow{AB}$ (لأن $AM:MB=1:2$)\n$\\overrightarrow{OM}=\\overrightarrow{OA}+\\frac13\\overrightarrow{AB}=2\\vec{\\mathbf{a}}+\\vec{\\mathbf{b}}-\\frac23\\vec{\\mathbf{a}}=\\frac43\\vec{\\mathbf{a}}+\\vec{\\mathbf{b}}$",
          "figure": "fig/u6e1q5.svg"
        },
        {
          "id": "u6e1q6",
          "lesson": "u6-l2",
          "difficulty": "easy",
          "text": "إذا كان المستقيم $l$ يوازي المتجه: $\\vec{\\mathbf{v}}=2\\hat{i}-3\\hat{j}+\\hat{k}$ ، ويمرّ بالنقطة $A$ التي متجه موقعها: $4\\hat{i}+\\hat{j}-2\\hat{k}$ ، فإنّ للمستقيم $l$ معادلة متجهة هي:",
          "options": [
            "$\\vec{\\mathbf{r}}=\\langle 4,\\,1,\\,-2\\rangle+t\\langle 2,\\,-3,\\,1\\rangle$",
            "$\\vec{\\mathbf{r}}=\\langle 2,\\,-3,\\,1\\rangle+t\\langle 4,\\,1,\\,-2\\rangle$",
            "$\\vec{\\mathbf{r}}=\\langle 4,\\,1,\\,-2\\rangle+t\\langle -3,\\,2,\\,1\\rangle$",
            "$\\vec{\\mathbf{r}}=\\langle 1,\\,4,\\,-2\\rangle+t\\langle 2,\\,-3,\\,1\\rangle$"
          ],
          "answer": 0,
          "solution": "معادلة المستقيم: $\\vec{\\mathbf{r}}=\\vec{\\mathbf{r}}_0+t\\vec{\\mathbf{v}}$ ، حيث $\\vec{\\mathbf{r}}_0=\\langle 4,1,-2\\rangle$ متجه موقع نقطة عليه، و $\\vec{\\mathbf{v}}=\\langle 2,-3,1\\rangle$ متجه اتجاهه."
        },
        {
          "id": "u6e1q7",
          "lesson": "u6-l2",
          "difficulty": "medium",
          "text": "النقطة الواقعة على المستقيم الذي له المعادلة المتجهة: $\\vec{\\mathbf{r}}=\\langle 1,\\,-2,\\,3\\rangle+t\\langle 2,\\,1,\\,-1\\rangle$ ، والإحداثي $z$ لها $-1$ ، هي:",
          "options": [
            "$(9,\\,2,\\,-1)$",
            "$(-7,\\,-6,\\,7)$",
            "$(7,\\,1,\\,0)$",
            "$(9,\\,-2,\\,-1)$"
          ],
          "answer": 0,
          "solution": "$z=3-t=-1 \\Rightarrow t=4$ ، فتكون النقطة $(1+8,\\ -2+4,\\ -1)=(9,\\,2,\\,-1)$"
        },
        {
          "id": "u6e1q8",
          "lesson": "u6-l2",
          "difficulty": "medium",
          "text": "العلاقة بين المستقيمين: $\\vec{\\mathbf{r}}_1=\\langle 1,1,0\\rangle+t\\langle 2,-1,3\\rangle$ و $\\vec{\\mathbf{r}}_2=\\langle 3,0,4\\rangle+s\\langle -4,2,-6\\rangle$ هي أنّهما:",
          "options": [
            "متوازيان",
            "متقاطعان",
            "متخالفان",
            "منطبقان"
          ],
          "answer": 0,
          "solution": "$\\langle -4,2,-6\\rangle=-2\\langle 2,-1,3\\rangle$ ، فمتجها الاتجاه متوازيان، والمستقيمان إمّا متوازيان أو منطبقان.\nالمتجه بين النقطتين $(1,1,0)$ و $(3,0,4)$ هو $\\langle 2,-1,4\\rangle$ ، وهو لا يوازي $\\langle 2,-1,3\\rangle$ ، فالنقطة $(3,0,4)$ لا تقع على $\\vec{\\mathbf{r}}_1$\nإذن المستقيمان متوازيان."
        },
        {
          "id": "u6e1q9",
          "lesson": "u6-l2",
          "difficulty": "hard",
          "text": "إحداثيات نقطة تقاطع المستقيمين: $\\vec{\\mathbf{r}}_1=\\langle 2,1,0\\rangle+t\\langle 1,2,-1\\rangle$ و $\\vec{\\mathbf{r}}_2=\\langle 7,4,0\\rangle+s\\langle 3,-1,2\\rangle$ هي:",
          "options": [
            "$(4,\\,5,\\,-2)$",
            "$(7,\\,4,\\,0)$",
            "$(3,\\,3,\\,-1)$",
            "$(1,\\,6,\\,-4)$"
          ],
          "answer": 0,
          "solution": "نساوي الإحداثيات: $2+t=7+3s$ ، $1+2t=4-s$ ، $-t=2s$\nمن الثالثة: $t=-2s$ ، وبالتعويض في الأولى: $2-2s=7+3s \\Rightarrow s=-1,\\ t=2$\nتحقق في الثانية: $1+4=5=4+1$ ✔ ، ونقطة التقاطع $\\langle 2,1,0\\rangle+2\\langle 1,2,-1\\rangle=(4,\\,5,\\,-2)$"
        },
        {
          "id": "u6e1q10",
          "lesson": "u6-l3",
          "difficulty": "easy",
          "text": "إذا كان المتجهان: $\\vec{\\mathbf{u}}=\\langle 3,\\,-1,\\,2\\rangle$ و $\\vec{\\mathbf{v}}=\\langle 1,\\,4,\\,k\\rangle$ متعامدين، فإنّ قيمة $k$ هي:",
          "options": [
            "$\\frac{1}{2}$",
            "$-\\frac{1}{2}$",
            "$2$",
            "$\\frac{7}{2}$"
          ],
          "answer": 0,
          "solution": "المتجهان متعامدان إذا كان $\\vec{\\mathbf{u}}\\cdot\\vec{\\mathbf{v}}=0$: $3-4+2k=0 \\Rightarrow k=\\frac12$"
        },
        {
          "id": "u6e1q11",
          "lesson": "u6-l3",
          "difficulty": "medium",
          "text": "إذا كان: $\\vec{\\mathbf{a}}=\\langle 2,\\,1,\\,-1\\rangle$ ، $\\vec{\\mathbf{b}}=\\langle 1,\\,-1,\\,2\\rangle$ ، فإنّ قياس الزاوية بين المتجهين $(\\vec{\\mathbf{a}}-\\vec{\\mathbf{b}})$ و $(\\vec{\\mathbf{a}}+\\vec{\\mathbf{b}})$ هو:",
          "options": [
            "$\\frac{\\pi}{2}$",
            "$\\frac{\\pi}{3}$",
            "$\\frac{\\pi}{4}$",
            "$\\frac{\\pi}{6}$"
          ],
          "answer": 0,
          "solution": "$\\vec{\\mathbf{a}}-\\vec{\\mathbf{b}}=\\langle 1,2,-3\\rangle$ ، $\\vec{\\mathbf{a}}+\\vec{\\mathbf{b}}=\\langle 3,0,1\\rangle$\nالضرب القياسي $=3+0-3=0$ ، إذن الزاوية $\\frac{\\pi}{2}$\n(ملاحظة: $(\\vec{\\mathbf{a}}-\\vec{\\mathbf{b}})\\cdot(\\vec{\\mathbf{a}}+\\vec{\\mathbf{b}})=|\\vec{\\mathbf{a}}|^2-|\\vec{\\mathbf{b}}|^2=6-6=0$)"
        },
        {
          "id": "u6e1q12",
          "lesson": "u6-l3",
          "difficulty": "hard",
          "text": "إذا كان $ABC$ مثلثًا فيه: $\\overrightarrow{BA}=\\langle 2,\\,-1,\\,2\\rangle$ ، $\\overrightarrow{BC}=\\langle 4,\\,4,\\,-2\\rangle$ ، فإنّ مساحته بالوحدات المربعة تساوي:",
          "options": [
            "$9$",
            "$18$",
            "$6$",
            "$12$"
          ],
          "answer": 0,
          "solution": "$\\overrightarrow{BA}\\cdot\\overrightarrow{BC}=8-4-4=0$ ، إذن الزاوية $B$ قائمة\n$|\\overrightarrow{BA}|=3$ ، $|\\overrightarrow{BC}|=\\sqrt{16+16+4}=6$ ، والمساحة $=\\frac12(3)(6)=9$"
        }
      ]
    },
    {
      "id": "u6-e2",
      "title": "الاختبار الثاني",
      "questions": [
        {
          "id": "u6e2q1",
          "lesson": "u6-l1",
          "difficulty": "easy",
          "text": "إذا كان: $\\vec{\\mathbf{v}}=\\langle 1,\\,-2,\\,4\\rangle$ ، $\\vec{\\mathbf{w}}=\\langle 3,\\,0,\\,-1\\rangle$ ، فإنّ $3\\vec{\\mathbf{v}}-2\\vec{\\mathbf{w}}$ يساوي:",
          "options": [
            "$\\langle -3,\\,-6,\\,14\\rangle$",
            "$\\langle -3,\\,-6,\\,10\\rangle$",
            "$\\langle 9,\\,-6,\\,10\\rangle$",
            "$\\langle -3,\\,6,\\,14\\rangle$"
          ],
          "answer": 0,
          "solution": "$3\\vec{\\mathbf{v}}=\\langle 3,-6,12\\rangle$ ، $2\\vec{\\mathbf{w}}=\\langle 6,0,-2\\rangle$ ، الفرق $\\langle -3,\\,-6,\\,14\\rangle$"
        },
        {
          "id": "u6e2q2",
          "lesson": "u6-l1",
          "difficulty": "medium",
          "text": "إذا كان المتجه $\\vec{\\mathbf{u}}=\\langle a,\\,6,\\,-3\\rangle$ يوازي المتجه $\\vec{\\mathbf{v}}=\\langle 2,\\,-4,\\,b\\rangle$ ، فإنّ قيمة $a+b$ هي:",
          "options": [
            "$-1$",
            "$1$",
            "$-5$",
            "$5$"
          ],
          "answer": 0,
          "solution": "المتجهان متوازيان: $\\vec{\\mathbf{u}}=k\\vec{\\mathbf{v}}$ ، من المركبة الثانية: $6=-4k \\Rightarrow k=-\\frac32$\n$a=-\\frac32(2)=-3$ ، و $-3=-\\frac32b \\Rightarrow b=2$ ، إذن $a+b=-1$"
        },
        {
          "id": "u6e2q3",
          "lesson": "u6-l1",
          "difficulty": "medium",
          "text": "إذا كانت $A,\\ B,\\ C$ ثلاث نقاط في الفضاء، وكان: $\\overrightarrow{AB}=\\langle 2,\\,a-1,\\,4\\rangle$ ، $\\overrightarrow{AC}=\\langle 3,\\,6,\\,6\\rangle$ ، فإنّ قيمة $a$ التي تجعل النقاط $A,\\ B,\\ C$ تقع على استقامة واحدة هي:",
          "options": [
            "$5$",
            "$4$",
            "$3$",
            "$9$"
          ],
          "answer": 0,
          "solution": "تقع النقاط على استقامة واحدة إذا توازى $\\overrightarrow{AB}$ و $\\overrightarrow{AC}$: $\\overrightarrow{AB}=\\frac23\\overrightarrow{AC}$ (من المركبتين الأولى والثالثة)\n$a-1=\\frac23(6)=4 \\Rightarrow a=5$"
        },
        {
          "id": "u6e2q4",
          "lesson": "u6-l1",
          "difficulty": "hard",
          "text": "في متوازي المستطيلات الآتي، أحد رؤوسه نقطة الأصل $O$ ، وأحرفه $\\overline{OP}$ و $\\overline{OR}$ و $\\overline{OS}$ على المحاور $x$ و $y$ و $z$ على الترتيب. إذا كانت إحداثيات الرأس $U$ هي $(4,\\,6,\\,3)$ ، فإنّ إحداثيات نقطة منتصف القطعة $\\overline{PV}$ هي:",
          "options": [
            "$(2,\\,3,\\,\\frac{3}{2})$",
            "$(2,\\,3,\\,3)$",
            "$(4,\\,6,\\,3)$",
            "$(2,\\,0,\\,\\frac{3}{2})$"
          ],
          "answer": 0,
          "solution": "من الشكل: $P(4,0,0)$ على المحور $x$ ، و $V(0,6,3)$ (فوق $R(0,6,0)$ بارتفاع $3$)\nمنتصف $\\overline{PV}$: $\\left(\\dfrac{4+0}{2},\\ \\dfrac{0+6}{2},\\ \\dfrac{0+3}{2}\\right)=\\left(2,\\,3,\\,\\frac32\\right)$",
          "figure": "fig/u6e2q4.svg"
        },
        {
          "id": "u6e2q5",
          "lesson": "u6-l1",
          "difficulty": "medium",
          "text": "إذا كان: $\\vec{\\mathbf{v}}=\\langle c,\\,-2,\\,4\\rangle$ ، وكان: $|\\vec{\\mathbf{v}}|=6$ ، فإنّ قيم $c$ هي:",
          "options": [
            "$\\pm 4$",
            "$4$",
            "$\\pm 2\\sqrt{14}$",
            "$\\pm 16$"
          ],
          "answer": 0,
          "solution": "$\\sqrt{c^2+4+16}=6 \\Rightarrow c^2+20=36 \\Rightarrow c^2=16 \\Rightarrow c=\\pm4$"
        },
        {
          "id": "u6e2q6",
          "lesson": "u6-l2",
          "difficulty": "easy",
          "text": "المعادلة المتجهة للمستقيم المارّ بالنقطتين: $A(3,\\,-1,\\,2)$ و $B(5,\\,2,\\,-2)$ هي:",
          "options": [
            "$\\vec{\\mathbf{r}}=\\langle 3,\\,-1,\\,2\\rangle+t\\langle 2,\\,3,\\,-4\\rangle$",
            "$\\vec{\\mathbf{r}}=\\langle 3,\\,-1,\\,2\\rangle+t\\langle 5,\\,2,\\,-2\\rangle$",
            "$\\vec{\\mathbf{r}}=\\langle 2,\\,3,\\,-4\\rangle+t\\langle 3,\\,-1,\\,2\\rangle$",
            "$\\vec{\\mathbf{r}}=\\langle 3,\\,-1,\\,2\\rangle+t\\langle 8,\\,1,\\,0\\rangle$"
          ],
          "answer": 0,
          "solution": "متجه الاتجاه $\\overrightarrow{AB}=\\langle 5-3,\\,2+1,\\,-2-2\\rangle=\\langle 2,\\,3,\\,-4\\rangle$ ، والمستقيم يمرّ بـ $A$:\n$\\vec{\\mathbf{r}}=\\langle 3,-1,2\\rangle+t\\langle 2,3,-4\\rangle$"
        },
        {
          "id": "u6e2q7",
          "lesson": "u6-l2",
          "difficulty": "medium",
          "text": "إذا كانت: $\\vec{\\mathbf{r}}=\\langle 6,\\,-2,\\,5\\rangle+t\\langle 3,\\,1,\\,-2\\rangle$ معادلة متجهة للمستقيم $l$ ، فإنّ قيمة $t$ التي تُقابل نقطة تقاطع المستقيم $l$ مع المستوى $yz$ هي:",
          "options": [
            "$-2$",
            "$2$",
            "$\\frac{5}{2}$",
            "$-3$"
          ],
          "answer": 0,
          "solution": "على المستوى $yz$ يكون $x=0$: $6+3t=0 \\Rightarrow t=-2$"
        },
        {
          "id": "u6e2q8",
          "lesson": "u6-l2",
          "difficulty": "hard",
          "text": "العلاقة بين المستقيمين: $\\vec{\\mathbf{r}}_1=\\langle 1,0,2\\rangle+t\\langle 1,1,1\\rangle$ و $\\vec{\\mathbf{r}}_2=\\langle 2,3,1\\rangle+s\\langle 2,-1,1\\rangle$ هي أنّهما:",
          "options": [
            "متخالفان",
            "متوازيان",
            "متقاطعان",
            "منطبقان"
          ],
          "answer": 0,
          "solution": "متجها الاتجاه غير متوازيين، فالمستقيمان إمّا متقاطعان أو متخالفان. نساوي الإحداثيات:\n$1+t=2+2s$ ، $t=3-s$ ، $2+t=1+s$\nمن الثانية والثالثة: $2+3-s=1+s \\Rightarrow s=2,\\ t=1$ ، وبالتعويض في الأولى: $2\\ne6$\nلا يوجد حلّ مشترك، إذن المستقيمان متخالفان."
        },
        {
          "id": "u6e2q9",
          "lesson": "u6-l3",
          "difficulty": "hard",
          "text": "إذا كانت: $\\vec{\\mathbf{r}}=\\langle 1,\\,0,\\,2\\rangle+t\\langle 1,\\,2,\\,-1\\rangle$ معادلة متجهة للمستقيم $l$ ، والنقطة $P(4,\\,5,\\,3)$ غير واقعة عليه، فإنّ إحداثيات مسقط العمود من النقطة $P$ على المستقيم $l$ هي:",
          "options": [
            "$(3,\\,4,\\,0)$",
            "$(1,\\,0,\\,2)$",
            "$(2,\\,2,\\,1)$",
            "$(5,\\,8,\\,-2)$"
          ],
          "answer": 0,
          "solution": "نفرض المسقط $Q=(1+t,\\ 2t,\\ 2-t)$ ، فيكون $\\overrightarrow{PQ}=\\langle t-3,\\ 2t-5,\\ -t-1\\rangle$ عموديًّا على $\\langle 1,2,-1\\rangle$:\n$(t-3)+2(2t-5)-(-t-1)=0 \\Rightarrow 6t-12=0 \\Rightarrow t=2$ ، إذن $Q=(3,\\,4,\\,0)$"
        },
        {
          "id": "u6e2q10",
          "lesson": "u6-l3",
          "difficulty": "easy",
          "text": "إذا كان: $|\\vec{\\mathbf{a}}|=4$ ، $|\\vec{\\mathbf{b}}|=5$ ، وقياس الزاوية بينهما $120^\\circ$ ، فإنّ $\\vec{\\mathbf{a}}\\cdot\\vec{\\mathbf{b}}$ يساوي:",
          "options": [
            "$-10$",
            "$10$",
            "$-10\\sqrt{3}$",
            "$20$"
          ],
          "answer": 0,
          "solution": "$\\vec{\\mathbf{a}}\\cdot\\vec{\\mathbf{b}}=|\\vec{\\mathbf{a}}||\\vec{\\mathbf{b}}|\\cos\\theta=4(5)\\cos120^\\circ=20\\left(-\\frac12\\right)=-10$"
        },
        {
          "id": "u6e2q11",
          "lesson": "u6-l3",
          "difficulty": "medium",
          "text": "إذا كان قياس الزاوية بين $\\vec{\\mathbf{a}}$ و $\\vec{\\mathbf{b}}$ هو $60^\\circ$ ، وكان: $|\\vec{\\mathbf{a}}|=6$ ، $\\vec{\\mathbf{a}}\\cdot\\vec{\\mathbf{b}}=12$ ، فإنّ مقدار $\\vec{\\mathbf{b}}$ هو:",
          "options": [
            "$4$",
            "$2$",
            "$8$",
            "$\\frac{4\\sqrt{3}}{3}$"
          ],
          "answer": 0,
          "solution": "$12=6|\\vec{\\mathbf{b}}|\\cos60^\\circ=3|\\vec{\\mathbf{b}}| \\Rightarrow |\\vec{\\mathbf{b}}|=4$"
        },
        {
          "id": "u6e2q12",
          "lesson": "u6-l3",
          "difficulty": "medium",
          "text": "إذا كان المتجه: $\\vec{\\mathbf{v}}=3\\hat{i}+c\\hat{j}+2\\hat{k}$ يُعامد المتجه: $\\vec{\\mathbf{w}}=2\\hat{i}-\\hat{j}+d\\hat{k}$ ، حيث $c,\\ d$ ثابتان، فإنّ $c-2d$ تساوي:",
          "options": [
            "$6$",
            "$-6$",
            "$3$",
            "$-3$"
          ],
          "answer": 0,
          "solution": "$\\vec{\\mathbf{v}}\\cdot\\vec{\\mathbf{w}}=6-c+2d=0 \\Rightarrow c-2d=6$"
        }
      ]
    },
    {
      "id": "u6-e3",
      "title": "الاختبار الثالث",
      "questions": [
        {
          "id": "u6e3q1",
          "lesson": "u6-l1",
          "difficulty": "easy",
          "text": "إحداثيات نقطة منتصف القطعة المستقيمة الواصلة بين النقطتين: $A(-2,\\,5,\\,1)$ و $B(4,\\,-1,\\,7)$ هي:",
          "options": [
            "$(1,\\,2,\\,4)$",
            "$(2,\\,4,\\,8)$",
            "$(3,\\,-3,\\,3)$",
            "$(-3,\\,3,\\,-3)$"
          ],
          "answer": 0,
          "solution": "$M=\\left(\\dfrac{-2+4}{2},\\ \\dfrac{5-1}{2},\\ \\dfrac{1+7}{2}\\right)=(1,\\,2,\\,4)$"
        },
        {
          "id": "u6e3q2",
          "lesson": "u6-l1",
          "difficulty": "easy",
          "text": "إذا كانت: $A(3,\\,-2,\\,5)$ ، $B(-1,\\,4,\\,2)$ ، فإنّ الصورة الإحداثية للمتجه $\\overrightarrow{BA}$ هي:",
          "options": [
            "$\\langle 4,\\,-6,\\,3\\rangle$",
            "$\\langle -4,\\,6,\\,-3\\rangle$",
            "$\\langle 2,\\,2,\\,7\\rangle$",
            "$\\langle -2,\\,-2,\\,-7\\rangle$"
          ],
          "answer": 0,
          "solution": "$\\overrightarrow{BA}=A-B=\\langle 3+1,\\,-2-4,\\,5-2\\rangle=\\langle 4,\\,-6,\\,3\\rangle$ (لاحظ الترتيب: نهاية المتجه ناقص بدايته)"
        },
        {
          "id": "u6e3q3",
          "lesson": "u6-l1",
          "difficulty": "medium",
          "text": "$ABCD$ متوازي أضلاع، فيه: $A(2,\\,-1,\\,3)$ ، $B(5,\\,1,\\,0)$ ، $C(4,\\,4,\\,2)$. إحداثيات الرأس $D$ هي:",
          "options": [
            "$(1,\\,2,\\,5)$",
            "$(7,\\,6,\\,-1)$",
            "$(3,\\,-4,\\,1)$",
            "$(1,\\,2,\\,-5)$"
          ],
          "answer": 0,
          "solution": "في متوازي الأضلاع $\\overrightarrow{AD}=\\overrightarrow{BC}=\\langle -1,\\,3,\\,2\\rangle$\n$D=A+\\overrightarrow{BC}=(2-1,\\ -1+3,\\ 3+2)=(1,\\,2,\\,5)$"
        },
        {
          "id": "u6e3q4",
          "lesson": "u6-l1",
          "difficulty": "hard",
          "text": "في الشكل الآتي $OABC$ متوازي أضلاع، فيه: $\\overrightarrow{OA}=2\\vec{\\mathbf{a}}$ ، $\\overrightarrow{OC}=3\\vec{\\mathbf{c}}$. إذا كانت $M$ منتصف الضلع $\\overline{CB}$ ، وكانت $P$ نقطة على القطر $\\overline{OB}$ بحيث $OP:PB=2:1$ ، فإنّ المتجه $\\overrightarrow{PM}$ بدلالة $\\vec{\\mathbf{a}}$ و $\\vec{\\mathbf{c}}$ هو:",
          "options": [
            "$-\\frac{1}{3}\\vec{\\mathbf{a}}+\\vec{\\mathbf{c}}$",
            "$\\frac{1}{3}\\vec{\\mathbf{a}}-\\vec{\\mathbf{c}}$",
            "$\\frac{7}{3}\\vec{\\mathbf{a}}+5\\vec{\\mathbf{c}}$",
            "$-\\frac{1}{3}\\vec{\\mathbf{a}}+5\\vec{\\mathbf{c}}$"
          ],
          "answer": 0,
          "solution": "$\\overrightarrow{OM}=\\overrightarrow{OC}+\\frac12\\overrightarrow{CB}=3\\vec{\\mathbf{c}}+\\frac12(2\\vec{\\mathbf{a}})=\\vec{\\mathbf{a}}+3\\vec{\\mathbf{c}}$\n$\\overrightarrow{OP}=\\frac23\\overrightarrow{OB}=\\frac23(2\\vec{\\mathbf{a}}+3\\vec{\\mathbf{c}})=\\frac43\\vec{\\mathbf{a}}+2\\vec{\\mathbf{c}}$\n$\\overrightarrow{PM}=\\overrightarrow{OM}-\\overrightarrow{OP}=-\\frac13\\vec{\\mathbf{a}}+\\vec{\\mathbf{c}}$",
          "figure": "fig/u6e3q4.svg"
        },
        {
          "id": "u6e3q5",
          "lesson": "u6-l1",
          "difficulty": "medium",
          "text": "إذا وقعت النقاط: $P(1,\\,2,\\,3)$ ، $Q(3,\\,h,\\,7)$ ، $R(4,\\,8,\\,k)$ على مستقيم واحد، فإنّ قيمة $h+k$ هي:",
          "options": [
            "$15$",
            "$12$",
            "$9$",
            "$18$"
          ],
          "answer": 0,
          "solution": "$\\overrightarrow{PQ}=\\langle 2,\\,h-2,\\,4\\rangle$ ، $\\overrightarrow{PR}=\\langle 3,\\,6,\\,k-3\\rangle$ ، ويجب أن يكون $\\overrightarrow{PQ}=\\frac23\\overrightarrow{PR}$\n$h-2=4 \\Rightarrow h=6$ ، و $4=\\frac23(k-3) \\Rightarrow k=9$ ، إذن $h+k=15$"
        },
        {
          "id": "u6e3q6",
          "lesson": "u6-l2",
          "difficulty": "easy",
          "text": "النقطة الواقعة على المستقيم: $\\vec{\\mathbf{r}}=\\langle -1,\\,4,\\,2\\rangle+t\\langle 2,\\,-1,\\,3\\rangle$ ، والإحداثي $y$ لها يساوي $1$ ، هي:",
          "options": [
            "$(5,\\,1,\\,11)$",
            "$(-7,\\,1,\\,-7)$",
            "$(5,\\,1,\\,-7)$",
            "$(1,\\,1,\\,5)$"
          ],
          "answer": 0,
          "solution": "$y=4-t=1 \\Rightarrow t=3$ ، فالنقطة $(-1+6,\\ 1,\\ 2+9)=(5,\\,1,\\,11)$"
        },
        {
          "id": "u6e3q7",
          "lesson": "u6-l2",
          "difficulty": "medium",
          "text": "معادلة المستقيم المارّ بالنقطة $(1,\\,-1,\\,2)$ ، والموازي للمستقيم: $\\vec{\\mathbf{r}}=\\langle 0,\\,3,\\,1\\rangle+t\\langle 4,\\,-2,\\,1\\rangle$ ، هي:",
          "options": [
            "$\\vec{\\mathbf{r}}=\\langle 1,\\,-1,\\,2\\rangle+t\\langle 4,\\,-2,\\,1\\rangle$",
            "$\\vec{\\mathbf{r}}=\\langle 0,\\,3,\\,1\\rangle+t\\langle 1,\\,-1,\\,2\\rangle$",
            "$\\vec{\\mathbf{r}}=\\langle 1,\\,-1,\\,2\\rangle+t\\langle 0,\\,3,\\,1\\rangle$",
            "$\\vec{\\mathbf{r}}=\\langle 4,\\,-2,\\,1\\rangle+t\\langle 1,\\,-1,\\,2\\rangle$"
          ],
          "answer": 0,
          "solution": "المستقيمان المتوازيان لهما متجه الاتجاه نفسه $\\langle 4,-2,1\\rangle$ ، والمستقيم المطلوب يمرّ بالنقطة $(1,-1,2)$"
        },
        {
          "id": "u6e3q8",
          "lesson": "u6-l2",
          "difficulty": "hard",
          "text": "العلاقة بين المستقيمين: $\\vec{\\mathbf{r}}_1=\\langle 2,-1,0\\rangle+t\\langle 1,3,-2\\rangle$ و $\\vec{\\mathbf{r}}_2=\\langle 4,5,-4\\rangle+s\\langle -2,-6,4\\rangle$ هي أنّهما:",
          "options": [
            "منطبقان",
            "متوازيان",
            "متقاطعان",
            "متخالفان"
          ],
          "answer": 0,
          "solution": "$\\langle -2,-6,4\\rangle=-2\\langle 1,3,-2\\rangle$ ، فمتجها الاتجاه متوازيان.\nالنقطة $(4,5,-4)$ تقع على $\\vec{\\mathbf{r}}_1$ عند $t=2$: $\\langle 2+2,\\,-1+6,\\,0-4\\rangle=\\langle 4,5,-4\\rangle$ ✔\nإذن المستقيمان منطبقان."
        },
        {
          "id": "u6e3q9",
          "lesson": "u6-l2",
          "difficulty": "hard",
          "text": "إحداثيات نقطة تقاطع المستقيمين: $\\vec{\\mathbf{r}}_1=\\langle 1,0,-2\\rangle+t\\langle 2,-1,3\\rangle$ و $\\vec{\\mathbf{r}}_2=\\langle -3,-3,-7\\rangle+s\\langle 1,2,1\\rangle$ هي:",
          "options": [
            "$(-1,\\,1,\\,-5)$",
            "$(3,\\,-1,\\,1)$",
            "$(-3,\\,-3,\\,-7)$",
            "$(1,\\,0,\\,-2)$"
          ],
          "answer": 0,
          "solution": "$1+2t=-3+s$ ، $-t=-3+2s$ ، $-2+3t=-7+s$\nبطرح الأولى من الثالثة: $-3+t=-4 \\Rightarrow t=-1$ ، ومنه $s=2$ ، وتحقق في الثانية: $1=-3+4$ ✔\nنقطة التقاطع: $\\langle 1,0,-2\\rangle-\\langle 2,-1,3\\rangle=(-1,\\,1,\\,-5)$"
        },
        {
          "id": "u6e3q10",
          "lesson": "u6-l3",
          "difficulty": "easy",
          "text": "إذا كان: $\\vec{\\mathbf{a}}=\\langle 2,\\,-3,\\,1\\rangle$ ، $\\vec{\\mathbf{b}}=\\langle 4,\\,1,\\,-2\\rangle$ ، فإنّ $\\vec{\\mathbf{a}}\\cdot\\vec{\\mathbf{b}}$ يساوي:",
          "options": [
            "$3$",
            "$-3$",
            "$11$",
            "$7$"
          ],
          "answer": 0,
          "solution": "$\\vec{\\mathbf{a}}\\cdot\\vec{\\mathbf{b}}=2(4)+(-3)(1)+1(-2)=8-3-2=3$"
        },
        {
          "id": "u6e3q11",
          "lesson": "u6-l3",
          "difficulty": "medium",
          "text": "قياس الزاوية بين المتجهين: $\\langle 1,\\,-1,\\,0\\rangle$ و $\\langle 0,\\,1,\\,-1\\rangle$ هو:",
          "options": [
            "$\\frac{2\\pi}{3}$",
            "$\\frac{\\pi}{3}$",
            "$\\frac{\\pi}{6}$",
            "$\\frac{5\\pi}{6}$"
          ],
          "answer": 0,
          "solution": "$\\cos\\theta=\\dfrac{0-1+0}{\\sqrt2\\cdot\\sqrt2}=-\\dfrac12 \\Rightarrow \\theta=\\dfrac{2\\pi}{3}$ (الزاوية بين متجهين قد تكون منفرجة)"
        },
        {
          "id": "u6e3q12",
          "lesson": "u6-l3",
          "difficulty": "hard",
          "text": "إذا كانت $M,\\ N,\\ P$ ثلاث نقاط في الفضاء، وكان: $\\overrightarrow{MN}=\\langle 1,\\,4,\\,-2\\rangle$ ، $\\overrightarrow{PN}=\\langle 3,\\,-1,\\,2\\rangle$ ، فإنّ $\\overrightarrow{MN}\\cdot\\overrightarrow{MP}$ يساوي:",
          "options": [
            "$26$",
            "$16$",
            "$-5$",
            "$10$"
          ],
          "answer": 0,
          "solution": "$\\overrightarrow{MP}=\\overrightarrow{MN}+\\overrightarrow{NP}=\\overrightarrow{MN}-\\overrightarrow{PN}=\\langle -2,\\,5,\\,-4\\rangle$\n$\\overrightarrow{MN}\\cdot\\overrightarrow{MP}=-2+20+8=26$"
        }
      ]
    }
  ]
};

export default unit;
