// Generated by question-bank/u6.py (verified). Do not edit by hand.
import type { Unit } from '../types';

const unit: Unit = {
  "id": "u6",
  "number": 6,
  "semester": 2,
  "title": "المتجهات",
  "description": "النقاط والمتجهات في الفضاء: المقدار ومتجه الوحدة والتوازي ونقطة المنتصف ومسائل النسبة، معادلة المستقيم في الفضاء والعلاقة بين مستقيمين ونقطة التقاطع، والضرب القياسي والزاوية بين متجهين.",
  "lessons": [
    {
      "id": "u6-l1",
      "title": "المتجهات في الفضاء"
    },
    {
      "id": "u6-l2",
      "title": "المستقيمات في الفضاء"
    },
    {
      "id": "u6-l3",
      "title": "الضرب القياسي"
    }
  ],
  "exams": [
    {
      "id": "u6-e1",
      "title": "الاختبار الأول",
      "questions": [
        {
          "id": "u6e1q1",
          "lesson": "u6-l1",
          "difficulty": "easy",
          "text": "إذا كانت: $A(3,\\,-2,\\,2)$ ، $B(-3,\\,1,\\,4)$ نقطتين في الفضاء، فإنّ مقدار المتجه $\\overrightarrow{AB}$ هو:",
          "options": [
            "$7$",
            "$49$",
            "$5$",
            "$\\sqrt{13}$"
          ],
          "answer": 0,
          "solution": "$\\overrightarrow{AB}=\\langle -3-3,\\,1+2,\\,4-2\\rangle=\\langle -6,\\,3,\\,2\\rangle$ ، و $|\\overrightarrow{AB}|=\\sqrt{36+9+4}=\\sqrt{49}=7$",
          "explain": {
            "idea": "مقدار متجه بين نقطتين ← نجد المتجه أولًا (النهاية − البداية)، ثم نحسب مقداره بالجذر.",
            "steps": [
              "## أولًا: المتجه AB",
              "المتجه من النقطة $A$ إلى النقطة $B$: $\\overrightarrow{AB}=B-A$ (إحداثيات النهاية ناقص إحداثيات البداية)",
              "$\\overrightarrow{AB}=\\langle -3-3,\\ 1-(-2),\\ 4-2\\rangle=\\langle -6,\\ 3,\\ 2\\rangle$",
              "## ثانيًا: المقدار",
              "مقدار المتجه $\\langle a,b,c\\rangle$ هو $\\sqrt{a^2+b^2+c^2}$",
              "$|\\overrightarrow{AB}|=\\sqrt{(-6)^2+3^2+2^2}=\\sqrt{36+9+4}=\\sqrt{49}=7$"
            ],
            "wrong": [
              null,
              "$49$ هو مربّع المقدار؛ يجب أخذ الجذر.",
              "تحقّقي من الحساب: $36+9+4=49$ وجذره $7$ لا $5$.",
              "نُسيت المركبة الأولى $-6$: $\\sqrt{9+4}=\\sqrt{13}$."
            ]
          }
        },
        {
          "id": "u6e1q2",
          "lesson": "u6-l1",
          "difficulty": "medium",
          "text": "إذا كانت: $A(1,\\,2,\\,-3)$ ، $B(4,\\,-1,\\,2)$ ، وكانت $D$ نقطة في الفضاء بحيث $\\overrightarrow{AB}=\\overrightarrow{BD}$ ، فإنّ متجه الموقع للنقطة $D$ هو:",
          "options": [
            "$\\langle 7,\\,-4,\\,7\\rangle$",
            "$\\langle -7,\\,4,\\,-7\\rangle$",
            "$\\langle 3,\\,-3,\\,5\\rangle$",
            "$\\langle \\frac{5}{2},\\,\\frac{1}{2},\\,- \\frac{1}{2}\\rangle$"
          ],
          "answer": 0,
          "solution": "$\\overrightarrow{AB}=\\overrightarrow{BD} \\Rightarrow B-A=D-B \\Rightarrow D=2B-A$\n$D=\\langle 8-1,\\,-2-2,\\,4+3\\rangle=\\langle 7,\\,-4,\\,7\\rangle$ (أي أن $B$ منتصف $\\overline{AD}$)",
          "explain": {
            "idea": "$\\overrightarrow{AB}=\\overrightarrow{BD}$ يعني أن الانتقال من $B$ إلى $D$ مثل الانتقال من $A$ إلى $B$ تمامًا، فتكون $B$ منتصف $\\overline{AD}$.",
            "steps": [
              "## أولًا: كتابة المعادلة",
              "المتجه من النقطة $A$ إلى النقطة $B$: $\\overrightarrow{AB}=B-A$ (إحداثيات النهاية ناقص إحداثيات البداية)",
              "$\\overrightarrow{AB}=B-A$ و $\\overrightarrow{BD}=D-B$",
              "$B-A=D-B$ ، ننقل $B$ إلى الطرف الأيسر: $D=2B-A$",
              "## ثانيًا: الحساب",
              "$2B=\\langle 8,\\ -2,\\ 4\\rangle$",
              "$D=\\langle 8-1,\\ -2-2,\\ 4-(-3)\\rangle=\\langle 7,\\ -4,\\ 7\\rangle$"
            ],
            "quick": "تحقّقي أن $B$ منتصف $\\overline{AD}$: $\\left(\\frac{1+7}{2},\\frac{2-4}{2},\\frac{-3+7}{2}\\right)=(4,-1,2)=B$ ✔",
            "wrong": [
              null,
              "الإشارات معكوسة؛ هذا $A-2B$ لا $2B-A$.",
              "هذا $\\overrightarrow{AB}=\\langle 3,-3,5\\rangle$ نفسه، لا متجه موقع $D$.",
              "هذا منتصف $\\overline{AB}$ ، بينما المطلوب نقطة تجعل $B$ هي المنتصف."
            ]
          }
        },
        {
          "id": "u6e1q3",
          "lesson": "u6-l1",
          "difficulty": "medium",
          "text": "إذا كانت: $A(1,\\,2,\\,-3)$ ، $C(\\alpha,\\,3,\\,2)$ ، وكان: $|\\overrightarrow{AC}|=\\sqrt{30}$ ، حيث $\\alpha>0$ ، فإنّ قيمة الثابت $\\alpha$ هي:",
          "options": [
            "$3$",
            "$-1$",
            "$5$",
            "$1$"
          ],
          "answer": 0,
          "solution": "$\\overrightarrow{AC}=\\langle \\alpha-1,\\,1,\\,5\\rangle$ ، و $(\\alpha-1)^2+1+25=30 \\Rightarrow (\\alpha-1)^2=4$\n$\\alpha-1=\\pm2 \\Rightarrow \\alpha=3$ أو $\\alpha=-1$ ، وبما أن $\\alpha>0$ فإن $\\alpha=3$",
          "explain": {
            "idea": "مقدار متجه فيه ثابت مجهول ← نكتب المتجه، ونساوي **مربّع** مقداره بمربّع القيمة المعطاة (للتخلّص من الجذر)، ثم نطبّق الشرط.",
            "steps": [
              "## أولًا: المتجه",
              "$\\overrightarrow{AC}=C-A=\\langle \\alpha-1,\\ 3-2,\\ 2-(-3)\\rangle=\\langle \\alpha-1,\\ 1,\\ 5\\rangle$",
              "## ثانيًا: المعادلة",
              "$|\\overrightarrow{AC}|^2=(\\sqrt{30})^2=30$",
              "$(\\alpha-1)^2+1+25=30$ ، إذن $(\\alpha-1)^2=4$",
              "## ثالثًا: الحلّ والشرط",
              "$\\alpha-1=2$ أو $\\alpha-1=-2$ ، أي $\\alpha=3$ أو $\\alpha=-1$",
              "المعطى $\\alpha>0$ ، إذن $\\alpha=3$"
            ],
            "wrong": [
              null,
              "$-1$ حلّ للمعادلة لكنه مرفوض لأن $\\alpha>0$.",
              "تحقّقي: $\\alpha=5$ يعطي $16+1+25=42\\neq30$.",
              "تحقّقي: $\\alpha=1$ يعطي $0+1+25=26\\neq30$."
            ]
          }
        },
        {
          "id": "u6e1q4",
          "lesson": "u6-l1",
          "difficulty": "easy",
          "text": "إذا كان: $\\vec{\\mathbf{v}}=\\langle 6,\\,-2,\\,3\\rangle$ ، فإنّ متجه الوحدة في اتجاه المتجه $\\vec{\\mathbf{v}}$ هو:",
          "options": [
            "$\\langle \\frac{6}{7},\\,- \\frac{2}{7},\\,\\frac{3}{7}\\rangle$",
            "$\\langle \\frac{6}{49},\\,- \\frac{2}{49},\\,\\frac{3}{49}\\rangle$",
            "$\\langle - \\frac{6}{7},\\,\\frac{2}{7},\\,- \\frac{3}{7}\\rangle$",
            "$\\langle \\frac{6}{11},\\,- \\frac{2}{11},\\,\\frac{3}{11}\\rangle$"
          ],
          "answer": 0,
          "solution": "$|\\vec{\\mathbf{v}}|=\\sqrt{36+4+9}=7$ ، ومتجه الوحدة $\\dfrac{\\vec{\\mathbf{v}}}{|\\vec{\\mathbf{v}}|}=\\left\\langle \\frac67,\\,-\\frac27,\\,\\frac37\\right\\rangle$",
          "explain": {
            "idea": "متجه الوحدة = المتجه مقسومًا على مقداره، فيبقى الاتجاه نفسه ويصبح الطول $1$.",
            "steps": [
              "متجه الوحدة في اتجاه $\\vec{\\mathbf{v}}$ هو $\\dfrac{\\vec{\\mathbf{v}}}{|\\vec{\\mathbf{v}}|}$ (نقسم كل مركبة على المقدار)، ومقداره دائمًا $1$",
              "$|\\vec{\\mathbf{v}}|=\\sqrt{6^2+(-2)^2+3^2}=\\sqrt{36+4+9}=\\sqrt{49}=7$",
              "$\\dfrac{\\vec{\\mathbf{v}}}{7}=\\left\\langle \\frac67,\\ -\\frac27,\\ \\frac37\\right\\rangle$",
              "تحقّق: $\\frac{36}{49}+\\frac{4}{49}+\\frac{9}{49}=1$ ✔"
            ],
            "wrong": [
              null,
              "نقسم على المقدار $7$ لا على مربّعه $49$.",
              "هذا في عكس اتجاه $\\vec{\\mathbf{v}}$ (كل الإشارات معكوسة).",
              "المقدار ليس مجموع القيم المطلقة للمركبات ($6+2+3=11$) ؛ $|\\vec{\\mathbf{v}}|=7$."
            ]
          }
        },
        {
          "id": "u6e1q5",
          "lesson": "u6-l1",
          "difficulty": "hard",
          "text": "في الشكل الآتي $OAB$ مثلث فيه: $\\overrightarrow{OA}=2\\vec{\\mathbf{a}}$ ، $\\overrightarrow{OB}=3\\vec{\\mathbf{b}}$ ، والنقطة $M$ تقع على الضلع $\\overline{AB}$ بحيث $AM:MB=1:2$. المتجه $\\overrightarrow{OM}$ بدلالة $\\vec{\\mathbf{a}}$ و $\\vec{\\mathbf{b}}$ هو:",
          "options": [
            "$\\frac{4}{3}\\vec{\\mathbf{a}}+\\vec{\\mathbf{b}}$",
            "$\\frac{2}{3}\\vec{\\mathbf{a}}+2\\vec{\\mathbf{b}}$",
            "$2\\vec{\\mathbf{a}}+\\vec{\\mathbf{b}}$",
            "$\\vec{\\mathbf{a}}+\\frac{3}{2}\\vec{\\mathbf{b}}$"
          ],
          "answer": 0,
          "solution": "$\\overrightarrow{AB}=\\overrightarrow{OB}-\\overrightarrow{OA}=3\\vec{\\mathbf{b}}-2\\vec{\\mathbf{a}}$ ، و $\\overrightarrow{AM}=\\frac13\\overrightarrow{AB}$ (لأن $AM:MB=1:2$)\n$\\overrightarrow{OM}=\\overrightarrow{OA}+\\frac13\\overrightarrow{AB}=2\\vec{\\mathbf{a}}+\\vec{\\mathbf{b}}-\\frac23\\vec{\\mathbf{a}}=\\frac43\\vec{\\mathbf{a}}+\\vec{\\mathbf{b}}$",
          "explain": {
            "idea": "نصل إلى $M$ من $O$ عبر $A$: $\\overrightarrow{OM}=\\overrightarrow{OA}+\\overrightarrow{AM}$ ، و $\\overrightarrow{AM}$ جزء من $\\overrightarrow{AB}$ حسب النسبة.",
            "steps": [
              "## أولًا: المتجه AB",
              "$\\overrightarrow{AB}=\\overrightarrow{OB}-\\overrightarrow{OA}=3\\vec{\\mathbf{b}}-2\\vec{\\mathbf{a}}$",
              "## ثانيًا: النسبة",
              "$AM:MB=1:2$ يعني أن $\\overline{AB}$ مقسوم إلى $1+2=3$ أجزاء متساوية، و $AM$ جزء واحد منها، فـ $\\overrightarrow{AM}=\\frac13\\overrightarrow{AB}$",
              "## ثالثًا: المسار من O إلى M",
              "$\\overrightarrow{OM}=2\\vec{\\mathbf{a}}+\\frac13(3\\vec{\\mathbf{b}}-2\\vec{\\mathbf{a}})=2\\vec{\\mathbf{a}}+\\vec{\\mathbf{b}}-\\frac23\\vec{\\mathbf{a}}$",
              "$2-\\frac23=\\frac43$ ، إذن $\\overrightarrow{OM}=\\frac43\\vec{\\mathbf{a}}+\\vec{\\mathbf{b}}$"
            ],
            "wrong": [
              null,
              "هذا ناتج أخذ $\\frac23\\overrightarrow{AB}$؛ لكن $AM$ ثلث $AB$ لا ثلثاه ($M$ أقرب إلى $A$).",
              "نُسي أن $\\frac13\\overrightarrow{AB}$ فيه $-\\frac23\\vec{\\mathbf{a}}$ أيضًا.",
              "هذا متجه موقع منتصف $\\overline{AB}$ ، والنسبة هنا $1:2$ لا $1:1$."
            ]
          },
          "figure": "fig/u6e1q5.svg"
        },
        {
          "id": "u6e1q6",
          "lesson": "u6-l2",
          "difficulty": "easy",
          "text": "إذا كان المستقيم $l$ يوازي المتجه: $\\vec{\\mathbf{v}}=2\\hat{i}-3\\hat{j}+\\hat{k}$ ، ويمرّ بالنقطة $A$ التي متجه موقعها: $4\\hat{i}+\\hat{j}-2\\hat{k}$ ، فإنّ للمستقيم $l$ معادلة متجهة هي:",
          "options": [
            "$\\vec{\\mathbf{r}}=\\langle 4,\\,1,\\,-2\\rangle+t\\langle 2,\\,-3,\\,1\\rangle$",
            "$\\vec{\\mathbf{r}}=\\langle 2,\\,-3,\\,1\\rangle+t\\langle 4,\\,1,\\,-2\\rangle$",
            "$\\vec{\\mathbf{r}}=\\langle 4,\\,1,\\,-2\\rangle+t\\langle -3,\\,2,\\,1\\rangle$",
            "$\\vec{\\mathbf{r}}=\\langle 1,\\,4,\\,-2\\rangle+t\\langle 2,\\,-3,\\,1\\rangle$"
          ],
          "answer": 0,
          "solution": "معادلة المستقيم: $\\vec{\\mathbf{r}}=\\vec{\\mathbf{r}}_0+t\\vec{\\mathbf{v}}$ ، حيث $\\vec{\\mathbf{r}}_0=\\langle 4,1,-2\\rangle$ متجه موقع نقطة عليه، و $\\vec{\\mathbf{v}}=\\langle 2,-3,1\\rangle$ متجه اتجاهه.",
          "explain": {
            "idea": "معادلة مستقيم ← نحتاج نقطة عليه (الحدّ الثابت) ومتجه اتجاهه (المضروب في $t$).",
            "steps": [
              "المعادلة المتجهة للمستقيم: $\\vec{\\mathbf{r}}=\\vec{\\mathbf{r}}_0+t\\vec{\\mathbf{v}}$ ، حيث $\\vec{\\mathbf{r}}_0$ متجه موقع نقطة على المستقيم، و $\\vec{\\mathbf{v}}$ متجه اتجاهه",
              "متجه الموقع $4\\hat i+\\hat j-2\\hat k$ يعني النقطة $\\langle 4,1,-2\\rangle$ (معاملات $\\hat i,\\hat j,\\hat k$ بالترتيب)",
              "المستقيم يوازي $\\vec{\\mathbf{v}}$ ، فمتجه اتجاهه $\\langle 2,-3,1\\rangle$",
              "$\\vec{\\mathbf{r}}=\\langle 4,1,-2\\rangle+t\\langle 2,-3,1\\rangle$"
            ],
            "wrong": [
              null,
              "النقطة ومتجه الاتجاه مبدّلان: الثابت هو النقطة، والمضروب في $t$ هو الاتجاه.",
              "ترتيب مركبات الاتجاه تغيّر: $2\\hat i-3\\hat j+\\hat k$ هو $\\langle 2,-3,1\\rangle$.",
              "ترتيب مركبات النقطة تغيّر: $4\\hat i+\\hat j$ يعني $x=4$ و $y=1$."
            ]
          }
        },
        {
          "id": "u6e1q7",
          "lesson": "u6-l2",
          "difficulty": "medium",
          "text": "النقطة الواقعة على المستقيم الذي له المعادلة المتجهة: $\\vec{\\mathbf{r}}=\\langle 1,\\,-2,\\,3\\rangle+t\\langle 2,\\,1,\\,-1\\rangle$ ، والإحداثي $z$ لها $-1$ ، هي:",
          "options": [
            "$(9,\\,2,\\,-1)$",
            "$(-7,\\,-6,\\,7)$",
            "$(7,\\,1,\\,0)$",
            "$(9,\\,-2,\\,-1)$"
          ],
          "answer": 0,
          "solution": "$z=3-t=-1 \\Rightarrow t=4$ ، فتكون النقطة $(1+8,\\ -2+4,\\ -1)=(9,\\,2,\\,-1)$",
          "explain": {
            "idea": "نقطة على المستقيم ← نكتب إحداثياتها العامة بدلالة $t$ ، ونستعمل المعلومة المعطاة لإيجاد $t$ ، ثم نعوّض في باقي الإحداثيات. هنا نعرف $z$ ، فنجد $t$ منها.",
            "steps": [
              "نقاط المستقيم: $(1+2t,\\ -2+t,\\ 3-t)$",
              "$z=-1$: $3-t=-1$ ، إذن $t=4$",
              "$x=1+2(4)=9$ ، $y=-2+4=2$",
              "النقطة $(9,\\ 2,\\ -1)$"
            ],
            "wrong": [
              null,
              "تنتج من $t=-4$؛ لكن من $3-t=-1$ تكون $t=4$ ، وعندها $z=7\\neq-1$ في هذا البديل.",
              "هذه النقطة عند $t=3$ ، وإحداثيها $z=0$ لا $-1$.",
              "$y=-2+4=+2$."
            ]
          }
        },
        {
          "id": "u6e1q8",
          "lesson": "u6-l2",
          "difficulty": "medium",
          "text": "العلاقة بين المستقيمين: $\\vec{\\mathbf{r}}_1=\\langle 1,1,0\\rangle+t\\langle 2,-1,3\\rangle$ و $\\vec{\\mathbf{r}}_2=\\langle 3,0,4\\rangle+s\\langle -4,2,-6\\rangle$ هي أنّهما:",
          "options": [
            "متوازيان",
            "متقاطعان",
            "متخالفان",
            "منطبقان"
          ],
          "answer": 0,
          "solution": "$\\langle -4,2,-6\\rangle=-2\\langle 2,-1,3\\rangle$ ، فمتجها الاتجاه متوازيان، والمستقيمان إمّا متوازيان أو منطبقان.\nالمتجه بين النقطتين $(1,1,0)$ و $(3,0,4)$ هو $\\langle 2,-1,4\\rangle$ ، وهو لا يوازي $\\langle 2,-1,3\\rangle$ ، فالنقطة $(3,0,4)$ لا تقع على $\\vec{\\mathbf{r}}_1$\nإذن المستقيمان متوازيان.",
          "explain": {
            "idea": "نفحص التوازي من متجهي الاتجاه أولًا، ثم نختبر نقطة من أحد المستقيمين على الآخر لنميّز بين التوازي والانطباق.",
            "steps": [
              "العلاقة بين مستقيمين: إذا توازى متجها الاتجاه فهما متوازيان أو منطبقان (نختبر نقطة من أحدهما على الآخر)، وإلّا فهما متقاطعان أو متخالفان (نحلّ معادلات تساوي الإحداثيات)",
              "## أولًا: التوازي",
              "$\\langle -4,2,-6\\rangle=-2\\langle 2,-1,3\\rangle$ ، فالاتجاهان متوازيان، والمستقيمان متوازيان أو منطبقان",
              "## ثانيًا: اختبار نقطة",
              "هل $(3,0,4)$ (من $\\vec{\\mathbf{r}}_2$) على $\\vec{\\mathbf{r}}_1$؟ من $x$: $1+2t=3$ ، إذن $t=1$",
              "عند $t=1$: $y=1-1=0$ ✔ ، لكن $z=0+3=3\\neq4$ ✘",
              "النقطة ليست على $\\vec{\\mathbf{r}}_1$ ، فلا نقطة مشتركة: المستقيمان متوازيان (غير منطبقين)"
            ],
            "wrong": [
              null,
              "المتقاطعان اتجاهاهما غير متوازيين، وهنا الاتجاهان متوازيان.",
              "المتخالفان اتجاهاهما غير متوازيين.",
              "المنطبقان يشتركان في كل النقاط، لكن $(3,0,4)$ ليست على $\\vec{\\mathbf{r}}_1$."
            ]
          }
        },
        {
          "id": "u6e1q9",
          "lesson": "u6-l2",
          "difficulty": "hard",
          "text": "إحداثيات نقطة تقاطع المستقيمين: $\\vec{\\mathbf{r}}_1=\\langle 2,1,0\\rangle+t\\langle 1,2,-1\\rangle$ و $\\vec{\\mathbf{r}}_2=\\langle 7,4,0\\rangle+s\\langle 3,-1,2\\rangle$ هي:",
          "options": [
            "$(4,\\,5,\\,-2)$",
            "$(7,\\,4,\\,0)$",
            "$(3,\\,3,\\,-1)$",
            "$(1,\\,6,\\,-4)$"
          ],
          "answer": 0,
          "solution": "نساوي الإحداثيات: $2+t=7+3s$ ، $1+2t=4-s$ ، $-t=2s$\nمن الثالثة: $t=-2s$ ، وبالتعويض في الأولى: $2-2s=7+3s \\Rightarrow s=-1,\\ t=2$\nتحقق في الثانية: $1+4=5=4+1$ ✔ ، ونقطة التقاطع $\\langle 2,1,0\\rangle+2\\langle 1,2,-1\\rangle=(4,\\,5,\\,-2)$",
          "explain": {
            "idea": "نقطة التقاطع تحقّق المعادلتين معًا ← نساوي الإحداثيات الثلاثة، نحلّ معادلتين، ونتحقّق في الثالثة.",
            "steps": [
              "## أولًا: المعادلات",
              "$x$: $2+t=7+3s$ ، $y$: $1+2t=4-s$ ، $z$: $-t=2s$",
              "## ثانيًا: الحلّ",
              "من $z$: $t=-2s$",
              "نعوّض في $x$: $2-2s=7+3s$ ، أي $-5=5s$ ، إذن $s=-1$ و $t=2$",
              "تحقّق في $y$: $1+2(2)=5$ و $4-(-1)=5$ ✔",
              "## ثالثًا: النقطة",
              "نعوّض $t=2$ في $\\vec{\\mathbf{r}}_1$: $(2+2,\\ 1+4,\\ 0-2)=(4,5,-2)$"
            ],
            "wrong": [
              null,
              "هذه نقطة على $\\vec{\\mathbf{r}}_2$ ($s=0$) لكنها ليست على $\\vec{\\mathbf{r}}_1$.",
              "هذه نقطة على $\\vec{\\mathbf{r}}_1$ ($t=1$) لكنها ليست على $\\vec{\\mathbf{r}}_2$.",
              "هذه نقطة على $\\vec{\\mathbf{r}}_2$ ($s=-2$) لكنها ليست على $\\vec{\\mathbf{r}}_1$."
            ],
            "tip": "نقطة التقاطع يجب أن تقع على المستقيمين؛ أغلب البدائل الخاطئة نقاط على مستقيم واحد فقط."
          }
        },
        {
          "id": "u6e1q10",
          "lesson": "u6-l3",
          "difficulty": "easy",
          "text": "إذا كان المتجهان: $\\vec{\\mathbf{u}}=\\langle 3,\\,-1,\\,2\\rangle$ و $\\vec{\\mathbf{v}}=\\langle 1,\\,4,\\,k\\rangle$ متعامدين، فإنّ قيمة $k$ هي:",
          "options": [
            "$\\frac{1}{2}$",
            "$-\\frac{1}{2}$",
            "$2$",
            "$\\frac{7}{2}$"
          ],
          "answer": 0,
          "solution": "المتجهان متعامدان إذا كان $\\vec{\\mathbf{u}}\\cdot\\vec{\\mathbf{v}}=0$: $3-4+2k=0 \\Rightarrow k=\\frac12$",
          "explain": {
            "idea": "التعامد ⟺ الضرب القياسي صفر.",
            "steps": [
              "الضرب القياسي: $\\langle a_1,a_2,a_3\\rangle\\cdot\\langle b_1,b_2,b_3\\rangle=a_1b_1+a_2b_2+a_3b_3$ ، وأيضًا $\\vec{\\mathbf{u}}\\cdot\\vec{\\mathbf{v}}=|\\vec{\\mathbf{u}}||\\vec{\\mathbf{v}}|\\cos\\theta$ ، والمتجهان متعامدان إذا كان ضربهما القياسي صفرًا",
              "$\\vec{\\mathbf{u}}\\cdot\\vec{\\mathbf{v}}=3(1)+(-1)(4)+2k=3-4+2k=2k-1$",
              "$2k-1=0$ ، إذن $k=\\frac12$"
            ],
            "wrong": [
              null,
              "خطأ إشارة: $2k=1$.",
              "من $2k=1$ تكون $k=\\frac12$ لا $2$.",
              "$(-1)(4)=-4$ لا $+4$: تحقّقي $3+4+2\\left(\\frac72\\right)\\neq0$."
            ]
          }
        },
        {
          "id": "u6e1q11",
          "lesson": "u6-l3",
          "difficulty": "medium",
          "text": "إذا كان: $\\vec{\\mathbf{a}}=\\langle 2,\\,1,\\,-1\\rangle$ ، $\\vec{\\mathbf{b}}=\\langle 1,\\,-1,\\,2\\rangle$ ، فإنّ قياس الزاوية بين المتجهين $(\\vec{\\mathbf{a}}-\\vec{\\mathbf{b}})$ و $(\\vec{\\mathbf{a}}+\\vec{\\mathbf{b}})$ هو:",
          "options": [
            "$\\frac{\\pi}{2}$",
            "$\\frac{\\pi}{3}$",
            "$\\frac{\\pi}{4}$",
            "$\\frac{\\pi}{6}$"
          ],
          "answer": 0,
          "solution": "$\\vec{\\mathbf{a}}-\\vec{\\mathbf{b}}=\\langle 1,2,-3\\rangle$ ، $\\vec{\\mathbf{a}}+\\vec{\\mathbf{b}}=\\langle 3,0,1\\rangle$\nالضرب القياسي $=3+0-3=0$ ، إذن الزاوية $\\frac{\\pi}{2}$\n(ملاحظة: $(\\vec{\\mathbf{a}}-\\vec{\\mathbf{b}})\\cdot(\\vec{\\mathbf{a}}+\\vec{\\mathbf{b}})=|\\vec{\\mathbf{a}}|^2-|\\vec{\\mathbf{b}}|^2=6-6=0$)",
          "explain": {
            "idea": "نحسب المتجهين، ثم ضربهما القياسي؛ إذا كان صفرًا فالزاوية قائمة دون حاجة لحساب المقادير.",
            "steps": [
              "$\\vec{\\mathbf{a}}-\\vec{\\mathbf{b}}=\\langle 2-1,\\ 1+1,\\ -1-2\\rangle=\\langle 1,2,-3\\rangle$",
              "$\\vec{\\mathbf{a}}+\\vec{\\mathbf{b}}=\\langle 3,0,1\\rangle$",
              "الضرب القياسي: $1(3)+2(0)+(-3)(1)=3+0-3=0$",
              "$\\cos\\theta=0$ ، إذن $\\theta=\\frac{\\pi}{2}$",
              "## ملاحظة",
              "$(\\vec{\\mathbf{a}}-\\vec{\\mathbf{b}})\\cdot(\\vec{\\mathbf{a}}+\\vec{\\mathbf{b}})=|\\vec{\\mathbf{a}}|^2-|\\vec{\\mathbf{b}}|^2=6-6=0$ ، لأن للمتجهين المقدار نفسه"
            ],
            "wrong": [
              null,
              "$\\cos\\frac{\\pi}{3}=\\frac12$ ، لكن الضرب القياسي صفر فجيب التمام صفر.",
              "$\\cos\\frac{\\pi}{4}\\neq0$؛ الضرب القياسي صفر.",
              "$\\cos\\frac{\\pi}{6}\\neq0$؛ الضرب القياسي صفر."
            ]
          }
        },
        {
          "id": "u6e1q12",
          "lesson": "u6-l3",
          "difficulty": "hard",
          "text": "إذا كان $ABC$ مثلثًا فيه: $\\overrightarrow{BA}=\\langle 2,\\,-1,\\,2\\rangle$ ، $\\overrightarrow{BC}=\\langle 4,\\,4,\\,-2\\rangle$ ، فإنّ مساحته بالوحدات المربعة تساوي:",
          "options": [
            "$9$",
            "$18$",
            "$6$",
            "$12$"
          ],
          "answer": 0,
          "solution": "$\\overrightarrow{BA}\\cdot\\overrightarrow{BC}=8-4-4=0$ ، إذن الزاوية $B$ قائمة\n$|\\overrightarrow{BA}|=3$ ، $|\\overrightarrow{BC}|=\\sqrt{16+16+4}=6$ ، والمساحة $=\\frac12(3)(6)=9$",
          "explain": {
            "idea": "نحسب الضرب القياسي للضلعين الخارجين من $B$: إذا كان صفرًا فالزاوية $B$ قائمة، والمساحة $\\frac12$ × حاصل ضرب الضلعين.",
            "steps": [
              "## أولًا: هل الزاوية قائمة؟",
              "$\\overrightarrow{BA}\\cdot\\overrightarrow{BC}=2(4)+(-1)(4)+2(-2)=8-4-4=0$ ، فالزاوية $B$ قائمة",
              "## ثانيًا: الضلعان",
              "$|\\overrightarrow{BA}|=\\sqrt{4+1+4}=3$ ، $|\\overrightarrow{BC}|=\\sqrt{16+16+4}=6$",
              "## ثالثًا: المساحة",
              "مساحة المثلث القائم نصف حاصل ضرب ضلعي القائمة: $\\frac12\\times3\\times6=9$"
            ],
            "wrong": [
              null,
              "نُسي العامل $\\frac12$؛ $18$ مساحة المستطيل.",
              "$6$ طول أحد الضلعين، لا المساحة.",
              "تحقّقي: $\\frac12\\times3\\times6=9$."
            ]
          }
        }
      ]
    },
    {
      "id": "u6-e2",
      "title": "الاختبار الثاني",
      "questions": [
        {
          "id": "u6e2q1",
          "lesson": "u6-l1",
          "difficulty": "easy",
          "text": "إذا كان: $\\vec{\\mathbf{v}}=\\langle 1,\\,-2,\\,4\\rangle$ ، $\\vec{\\mathbf{w}}=\\langle 3,\\,0,\\,-1\\rangle$ ، فإنّ $3\\vec{\\mathbf{v}}-2\\vec{\\mathbf{w}}$ يساوي:",
          "options": [
            "$\\langle -3,\\,-6,\\,14\\rangle$",
            "$\\langle -3,\\,-6,\\,10\\rangle$",
            "$\\langle 9,\\,-6,\\,10\\rangle$",
            "$\\langle -3,\\,6,\\,14\\rangle$"
          ],
          "answer": 0,
          "solution": "$3\\vec{\\mathbf{v}}=\\langle 3,-6,12\\rangle$ ، $2\\vec{\\mathbf{w}}=\\langle 6,0,-2\\rangle$ ، الفرق $\\langle -3,\\,-6,\\,14\\rangle$",
          "explain": {
            "idea": "ضرب متجه في عدد يضرب كل مركبة، والطرح مركبة مركبة.",
            "steps": [
              "$3\\vec{\\mathbf{v}}=\\langle 3,\\ -6,\\ 12\\rangle$",
              "$2\\vec{\\mathbf{w}}=\\langle 6,\\ 0,\\ -2\\rangle$",
              "$3\\vec{\\mathbf{v}}-2\\vec{\\mathbf{w}}=\\langle 3-6,\\ -6-0,\\ 12-(-2)\\rangle=\\langle -3,\\ -6,\\ 14\\rangle$"
            ],
            "wrong": [
              null,
              "المركبة الثالثة: $12-(-2)=12+2=14$ لا $10$.",
              "المركبة الأولى: $3-6=-3$ ، والثالثة $14$.",
              "المركبة الثانية: $-6-0=-6$."
            ]
          }
        },
        {
          "id": "u6e2q2",
          "lesson": "u6-l1",
          "difficulty": "medium",
          "text": "إذا كان المتجه $\\vec{\\mathbf{u}}=\\langle a,\\,6,\\,-3\\rangle$ يوازي المتجه $\\vec{\\mathbf{v}}=\\langle 2,\\,-4,\\,b\\rangle$ ، فإنّ قيمة $a+b$ هي:",
          "options": [
            "$-1$",
            "$1$",
            "$-5$",
            "$5$"
          ],
          "answer": 0,
          "solution": "المتجهان متوازيان: $\\vec{\\mathbf{u}}=k\\vec{\\mathbf{v}}$ ، من المركبة الثانية: $6=-4k \\Rightarrow k=-\\frac32$\n$a=-\\frac32(2)=-3$ ، و $-3=-\\frac32b \\Rightarrow b=2$ ، إذن $a+b=-1$",
          "explain": {
            "idea": "التوازي ⟺ أحد المتجهين مضاعف للآخر. نجد المضاعف $k$ من مركبة معلومة في المتجهين.",
            "steps": [
              "المتجهان متوازيان إذا كان أحدهما مضاعفًا للآخر: $\\vec{\\mathbf{u}}=k\\vec{\\mathbf{v}}$ لعدد حقيقي $k$",
              "$\\langle a,6,-3\\rangle=k\\langle 2,-4,b\\rangle$",
              "المركبة الثانية معلومة في الاثنين: $6=-4k$ ، إذن $k=-\\frac32$",
              "الأولى: $a=-\\frac32\\times2=-3$",
              "الثالثة: $-3=-\\frac32b$ ، إذن $b=2$",
              "$a+b=-3+2=-1$"
            ],
            "wrong": [
              null,
              "تنتج من أخذ $k=+\\frac32$ (فتصبح $a=3$ و $b=-2$)؛ لكن $6=k(-4)$ يعطي $k$ سالبًا.",
              "$b=+2$: من $-3=-\\frac32b$.",
              "$a=-\\frac32\\times2=-3$ سالب، فـ $a+b=-1$."
            ]
          }
        },
        {
          "id": "u6e2q3",
          "lesson": "u6-l1",
          "difficulty": "medium",
          "text": "إذا كانت $A,\\ B,\\ C$ ثلاث نقاط في الفضاء، وكان: $\\overrightarrow{AB}=\\langle 2,\\,a-1,\\,4\\rangle$ ، $\\overrightarrow{AC}=\\langle 3,\\,6,\\,6\\rangle$ ، فإنّ قيمة $a$ التي تجعل النقاط $A,\\ B,\\ C$ تقع على استقامة واحدة هي:",
          "options": [
            "$5$",
            "$4$",
            "$3$",
            "$9$"
          ],
          "answer": 0,
          "solution": "تقع النقاط على استقامة واحدة إذا توازى $\\overrightarrow{AB}$ و $\\overrightarrow{AC}$: $\\overrightarrow{AB}=\\frac23\\overrightarrow{AC}$ (من المركبتين الأولى والثالثة)\n$a-1=\\frac23(6)=4 \\Rightarrow a=5$",
          "explain": {
            "idea": "ثلاث نقاط على استقامة واحدة ⟺ $\\overrightarrow{AB}$ و $\\overrightarrow{AC}$ متوازيان (ويشتركان في $A$).",
            "steps": [
              "المتجهان متوازيان إذا كان أحدهما مضاعفًا للآخر: $\\vec{\\mathbf{u}}=k\\vec{\\mathbf{v}}$ لعدد حقيقي $k$",
              "$\\langle 2,\\ a-1,\\ 4\\rangle=k\\langle 3,6,6\\rangle$",
              "الأولى: $2=3k$ ، إذن $k=\\frac23$ ، والثالثة تؤكّد: $\\frac23\\times6=4$ ✔",
              "الثانية: $a-1=\\frac23\\times6=4$ ، إذن $a=5$"
            ],
            "wrong": [
              null,
              "$4$ هي $a-1$ ، و $a=5$.",
              "تحقّقي: $a=3$ يعطي $\\langle 2,2,4\\rangle$ ، وليس مضاعفًا لـ $\\langle 3,6,6\\rangle$.",
              "تحقّقي: $a=9$ يعطي $\\langle 2,8,4\\rangle$ ، وليس مضاعفًا لـ $\\langle 3,6,6\\rangle$."
            ]
          }
        },
        {
          "id": "u6e2q4",
          "lesson": "u6-l1",
          "difficulty": "hard",
          "text": "في متوازي المستطيلات الآتي، أحد رؤوسه نقطة الأصل $O$ ، وأحرفه $\\overline{OP}$ و $\\overline{OR}$ و $\\overline{OS}$ على المحاور $x$ و $y$ و $z$ على الترتيب. إذا كانت إحداثيات الرأس $U$ هي $(4,\\,6,\\,3)$ ، فإنّ إحداثيات نقطة منتصف القطعة $\\overline{PV}$ هي:",
          "options": [
            "$(2,\\,3,\\,\\frac{3}{2})$",
            "$(2,\\,3,\\,3)$",
            "$(4,\\,6,\\,3)$",
            "$(2,\\,0,\\,\\frac{3}{2})$"
          ],
          "answer": 0,
          "solution": "من الشكل: $P(4,0,0)$ على المحور $x$ ، و $V(0,6,3)$ (فوق $R(0,6,0)$ بارتفاع $3$)\nمنتصف $\\overline{PV}$: $\\left(\\dfrac{4+0}{2},\\ \\dfrac{0+6}{2},\\ \\dfrac{0+3}{2}\\right)=\\left(2,\\,3,\\,\\frac32\\right)$",
          "explain": {
            "idea": "إحداثيات الرأس $U$ تعطي أبعاد متوازي المستطيلات، ومنها إحداثيات $P$ و $V$ ، ثم المنتصف.",
            "steps": [
              "## أولًا: الأبعاد",
              "$U(4,6,3)$: الطول على $x$ يساوي $4$ ، وعلى $y$ يساوي $6$ ، وعلى $z$ يساوي $3$",
              "## ثانيًا: الرأسان",
              "$P$ على المحور $x$: $P(4,0,0)$",
              "$V$ فوق $R$ ($R$ على المحور $y$): $V(0,6,3)$",
              "## ثالثًا: المنتصف",
              "منتصف القطعة بين نقطتين = متوسط إحداثياتهما: $\\left(\\frac{x_1+x_2}{2},\\frac{y_1+y_2}{2},\\frac{z_1+z_2}{2}\\right)$",
              "$\\left(\\frac{4+0}{2},\\ \\frac{0+6}{2},\\ \\frac{0+3}{2}\\right)=\\left(2,\\ 3,\\ \\frac32\\right)$"
            ],
            "wrong": [
              null,
              "المركبة الثالثة: $\\frac{0+3}{2}=\\frac32$؛ نُسيت القسمة على $2$.",
              "هذه إحداثيات $U$ نفسه.",
              "المركبة الثانية: $V$ لها $y=6$ ، فالمنتصف $y=3$."
            ]
          },
          "figure": "fig/u6e2q4.svg"
        },
        {
          "id": "u6e2q5",
          "lesson": "u6-l1",
          "difficulty": "medium",
          "text": "إذا كان: $\\vec{\\mathbf{v}}=\\langle c,\\,-2,\\,4\\rangle$ ، وكان: $|\\vec{\\mathbf{v}}|=6$ ، فإنّ قيم $c$ هي:",
          "options": [
            "$\\pm 4$",
            "$4$",
            "$\\pm 2\\sqrt{14}$",
            "$\\pm 16$"
          ],
          "answer": 0,
          "solution": "$\\sqrt{c^2+4+16}=6 \\Rightarrow c^2+20=36 \\Rightarrow c^2=16 \\Rightarrow c=\\pm4$",
          "explain": {
            "idea": "مربّع المقدار = مجموع مربّعات المركبات ← معادلة في $c^2$ ، ولها حلّان لأن لا شرط على إشارة $c$.",
            "steps": [
              "مقدار المتجه $\\langle a,b,c\\rangle$ هو $\\sqrt{a^2+b^2+c^2}$",
              "$\\sqrt{c^2+(-2)^2+4^2}=6$ ، نربّع: $c^2+4+16=36$",
              "$c^2=36-20=16$ ، إذن $c=\\pm4$",
              "لا يوجد شرط على إشارة $c$ ، فالقيمتان مقبولتان"
            ],
            "wrong": [
              null,
              "$c=-4$ أيضًا يحقّق: $16+4+16=36$.",
              "تنتج من $c^2=36+20$؛ الصحيح $c^2=36-20$.",
              "$16$ هي قيمة $c^2$ لا $c$."
            ]
          }
        },
        {
          "id": "u6e2q6",
          "lesson": "u6-l2",
          "difficulty": "easy",
          "text": "المعادلة المتجهة للمستقيم المارّ بالنقطتين: $A(3,\\,-1,\\,2)$ و $B(5,\\,2,\\,-2)$ هي:",
          "options": [
            "$\\vec{\\mathbf{r}}=\\langle 3,\\,-1,\\,2\\rangle+t\\langle 2,\\,3,\\,-4\\rangle$",
            "$\\vec{\\mathbf{r}}=\\langle 3,\\,-1,\\,2\\rangle+t\\langle 5,\\,2,\\,-2\\rangle$",
            "$\\vec{\\mathbf{r}}=\\langle 2,\\,3,\\,-4\\rangle+t\\langle 3,\\,-1,\\,2\\rangle$",
            "$\\vec{\\mathbf{r}}=\\langle 3,\\,-1,\\,2\\rangle+t\\langle 8,\\,1,\\,0\\rangle$"
          ],
          "answer": 0,
          "solution": "متجه الاتجاه $\\overrightarrow{AB}=\\langle 5-3,\\,2+1,\\,-2-2\\rangle=\\langle 2,\\,3,\\,-4\\rangle$ ، والمستقيم يمرّ بـ $A$:\n$\\vec{\\mathbf{r}}=\\langle 3,-1,2\\rangle+t\\langle 2,3,-4\\rangle$",
          "explain": {
            "idea": "مستقيم يمرّ بنقطتين ← متجه الاتجاه هو $\\overrightarrow{AB}$ ، والنقطة $A$ (أو $B$).",
            "steps": [
              "المعادلة المتجهة للمستقيم: $\\vec{\\mathbf{r}}=\\vec{\\mathbf{r}}_0+t\\vec{\\mathbf{v}}$ ، حيث $\\vec{\\mathbf{r}}_0$ متجه موقع نقطة على المستقيم، و $\\vec{\\mathbf{v}}$ متجه اتجاهه",
              "$\\overrightarrow{AB}=\\langle 5-3,\\ 2-(-1),\\ -2-2\\rangle=\\langle 2,3,-4\\rangle$",
              "$\\vec{\\mathbf{r}}=\\langle 3,-1,2\\rangle+t\\langle 2,3,-4\\rangle$"
            ],
            "wrong": [
              null,
              "متجه الاتجاه هنا متجه موقع $B$ ، وليس متجهًا بين النقطتين.",
              "النقطة ومتجه الاتجاه مبدّلان.",
              "متجه الاتجاه هنا $A+B$ لا $B-A$."
            ]
          }
        },
        {
          "id": "u6e2q7",
          "lesson": "u6-l2",
          "difficulty": "medium",
          "text": "إذا كانت: $\\vec{\\mathbf{r}}=\\langle 6,\\,-2,\\,5\\rangle+t\\langle 3,\\,1,\\,-2\\rangle$ معادلة متجهة للمستقيم $l$ ، فإنّ قيمة $t$ التي تُقابل نقطة تقاطع المستقيم $l$ مع المستوى $yz$ هي:",
          "options": [
            "$-2$",
            "$2$",
            "$\\frac{5}{2}$",
            "$-3$"
          ],
          "answer": 0,
          "solution": "على المستوى $yz$ يكون $x=0$: $6+3t=0 \\Rightarrow t=-2$",
          "explain": {
            "idea": "المستوى $yz$ هو المستوى الذي فيه $x=0$ ← نساوي المركبة الأولى بالصفر.",
            "steps": [
              "نقاط المستقيم: $(6+3t,\\ -2+t,\\ 5-2t)$",
              "على المستوى $yz$: $x=0$ ، أي $6+3t=0$ ، إذن $t=-2$"
            ],
            "wrong": [
              null,
              "خطأ إشارة: $3t=-6$.",
              "هذه قيمة $t$ عند $z=0$ ، أي التقاطع مع المستوى $xy$.",
              "تحقّقي: $t=-3$ يعطي $x=-3\\neq0$."
            ],
            "tip": "المستوى $xy$: $z=0$ ، المستوى $xz$: $y=0$ ، المستوى $yz$: $x=0$ (الإحداثي الغائب من الاسم يساوي صفرًا)."
          }
        },
        {
          "id": "u6e2q8",
          "lesson": "u6-l2",
          "difficulty": "hard",
          "text": "العلاقة بين المستقيمين: $\\vec{\\mathbf{r}}_1=\\langle 1,0,2\\rangle+t\\langle 1,1,1\\rangle$ و $\\vec{\\mathbf{r}}_2=\\langle 2,3,1\\rangle+s\\langle 2,-1,1\\rangle$ هي أنّهما:",
          "options": [
            "متخالفان",
            "متوازيان",
            "متقاطعان",
            "منطبقان"
          ],
          "answer": 0,
          "solution": "متجها الاتجاه غير متوازيين، فالمستقيمان إمّا متقاطعان أو متخالفان. نساوي الإحداثيات:\n$1+t=2+2s$ ، $t=3-s$ ، $2+t=1+s$\nمن الثانية والثالثة: $2+3-s=1+s \\Rightarrow s=2,\\ t=1$ ، وبالتعويض في الأولى: $2\\ne6$\nلا يوجد حلّ مشترك، إذن المستقيمان متخالفان.",
          "explain": {
            "idea": "اتجاهان غير متوازيين ← متقاطعان أو متخالفان، فنحلّ معادلات الإحداثيات.",
            "steps": [
              "العلاقة بين مستقيمين: إذا توازى متجها الاتجاه فهما متوازيان أو منطبقان (نختبر نقطة من أحدهما على الآخر)، وإلّا فهما متقاطعان أو متخالفان (نحلّ معادلات تساوي الإحداثيات)",
              "## أولًا: التوازي",
              "$\\langle 1,1,1\\rangle$ و $\\langle 2,-1,1\\rangle$: لو كان $\\langle 2,-1,1\\rangle=k\\langle 1,1,1\\rangle$ لكانت كل المركبات متساوية، وهذا غير صحيح ← غير متوازيين",
              "## ثانيًا: البحث عن نقطة مشتركة",
              "$x$: $1+t=2+2s$ ، $y$: $t=3-s$ ، $z$: $2+t=1+s$",
              "نعوّض $t=3-s$ في $z$: $5-s=1+s$ ، إذن $s=2$ و $t=1$",
              "نختبر $x$: الطرف الأيسر $1+1=2$ والأيمن $2+4=6$ ، و $2\\neq6$",
              "لا حلّ مشترك وهما غير متوازيين ← متخالفان"
            ],
            "wrong": [
              null,
              "متجها الاتجاه غير متوازيين.",
              "قيم $t$ و $s$ لا تحقّق المعادلة الثالثة، فلا نقطة مشتركة.",
              "المنطبقان متوازيان، وهذان غير متوازيين."
            ]
          }
        },
        {
          "id": "u6e2q9",
          "lesson": "u6-l3",
          "difficulty": "hard",
          "text": "إذا كانت: $\\vec{\\mathbf{r}}=\\langle 1,\\,0,\\,2\\rangle+t\\langle 1,\\,2,\\,-1\\rangle$ معادلة متجهة للمستقيم $l$ ، والنقطة $P(4,\\,5,\\,3)$ غير واقعة عليه، فإنّ إحداثيات مسقط العمود من النقطة $P$ على المستقيم $l$ هي:",
          "options": [
            "$(3,\\,4,\\,0)$",
            "$(1,\\,0,\\,2)$",
            "$(2,\\,2,\\,1)$",
            "$(5,\\,8,\\,-2)$"
          ],
          "answer": 0,
          "solution": "نفرض المسقط $Q=(1+t,\\ 2t,\\ 2-t)$ ، فيكون $\\overrightarrow{PQ}=\\langle t-3,\\ 2t-5,\\ -t-1\\rangle$ عموديًّا على $\\langle 1,2,-1\\rangle$:\n$(t-3)+2(2t-5)-(-t-1)=0 \\Rightarrow 6t-12=0 \\Rightarrow t=2$ ، إذن $Q=(3,\\,4,\\,0)$",
          "explain": {
            "idea": "مسقط العمود من $P$ على مستقيم هو النقطة $Q$ عليه التي تجعل $\\overrightarrow{PQ}$ عموديًّا على متجه اتجاه المستقيم (ضربهما القياسي صفر). نكتب $Q$ بدلالة $t$ ، ونطبّق شرط التعامد.",
            "steps": [
              "## أولًا: النقطة العامة",
              "$Q=(1+t,\\ 2t,\\ 2-t)$",
              "$\\overrightarrow{PQ}=Q-P=\\langle t-3,\\ 2t-5,\\ -t-1\\rangle$",
              "## ثانيًا: شرط التعامد",
              "$\\overrightarrow{PQ}\\cdot\\langle 1,2,-1\\rangle=(t-3)+2(2t-5)-(-t-1)=t-3+4t-10+t+1=6t-12$",
              "$6t-12=0$ ، إذن $t=2$",
              "## ثالثًا: المسقط",
              "$Q=(3,\\ 4,\\ 0)$ ، وتحقّق: $\\overrightarrow{PQ}=\\langle -1,-1,-3\\rangle$ و $-1-2+3=0$ ✔"
            ],
            "wrong": [
              null,
              "نقطة على المستقيم ($t=0$) لكن $\\overrightarrow{PQ}\\cdot\\langle 1,2,-1\\rangle=-12\\neq0$.",
              "نقطة على المستقيم ($t=1$) لكن الضرب القياسي $-6\\neq0$.",
              "نقطة على المستقيم ($t=4$) لكن الضرب القياسي $12\\neq0$."
            ]
          }
        },
        {
          "id": "u6e2q10",
          "lesson": "u6-l3",
          "difficulty": "easy",
          "text": "إذا كان: $|\\vec{\\mathbf{a}}|=4$ ، $|\\vec{\\mathbf{b}}|=5$ ، وقياس الزاوية بينهما $120^\\circ$ ، فإنّ $\\vec{\\mathbf{a}}\\cdot\\vec{\\mathbf{b}}$ يساوي:",
          "options": [
            "$-10$",
            "$10$",
            "$-10\\sqrt{3}$",
            "$20$"
          ],
          "answer": 0,
          "solution": "$\\vec{\\mathbf{a}}\\cdot\\vec{\\mathbf{b}}=|\\vec{\\mathbf{a}}||\\vec{\\mathbf{b}}|\\cos\\theta=4(5)\\cos120^\\circ=20\\left(-\\frac12\\right)=-10$",
          "explain": {
            "idea": "معطى المقداران والزاوية ← الصيغة الهندسية للضرب القياسي: $|\\vec{\\mathbf{a}}||\\vec{\\mathbf{b}}|\\cos\\theta$.",
            "steps": [
              "$\\vec{\\mathbf{a}}\\cdot\\vec{\\mathbf{b}}=|\\vec{\\mathbf{a}}||\\vec{\\mathbf{b}}|\\cos\\theta=4\\times5\\times\\cos120^\\circ$",
              "$120^\\circ$ في الربع الثاني، وزاوية الإسناد $60^\\circ$ ، و $\\cos$ سالب في الربع الثاني: $\\cos120^\\circ=-\\frac12$",
              "$20\\times\\left(-\\frac12\\right)=-10$"
            ],
            "wrong": [
              null,
              "$\\cos120^\\circ$ سالب (الربع الثاني).",
              "هذا باستعمال $\\cos150^\\circ=-\\frac{\\sqrt3}{2}$؛ الزاوية $120^\\circ$.",
              "نُسي الضرب في $\\cos\\theta$."
            ]
          }
        },
        {
          "id": "u6e2q11",
          "lesson": "u6-l3",
          "difficulty": "medium",
          "text": "إذا كان قياس الزاوية بين $\\vec{\\mathbf{a}}$ و $\\vec{\\mathbf{b}}$ هو $60^\\circ$ ، وكان: $|\\vec{\\mathbf{a}}|=6$ ، $\\vec{\\mathbf{a}}\\cdot\\vec{\\mathbf{b}}=12$ ، فإنّ مقدار $\\vec{\\mathbf{b}}$ هو:",
          "options": [
            "$4$",
            "$2$",
            "$8$",
            "$\\frac{4\\sqrt{3}}{3}$"
          ],
          "answer": 0,
          "solution": "$12=6|\\vec{\\mathbf{b}}|\\cos60^\\circ=3|\\vec{\\mathbf{b}}| \\Rightarrow |\\vec{\\mathbf{b}}|=4$",
          "explain": {
            "idea": "نعوّض المعطيات في $\\vec{\\mathbf{a}}\\cdot\\vec{\\mathbf{b}}=|\\vec{\\mathbf{a}}||\\vec{\\mathbf{b}}|\\cos\\theta$ ونحلّ لـ $|\\vec{\\mathbf{b}}|$.",
            "steps": [
              "$12=6\\times|\\vec{\\mathbf{b}}|\\times\\cos60^\\circ$",
              "$\\cos60^\\circ=\\frac12$ ، فـ $12=6\\times\\frac12\\times|\\vec{\\mathbf{b}}|=3|\\vec{\\mathbf{b}}|$",
              "$|\\vec{\\mathbf{b}}|=\\frac{12}{3}=4$"
            ],
            "wrong": [
              null,
              "نُسي العامل $\\cos60^\\circ=\\frac12$: $\\frac{12}{6}=2$.",
              "تحقّقي: $6\\times8\\times\\frac12=24\\neq12$.",
              "هذا باستعمال $\\cos30^\\circ=\\frac{\\sqrt3}{2}$؛ الزاوية $60^\\circ$."
            ]
          }
        },
        {
          "id": "u6e2q12",
          "lesson": "u6-l3",
          "difficulty": "medium",
          "text": "إذا كان المتجه: $\\vec{\\mathbf{v}}=3\\hat{i}+c\\hat{j}+2\\hat{k}$ يُعامد المتجه: $\\vec{\\mathbf{w}}=2\\hat{i}-\\hat{j}+d\\hat{k}$ ، حيث $c,\\ d$ ثابتان، فإنّ $c-2d$ تساوي:",
          "options": [
            "$6$",
            "$-6$",
            "$3$",
            "$-3$"
          ],
          "answer": 0,
          "solution": "$\\vec{\\mathbf{v}}\\cdot\\vec{\\mathbf{w}}=6-c+2d=0 \\Rightarrow c-2d=6$",
          "explain": {
            "idea": "التعامد ← الضرب القياسي صفر، فتظهر علاقة بين $c$ و $d$ نرتّبها على صورة المطلوب.",
            "steps": [
              "الضرب القياسي: $\\langle a_1,a_2,a_3\\rangle\\cdot\\langle b_1,b_2,b_3\\rangle=a_1b_1+a_2b_2+a_3b_3$ ، وأيضًا $\\vec{\\mathbf{u}}\\cdot\\vec{\\mathbf{v}}=|\\vec{\\mathbf{u}}||\\vec{\\mathbf{v}}|\\cos\\theta$ ، والمتجهان متعامدان إذا كان ضربهما القياسي صفرًا",
              "$\\langle 3,c,2\\rangle\\cdot\\langle 2,-1,d\\rangle=6-c+2d$",
              "$6-c+2d=0$ ، ننقل: $6=c-2d$",
              "إذن $c-2d=6$"
            ],
            "wrong": [
              null,
              "عند نقل $-c+2d$ يصبح $c-2d=6$ (موجب).",
              "تحقّقي: الحدّ الثابت $3\\times2=6$.",
              "تحقّقي: الحدّ الثابت $6$ ، والعلاقة $c-2d=6$."
            ]
          }
        }
      ]
    },
    {
      "id": "u6-e3",
      "title": "الاختبار الثالث",
      "questions": [
        {
          "id": "u6e3q1",
          "lesson": "u6-l1",
          "difficulty": "easy",
          "text": "إحداثيات نقطة منتصف القطعة المستقيمة الواصلة بين النقطتين: $A(-2,\\,5,\\,1)$ و $B(4,\\,-1,\\,7)$ هي:",
          "options": [
            "$(1,\\,2,\\,4)$",
            "$(2,\\,4,\\,8)$",
            "$(3,\\,-3,\\,3)$",
            "$(-3,\\,3,\\,-3)$"
          ],
          "answer": 0,
          "solution": "$M=\\left(\\dfrac{-2+4}{2},\\ \\dfrac{5-1}{2},\\ \\dfrac{1+7}{2}\\right)=(1,\\,2,\\,4)$",
          "explain": {
            "idea": "منتصف القطعة بين نقطتين = متوسط إحداثياتهما: $\\left(\\frac{x_1+x_2}{2},\\frac{y_1+y_2}{2},\\frac{z_1+z_2}{2}\\right)$.",
            "steps": [
              "$x$: $\\frac{-2+4}{2}=1$",
              "$y$: $\\frac{5+(-1)}{2}=2$",
              "$z$: $\\frac{1+7}{2}=4$",
              "المنتصف $(1,2,4)$"
            ],
            "wrong": [
              null,
              "نُسيت القسمة على $2$ (هذا مجموع الإحداثيات).",
              "هذا $\\frac{B-A}{2}$ (نصف المتجه) لا المنتصف.",
              "هذا $\\frac{A-B}{2}$."
            ]
          }
        },
        {
          "id": "u6e3q2",
          "lesson": "u6-l1",
          "difficulty": "easy",
          "text": "إذا كانت: $A(3,\\,-2,\\,5)$ ، $B(-1,\\,4,\\,2)$ ، فإنّ الصورة الإحداثية للمتجه $\\overrightarrow{BA}$ هي:",
          "options": [
            "$\\langle 4,\\,-6,\\,3\\rangle$",
            "$\\langle -4,\\,6,\\,-3\\rangle$",
            "$\\langle 2,\\,2,\\,7\\rangle$",
            "$\\langle -2,\\,-2,\\,-7\\rangle$"
          ],
          "answer": 0,
          "solution": "$\\overrightarrow{BA}=A-B=\\langle 3+1,\\,-2-4,\\,5-2\\rangle=\\langle 4,\\,-6,\\,3\\rangle$ (لاحظ الترتيب: نهاية المتجه ناقص بدايته)",
          "explain": {
            "idea": "$\\overrightarrow{BA}$ يبدأ من $B$ وينتهي عند $A$ ← $A-B$ (النهاية − البداية).",
            "steps": [
              "المتجه من النقطة $A$ إلى النقطة $B$: $\\overrightarrow{AB}=B-A$ (إحداثيات النهاية ناقص إحداثيات البداية)",
              "$\\overrightarrow{BA}=A-B=\\langle 3-(-1),\\ -2-4,\\ 5-2\\rangle=\\langle 4,\\ -6,\\ 3\\rangle$"
            ],
            "wrong": [
              null,
              "هذا $\\overrightarrow{AB}=B-A$؛ الترتيب معكوس.",
              "هذا $A+B$؛ المتجه بين نقطتين فرق لا مجموع.",
              "هذا $-(A+B)$."
            ]
          }
        },
        {
          "id": "u6e3q3",
          "lesson": "u6-l1",
          "difficulty": "medium",
          "text": "$ABCD$ متوازي أضلاع، فيه: $A(2,\\,-1,\\,3)$ ، $B(5,\\,1,\\,0)$ ، $C(4,\\,4,\\,2)$. إحداثيات الرأس $D$ هي:",
          "options": [
            "$(1,\\,2,\\,5)$",
            "$(7,\\,6,\\,-1)$",
            "$(3,\\,-4,\\,1)$",
            "$(1,\\,2,\\,-5)$"
          ],
          "answer": 0,
          "solution": "في متوازي الأضلاع $\\overrightarrow{AD}=\\overrightarrow{BC}=\\langle -1,\\,3,\\,2\\rangle$\n$D=A+\\overrightarrow{BC}=(2-1,\\ -1+3,\\ 3+2)=(1,\\,2,\\,5)$",
          "explain": {
            "idea": "في متوازي الأضلاع $ABCD$ (الرؤوس بالترتيب) الضلعان المتقابلان متساويان ومتوازيان: $\\overrightarrow{AD}=\\overrightarrow{BC}$.",
            "steps": [
              "$\\overrightarrow{BC}=C-B=\\langle 4-5,\\ 4-1,\\ 2-0\\rangle=\\langle -1,3,2\\rangle$",
              "$D=A+\\overrightarrow{BC}=(2-1,\\ -1+3,\\ 3+2)=(1,2,5)$",
              "## تحقّق",
              "القطران ينصّف كلٌّ منهما الآخر: منتصف $\\overline{AC}$ هو $(3,1.5,2.5)$ ، ومنتصف $\\overline{BD}$ هو $\\left(\\frac{5+1}{2},\\frac{1+2}{2},\\frac{0+5}{2}\\right)=(3,1.5,2.5)$ ✔"
            ],
            "wrong": [
              null,
              "هذا $B+C-A$ ، أي الرأس المقابل لـ $A$؛ لكن في $ABCD$ الرأس المقابل لـ $A$ هو $C$.",
              "هذا $A+B-C$ ، ترتيب آخر للرؤوس.",
              "المركبة الثالثة: $3+2=5$ لا $-5$."
            ]
          }
        },
        {
          "id": "u6e3q4",
          "lesson": "u6-l1",
          "difficulty": "hard",
          "text": "في الشكل الآتي $OABC$ متوازي أضلاع، فيه: $\\overrightarrow{OA}=2\\vec{\\mathbf{a}}$ ، $\\overrightarrow{OC}=3\\vec{\\mathbf{c}}$. إذا كانت $M$ منتصف الضلع $\\overline{CB}$ ، وكانت $P$ نقطة على القطر $\\overline{OB}$ بحيث $OP:PB=2:1$ ، فإنّ المتجه $\\overrightarrow{PM}$ بدلالة $\\vec{\\mathbf{a}}$ و $\\vec{\\mathbf{c}}$ هو:",
          "options": [
            "$-\\frac{1}{3}\\vec{\\mathbf{a}}+\\vec{\\mathbf{c}}$",
            "$\\frac{1}{3}\\vec{\\mathbf{a}}-\\vec{\\mathbf{c}}$",
            "$\\frac{7}{3}\\vec{\\mathbf{a}}+5\\vec{\\mathbf{c}}$",
            "$-\\frac{1}{3}\\vec{\\mathbf{a}}+5\\vec{\\mathbf{c}}$"
          ],
          "answer": 0,
          "solution": "$\\overrightarrow{OM}=\\overrightarrow{OC}+\\frac12\\overrightarrow{CB}=3\\vec{\\mathbf{c}}+\\frac12(2\\vec{\\mathbf{a}})=\\vec{\\mathbf{a}}+3\\vec{\\mathbf{c}}$\n$\\overrightarrow{OP}=\\frac23\\overrightarrow{OB}=\\frac23(2\\vec{\\mathbf{a}}+3\\vec{\\mathbf{c}})=\\frac43\\vec{\\mathbf{a}}+2\\vec{\\mathbf{c}}$\n$\\overrightarrow{PM}=\\overrightarrow{OM}-\\overrightarrow{OP}=-\\frac13\\vec{\\mathbf{a}}+\\vec{\\mathbf{c}}$",
          "explain": {
            "idea": "$\\overrightarrow{PM}=\\overrightarrow{OM}-\\overrightarrow{OP}$ ← نعبّر عن كلٍّ منهما بدلالة $\\vec{\\mathbf{a}}$ و $\\vec{\\mathbf{c}}$.",
            "steps": [
              "## أولًا: أضلاع متوازي الأضلاع",
              "$\\overrightarrow{CB}=\\overrightarrow{OA}=2\\vec{\\mathbf{a}}$ (ضلعان متقابلان)",
              "$\\overrightarrow{OB}=\\overrightarrow{OA}+\\overrightarrow{AB}=2\\vec{\\mathbf{a}}+3\\vec{\\mathbf{c}}$",
              "## ثانيًا: OM",
              "$M$ منتصف $\\overline{CB}$: $\\overrightarrow{OM}=\\overrightarrow{OC}+\\frac12\\overrightarrow{CB}=3\\vec{\\mathbf{c}}+\\vec{\\mathbf{a}}$",
              "## ثالثًا: OP",
              "$OP:PB=2:1$ ، فـ $OP$ ثلثا $OB$: $\\overrightarrow{OP}=\\frac23(2\\vec{\\mathbf{a}}+3\\vec{\\mathbf{c}})=\\frac43\\vec{\\mathbf{a}}+2\\vec{\\mathbf{c}}$",
              "## رابعًا: PM",
              "$\\overrightarrow{PM}=(\\vec{\\mathbf{a}}+3\\vec{\\mathbf{c}})-\\left(\\frac43\\vec{\\mathbf{a}}+2\\vec{\\mathbf{c}}\\right)=-\\frac13\\vec{\\mathbf{a}}+\\vec{\\mathbf{c}}$"
            ],
            "wrong": [
              null,
              "هذا $\\overrightarrow{MP}$ (الاتجاه معكوس).",
              "هذا $\\overrightarrow{OM}+\\overrightarrow{OP}$؛ المتجه بين نقطتين فرق لا مجموع.",
              "معامل $\\vec{\\mathbf{c}}$: $3-2=1$ لا $3+2$."
            ]
          },
          "figure": "fig/u6e3q4.svg"
        },
        {
          "id": "u6e3q5",
          "lesson": "u6-l1",
          "difficulty": "medium",
          "text": "إذا وقعت النقاط: $P(1,\\,2,\\,3)$ ، $Q(3,\\,h,\\,7)$ ، $R(4,\\,8,\\,k)$ على مستقيم واحد، فإنّ قيمة $h+k$ هي:",
          "options": [
            "$15$",
            "$12$",
            "$9$",
            "$18$"
          ],
          "answer": 0,
          "solution": "$\\overrightarrow{PQ}=\\langle 2,\\,h-2,\\,4\\rangle$ ، $\\overrightarrow{PR}=\\langle 3,\\,6,\\,k-3\\rangle$ ، ويجب أن يكون $\\overrightarrow{PQ}=\\frac23\\overrightarrow{PR}$\n$h-2=4 \\Rightarrow h=6$ ، و $4=\\frac23(k-3) \\Rightarrow k=9$ ، إذن $h+k=15$",
          "explain": {
            "idea": "النقاط على مستقيم واحد ⟺ $\\overrightarrow{PQ}$ مضاعف لـ $\\overrightarrow{PR}$ ، ونجد المضاعف من المركبة الأولى.",
            "steps": [
              "$\\overrightarrow{PQ}=\\langle 2,\\ h-2,\\ 4\\rangle$ ، $\\overrightarrow{PR}=\\langle 3,\\ 6,\\ k-3\\rangle$",
              "المتجهان متوازيان إذا كان أحدهما مضاعفًا للآخر: $\\vec{\\mathbf{u}}=k\\vec{\\mathbf{v}}$ لعدد حقيقي $k$",
              "الأولى: $2=3m$ ، إذن $m=\\frac23$",
              "الثانية: $h-2=\\frac23\\times6=4$ ، إذن $h=6$",
              "الثالثة: $4=\\frac23(k-3)$ ، إذن $k-3=6$ و $k=9$",
              "$h+k=6+9=15$"
            ],
            "wrong": [
              null,
              "تحقّقي: $h=6$ و $k=9$.",
              "$9$ هي $k$ وحدها.",
              "تحقّقي: من $4=\\frac23(k-3)$ تكون $k=9$ لا $12$."
            ]
          }
        },
        {
          "id": "u6e3q6",
          "lesson": "u6-l2",
          "difficulty": "easy",
          "text": "النقطة الواقعة على المستقيم: $\\vec{\\mathbf{r}}=\\langle -1,\\,4,\\,2\\rangle+t\\langle 2,\\,-1,\\,3\\rangle$ ، والإحداثي $y$ لها يساوي $1$ ، هي:",
          "options": [
            "$(5,\\,1,\\,11)$",
            "$(-7,\\,1,\\,-7)$",
            "$(5,\\,1,\\,-7)$",
            "$(1,\\,1,\\,5)$"
          ],
          "answer": 0,
          "solution": "$y=4-t=1 \\Rightarrow t=3$ ، فالنقطة $(-1+6,\\ 1,\\ 2+9)=(5,\\,1,\\,11)$",
          "explain": {
            "idea": "نقطة على المستقيم ← نكتب إحداثياتها العامة بدلالة $t$ ، ونستعمل المعلومة المعطاة لإيجاد $t$ ، ثم نعوّض في باقي الإحداثيات. هنا نعرف $y$.",
            "steps": [
              "نقاط المستقيم: $(-1+2t,\\ 4-t,\\ 2+3t)$",
              "$y=1$: $4-t=1$ ، إذن $t=3$",
              "$x=-1+6=5$ ، $z=2+9=11$",
              "النقطة $(5,1,11)$"
            ],
            "wrong": [
              null,
              "تنتج من $t=-3$؛ لكن من $4-t=1$ تكون $t=3$.",
              "$z=2+3(3)=11$ لا $-7$.",
              "هذه $x$ و $z$ عند $t=1$ ، وعندها $y=3\\neq1$."
            ]
          }
        },
        {
          "id": "u6e3q7",
          "lesson": "u6-l2",
          "difficulty": "medium",
          "text": "معادلة المستقيم المارّ بالنقطة $(1,\\,-1,\\,2)$ ، والموازي للمستقيم: $\\vec{\\mathbf{r}}=\\langle 0,\\,3,\\,1\\rangle+t\\langle 4,\\,-2,\\,1\\rangle$ ، هي:",
          "options": [
            "$\\vec{\\mathbf{r}}=\\langle 1,\\,-1,\\,2\\rangle+t\\langle 4,\\,-2,\\,1\\rangle$",
            "$\\vec{\\mathbf{r}}=\\langle 0,\\,3,\\,1\\rangle+t\\langle 1,\\,-1,\\,2\\rangle$",
            "$\\vec{\\mathbf{r}}=\\langle 1,\\,-1,\\,2\\rangle+t\\langle 0,\\,3,\\,1\\rangle$",
            "$\\vec{\\mathbf{r}}=\\langle 4,\\,-2,\\,1\\rangle+t\\langle 1,\\,-1,\\,2\\rangle$"
          ],
          "answer": 0,
          "solution": "المستقيمان المتوازيان لهما متجه الاتجاه نفسه $\\langle 4,-2,1\\rangle$ ، والمستقيم المطلوب يمرّ بالنقطة $(1,-1,2)$",
          "explain": {
            "idea": "المستقيمان المتوازيان لهما متجه الاتجاه نفسه؛ والنقطة هي النقطة المعطاة.",
            "steps": [
              "المعادلة المتجهة للمستقيم: $\\vec{\\mathbf{r}}=\\vec{\\mathbf{r}}_0+t\\vec{\\mathbf{v}}$ ، حيث $\\vec{\\mathbf{r}}_0$ متجه موقع نقطة على المستقيم، و $\\vec{\\mathbf{v}}$ متجه اتجاهه",
              "متجه الاتجاه من المستقيم المعطى: $\\langle 4,-2,1\\rangle$ (المضروب في $t$)",
              "النقطة: $(1,-1,2)$",
              "$\\vec{\\mathbf{r}}=\\langle 1,-1,2\\rangle+t\\langle 4,-2,1\\rangle$"
            ],
            "wrong": [
              null,
              "هذا يمرّ بنقطة المستقيم المعطى، واتجاهه هو النقطة الجديدة؛ خطآن.",
              "$\\langle 0,3,1\\rangle$ نقطة على المستقيم المعطى، لا اتجاهه.",
              "النقطة والاتجاه مبدّلان."
            ]
          }
        },
        {
          "id": "u6e3q8",
          "lesson": "u6-l2",
          "difficulty": "hard",
          "text": "العلاقة بين المستقيمين: $\\vec{\\mathbf{r}}_1=\\langle 2,-1,0\\rangle+t\\langle 1,3,-2\\rangle$ و $\\vec{\\mathbf{r}}_2=\\langle 4,5,-4\\rangle+s\\langle -2,-6,4\\rangle$ هي أنّهما:",
          "options": [
            "منطبقان",
            "متوازيان",
            "متقاطعان",
            "متخالفان"
          ],
          "answer": 0,
          "solution": "$\\langle -2,-6,4\\rangle=-2\\langle 1,3,-2\\rangle$ ، فمتجها الاتجاه متوازيان.\nالنقطة $(4,5,-4)$ تقع على $\\vec{\\mathbf{r}}_1$ عند $t=2$: $\\langle 2+2,\\,-1+6,\\,0-4\\rangle=\\langle 4,5,-4\\rangle$ ✔\nإذن المستقيمان منطبقان.",
          "explain": {
            "idea": "اتجاهان متوازيان ← متوازيان أو منطبقان؛ نختبر نقطة من أحدهما على الآخر.",
            "steps": [
              "العلاقة بين مستقيمين: إذا توازى متجها الاتجاه فهما متوازيان أو منطبقان (نختبر نقطة من أحدهما على الآخر)، وإلّا فهما متقاطعان أو متخالفان (نحلّ معادلات تساوي الإحداثيات)",
              "$\\langle -2,-6,4\\rangle=-2\\langle 1,3,-2\\rangle$ ، فالاتجاهان متوازيان",
              "هل $(4,5,-4)$ على $\\vec{\\mathbf{r}}_1$؟ من $x$: $2+t=4$ ، إذن $t=2$",
              "$y=-1+3(2)=5$ ✔ ، $z=0-2(2)=-4$ ✔",
              "النقطة على المستقيمين، فهما منطبقان"
            ],
            "wrong": [
              null,
              "المتوازيان لا يشتركان في أيّ نقطة، وهنا $(4,5,-4)$ مشتركة.",
              "المتقاطعان اتجاهاهما غير متوازيين.",
              "المتخالفان اتجاهاهما غير متوازيين."
            ]
          }
        },
        {
          "id": "u6e3q9",
          "lesson": "u6-l2",
          "difficulty": "hard",
          "text": "إحداثيات نقطة تقاطع المستقيمين: $\\vec{\\mathbf{r}}_1=\\langle 1,0,-2\\rangle+t\\langle 2,-1,3\\rangle$ و $\\vec{\\mathbf{r}}_2=\\langle -3,-3,-7\\rangle+s\\langle 1,2,1\\rangle$ هي:",
          "options": [
            "$(-1,\\,1,\\,-5)$",
            "$(3,\\,-1,\\,1)$",
            "$(-3,\\,-3,\\,-7)$",
            "$(1,\\,0,\\,-2)$"
          ],
          "answer": 0,
          "solution": "$1+2t=-3+s$ ، $-t=-3+2s$ ، $-2+3t=-7+s$\nبطرح الأولى من الثالثة: $-3+t=-4 \\Rightarrow t=-1$ ، ومنه $s=2$ ، وتحقق في الثانية: $1=-3+4$ ✔\nنقطة التقاطع: $\\langle 1,0,-2\\rangle-\\langle 2,-1,3\\rangle=(-1,\\,1,\\,-5)$",
          "explain": {
            "idea": "نساوي الإحداثيات ونحلّ معادلتين، ثم نتحقّق في الثالثة.",
            "steps": [
              "$x$: $1+2t=-3+s$ ، $y$: $-t=-3+2s$ ، $z$: $-2+3t=-7+s$",
              "نطرح معادلة $x$ من معادلة $z$ (فيُحذف $s$): $(-2+3t)-(1+2t)=-7-(-3)$ ، أي $-3+t=-4$ ، إذن $t=-1$",
              "من $x$: $1-2=-3+s$ ، إذن $s=2$",
              "تحقّق $y$: $-(-1)=1$ و $-3+4=1$ ✔",
              "النقطة: $(1-2,\\ 0+1,\\ -2-3)=(-1,1,-5)$"
            ],
            "wrong": [
              null,
              "نقطة على $\\vec{\\mathbf{r}}_1$ عند $t=1$ ، لكنها ليست على $\\vec{\\mathbf{r}}_2$.",
              "نقطة البداية على $\\vec{\\mathbf{r}}_2$ ($s=0$) ، لكنها ليست على $\\vec{\\mathbf{r}}_1$.",
              "نقطة البداية على $\\vec{\\mathbf{r}}_1$ ($t=0$) ، لكنها ليست على $\\vec{\\mathbf{r}}_2$."
            ]
          }
        },
        {
          "id": "u6e3q10",
          "lesson": "u6-l3",
          "difficulty": "easy",
          "text": "إذا كان: $\\vec{\\mathbf{a}}=\\langle 2,\\,-3,\\,1\\rangle$ ، $\\vec{\\mathbf{b}}=\\langle 4,\\,1,\\,-2\\rangle$ ، فإنّ $\\vec{\\mathbf{a}}\\cdot\\vec{\\mathbf{b}}$ يساوي:",
          "options": [
            "$3$",
            "$-3$",
            "$11$",
            "$7$"
          ],
          "answer": 0,
          "solution": "$\\vec{\\mathbf{a}}\\cdot\\vec{\\mathbf{b}}=2(4)+(-3)(1)+1(-2)=8-3-2=3$",
          "explain": {
            "idea": "الضرب القياسي: نضرب المركبات المتناظرة ونجمع (الناتج عدد لا متجه).",
            "steps": [
              "الضرب القياسي: $\\langle a_1,a_2,a_3\\rangle\\cdot\\langle b_1,b_2,b_3\\rangle=a_1b_1+a_2b_2+a_3b_3$ ، وأيضًا $\\vec{\\mathbf{u}}\\cdot\\vec{\\mathbf{v}}=|\\vec{\\mathbf{u}}||\\vec{\\mathbf{v}}|\\cos\\theta$ ، والمتجهان متعامدان إذا كان ضربهما القياسي صفرًا",
              "$2(4)+(-3)(1)+1(-2)=8-3-2=3$"
            ],
            "wrong": [
              null,
              "خطأ إشارة؛ $8-3-2=+3$.",
              "$(-3)(1)=-3$ لا $+3$.",
              "$1\\times(-2)=-2$ لا $+2$."
            ]
          }
        },
        {
          "id": "u6e3q11",
          "lesson": "u6-l3",
          "difficulty": "medium",
          "text": "قياس الزاوية بين المتجهين: $\\langle 1,\\,-1,\\,0\\rangle$ و $\\langle 0,\\,1,\\,-1\\rangle$ هو:",
          "options": [
            "$\\frac{2\\pi}{3}$",
            "$\\frac{\\pi}{3}$",
            "$\\frac{\\pi}{6}$",
            "$\\frac{5\\pi}{6}$"
          ],
          "answer": 0,
          "solution": "$\\cos\\theta=\\dfrac{0-1+0}{\\sqrt2\\cdot\\sqrt2}=-\\dfrac12 \\Rightarrow \\theta=\\dfrac{2\\pi}{3}$ (الزاوية بين متجهين قد تكون منفرجة)",
          "explain": {
            "idea": "الزاوية بين متجهين: $\\cos\\theta=\\dfrac{\\vec{\\mathbf{u}}\\cdot\\vec{\\mathbf{v}}}{|\\vec{\\mathbf{u}}||\\vec{\\mathbf{v}}|}$ ، و $0\\le\\theta\\le\\pi$ (إشارة الضرب القياسي السالبة تعني زاوية منفرجة).",
            "steps": [
              "الضرب القياسي: $1(0)+(-1)(1)+0(-1)=-1$",
              "المقداران: $\\sqrt{1+1+0}=\\sqrt2$ و $\\sqrt{0+1+1}=\\sqrt2$",
              "$\\cos\\theta=\\dfrac{-1}{\\sqrt2\\times\\sqrt2}=-\\frac12$",
              "جيب التمام سالب ← الزاوية منفرجة، وزاوية الإسناد $\\frac{\\pi}{3}$ ، إذن $\\theta=\\pi-\\frac{\\pi}{3}=\\frac{2\\pi}{3}$"
            ],
            "wrong": [
              null,
              "$\\cos\\frac{\\pi}{3}=+\\frac12$؛ أُهملت الإشارة السالبة.",
              "$\\cos\\frac{\\pi}{6}=\\frac{\\sqrt3}{2}\\neq-\\frac12$.",
              "$\\cos\\frac{5\\pi}{6}=-\\frac{\\sqrt3}{2}\\neq-\\frac12$."
            ]
          }
        },
        {
          "id": "u6e3q12",
          "lesson": "u6-l3",
          "difficulty": "hard",
          "text": "إذا كانت $M,\\ N,\\ P$ ثلاث نقاط في الفضاء، وكان: $\\overrightarrow{MN}=\\langle 1,\\,4,\\,-2\\rangle$ ، $\\overrightarrow{PN}=\\langle 3,\\,-1,\\,2\\rangle$ ، فإنّ $\\overrightarrow{MN}\\cdot\\overrightarrow{MP}$ يساوي:",
          "options": [
            "$26$",
            "$16$",
            "$-5$",
            "$10$"
          ],
          "answer": 0,
          "solution": "$\\overrightarrow{MP}=\\overrightarrow{MN}+\\overrightarrow{NP}=\\overrightarrow{MN}-\\overrightarrow{PN}=\\langle -2,\\,5,\\,-4\\rangle$\n$\\overrightarrow{MN}\\cdot\\overrightarrow{MP}=-2+20+8=26$",
          "explain": {
            "idea": "نعبّر عن $\\overrightarrow{MP}$ بالمعطيين: من $M$ إلى $N$ ثم من $N$ إلى $P$ ، و $\\overrightarrow{NP}=-\\overrightarrow{PN}$.",
            "steps": [
              "$\\overrightarrow{NP}=-\\overrightarrow{PN}=\\langle -3,1,-2\\rangle$",
              "$\\overrightarrow{MP}=\\overrightarrow{MN}+\\overrightarrow{NP}=\\langle 1-3,\\ 4+1,\\ -2-2\\rangle=\\langle -2,5,-4\\rangle$",
              "الضرب القياسي: $\\langle a_1,a_2,a_3\\rangle\\cdot\\langle b_1,b_2,b_3\\rangle=a_1b_1+a_2b_2+a_3b_3$ ، وأيضًا $\\vec{\\mathbf{u}}\\cdot\\vec{\\mathbf{v}}=|\\vec{\\mathbf{u}}||\\vec{\\mathbf{v}}|\\cos\\theta$ ، والمتجهان متعامدان إذا كان ضربهما القياسي صفرًا",
              "$\\overrightarrow{MN}\\cdot\\overrightarrow{MP}=1(-2)+4(5)+(-2)(-4)=-2+20+8=26$"
            ],
            "wrong": [
              null,
              "تنتج من $\\overrightarrow{MP}=\\overrightarrow{MN}+\\overrightarrow{PN}$؛ لكن $\\overrightarrow{PN}$ في الاتجاه المعاكس لـ $\\overrightarrow{NP}$.",
              "هذا $\\overrightarrow{MN}\\cdot\\overrightarrow{PN}$ ، لا مع $\\overrightarrow{MP}$.",
              "تحقّقي: $-2+20+8=26$."
            ]
          }
        }
      ]
    }
  ]
};

export default unit;
