"""Five full mock papers for semester 1 (units 1-4), modelled on the ministry paper of
2 July 2026 (items 1-25) and the official half-year trial format (30 items / 90 minutes).
Per paper: U1 items 1-4, U2 items 5-10, U3 items 11-22, U4 items 23-30."""
from qb import *
import numpy as np

R = Rational
P = pi
X, Y = symbols('X Y', real=True)
U1 = {1: 'u1-l1', 2: 'u1-l2'}
U2 = {1: 'u2-l1', 2: 'u2-l2', 3: 'u2-l3'}
U3 = {i: f'u3-l{i}' for i in range(1, 6)}
U4 = {1: 'u4-l1', 2: 'u4-l2', 3: 'u4-l3'}

# ------------------------------------------------------------------ helpers
def roots(f): return FiniteSet(*solve(f, x))
def other_roots(f, r0): return FiniteSet(*[q for q in solve(f, x) if simplify(q - r0) != 0])
def rem(f, r0): return expand(f).subs(x, r0)
def st(*vals_tex, var='x'): return r',\ '.join(f'{var}=' + t_ for t_ in vals_tex)
S_ = lambda *v_: FiniteSet(*v_)
deg = lambda d_: d_*pi/180
def sols(expr, lo, hi, closed_lo=True, closed_hi=False): return numsols(expr, lo, hi, closed_lo, closed_hi)
Dx = lambda f_: diff(f_, x)
def imp(eq, pt, order=1): return idiff(eq, y, x, order).subs({x: pt[0], y: pt[1]})
pol = lambda r_, th_: r_*(cos(th_) + I*sin(th_))
def trig(r_tex, th_tex): return rf'{r_tex}\left(\cos({th_tex})+i\sin({th_tex})\right)'
def croots(poly): return FiniteSet(*[nsimplify(expand(r_)) for r_ in solve(poly, z)])
def ab(lst): return Tuple(*lst)

def pw(points):
    def val(x0):
        for (x1, y1), (x2, y2) in zip(points, points[1:]):
            if x1 <= x0 <= x2:
                return R(y1) + R(y2 - y1, x2 - x1)*(x0 - x1)
        raise ValueError
    def slope(x0):
        for (x1, y1), (x2, y2) in zip(points, points[1:]):
            if x1 < x0 < x2:
                return R(y2 - y1, x2 - x1)
        raise ValueError('corner or outside')
    return val, slope

def draw_two(fpts, gpts, xmax, ymax, flabel, glabel):
    def draw(fig, ax):
        axes_style(ax, (-0.6, xmax + 0.6), (-0.6, ymax + 0.8), grid=True)
        ax.set_xticks(range(0, xmax + 1)); ax.set_yticks(range(0, ymax + 1))
        fx, fy = zip(*fpts); gx, gy = zip(*gpts)
        ax.plot(fx, fy, color='#1f5fbf', lw=2); ax.plot(gx, gy, color='#d04a1a', lw=2)
        ax.text(*flabel, r'$f(x)$', color='#1f5fbf', fontsize=12)
        ax.text(*glabel, r'$g(x)$', color='#d04a1a', fontsize=12)
    return draw

def complex_axes(ax, lim):
    axes_style(ax, (-lim, lim), (-lim, lim), xlabel=r'\mathrm{Re}', ylabel=r'\mathrm{Im}', grid=True)
    ax.set_aspect('equal'); ax.set_xticks(range(-lim + 1, lim)); ax.set_yticks(range(-lim + 1, lim))
    ax.tick_params(labelsize=8)

FILL, LINE = '#9cc3ef', '#1f5fbf'

def fig_region(kind):
    """locus regions used in the papers (drawn exactly as described in each solution)"""
    def draw(fig, ax):
        if kind == 'halfdisk':          # |z-i|<=2 , 0<=Arg(z-i)<=pi
            complex_axes(ax, 4)
            th_ = np.linspace(0, np.pi, 100)
            ax.fill(np.r_[2*np.cos(th_)], np.r_[1 + 2*np.sin(th_)], color=FILL, alpha=0.8)
            ax.plot(2*np.cos(th_), 1 + 2*np.sin(th_), color=LINE, lw=1.8)
            ax.plot([-2, 2], [1, 1], color=LINE, lw=1.8)
            ax.plot(0, 1, 'o', mfc='white', mec=LINE, ms=5)
        elif kind == 'disk_right':      # |z|<=3 , |z-2|<=|z|  (x>=1)
            complex_axes(ax, 4)
            th_ = np.linspace(-np.arccos(1/3), np.arccos(1/3), 100)
            xs = np.r_[1, 3*np.cos(th_), 1]; ys = np.r_[-np.sqrt(8), 3*np.sin(th_), np.sqrt(8)]
            ax.fill(xs, ys, color=FILL, alpha=0.8)
            full = np.linspace(0, 2*np.pi, 200)
            ax.plot(3*np.cos(full), 3*np.sin(full), color=LINE, lw=1.4)
            ax.plot([1, 1], [-3.9, 3.9], color=LINE, lw=1.4)
            ax.plot(2, 0, 'x', color='#d04a1a', ms=7)
        elif kind == 'quarter_ring':    # 1<|z|<=3 , 0<=Arg z<=pi/2
            complex_axes(ax, 4)
            th_ = np.linspace(0, np.pi/2, 100)
            xs = np.r_[3*np.cos(th_), np.cos(th_[::-1])]; ys = np.r_[3*np.sin(th_), np.sin(th_[::-1])]
            ax.fill(xs, ys, color=FILL, alpha=0.8)
            ax.plot(3*np.cos(th_), 3*np.sin(th_), color=LINE, lw=1.8)
            ax.plot(np.cos(th_), np.sin(th_), color=LINE, lw=1.6, ls='--')
            ax.plot([1, 3], [0, 0], color=LINE, lw=1.8); ax.plot([0, 0], [1, 3], color=LINE, lw=1.8)
        elif kind == 'disk_left':       # |z-2i|<=2 , |z|<=|z-2| (x<=1)
            complex_axes(ax, 5)
            th_ = np.linspace(np.pi - np.arccos(-0.5), np.pi + np.arccos(-0.5), 10)
            t2 = np.linspace(np.arccos(0.5), 2*np.pi - np.arccos(0.5), 200)
            xs = 2*np.cos(t2); ys = 2 + 2*np.sin(t2)
            ax.fill(np.r_[xs, 1], np.r_[ys, 2 + 2*np.sin(np.arccos(0.5))], color=FILL, alpha=0.8)
            full = np.linspace(0, 2*np.pi, 200)
            ax.plot(2*np.cos(full), 2 + 2*np.sin(full), color=LINE, lw=1.4)
            ax.plot([1, 1], [-4.9, 4.9], color=LINE, lw=1.4)
            ax.plot(2, 0, 'x', color='#d04a1a', ms=7)
        elif kind == 'wedge':           # pi/6<=Arg(z+1-i)<=2pi/3
            complex_axes(ax, 5)
            v0 = np.array([-1, 1]); L_ = 7
            a1, a2 = np.pi/6, 2*np.pi/3
            pts = [v0, v0 + L_*np.array([np.cos(a1), np.sin(a1)]), v0 + L_*np.array([np.cos(a2), np.sin(a2)])]
            ax.fill([p_[0] for p_ in pts], [p_[1] for p_ in pts], color=FILL, alpha=0.8)
            for a_ in (a1, a2):
                e_ = v0 + L_*np.array([np.cos(a_), np.sin(a_)])
                ax.plot([v0[0], e_[0]], [v0[1], e_[1]], color=LINE, lw=1.8)
            ax.plot(*v0, 'o', mfc='white', mec=LINE, ms=5)
            ax.set_xlim(-5, 5); ax.set_ylim(-5, 5)
    return draw

NOTE_I = lambda a_, b_: rf"ملحوظة: في جميع الفقرات من ({a_}) إلى ({b_}) ، فإنّ $i=\sqrt{{-1}}$ حيثما وردت، و $\text{{Arg}}(z)$ هي السعة الرئيسة للعدد $z$."
def shared(stem, a_, b_):
    return rf"❖ {stem} ، فاعتمد ذلك للإجابة عن الفقرتين ({a_}) و ({b_}) الآتيتين:"

# ================================================================== PAPER 1
f1_17, fs1_17 = pw([(0, 1), (2, 5), (6, 3)])
g1_17, gs1_17 = pw([(0, 6), (4, 2), (6, 6)])
P1 = [
# ---------------- unit 1
Q('m1q1', U1[1], 'easy',
  F(r"إذا كان $x=3$ حلًّا للمعادلة: $«0»=«1»$ ، فإنّ لها حلّين آخرين هما:", (r'x^{3}+6', x**3+6), (r'x^{2}+8x', x**2+8*x)),
  [O(r'x=-1+\sqrt{3},\ x=-1-\sqrt{3}', S_(-1+sqrt(3), -1-sqrt(3)), 'set'), O(r'x=1+\sqrt{3},\ x=1-\sqrt{3}', S_(1+sqrt(3), 1-sqrt(3)), 'set'),
   O(r'x=-1+\sqrt{2},\ x=-1-\sqrt{2}', S_(-1+sqrt(2), -1-sqrt(2)), 'set'), O(r'x=2,\ x=-4', S_(2, -4), 'set')],
  r"نكتب المعادلة: $x^3-x^2-8x+6=0$ ، وبالقسمة التركيبية على $(x-3)$: $1,\ -1,\ -8,\ 6 \to 1,\ 2,\ -2,\ 0$" "\n"
  r"$x^2+2x-2=0 \Rightarrow x=\dfrac{-2\pm\sqrt{4+8}}{2}=-1\pm\sqrt3$",
  truth=lambda: other_roots(x**3-x**2-8*x+6, 3), tag='حل معادلة كثير حدود بمعلومية أحد جذورها'),
Q('m1q2', U1[1], 'medium',
  r"إذا كان باقي قسمة كثير الحدود $f(x)$ على $(x+1)$ هو $5$ ، وباقي قسمته على $(x-2)$ هو $-1$ ، فإنّ باقي قسمة $f(x)$ على $(x+1)(x-2)$ هو:",
  [O('-2x+3', -2*x+3), O('2x+3', 2*x+3), O('-2x-3', -2*x-3), O('3x-2', 3*x-2)],
  r"الباقي على الصورة $ax+b$: $f(-1)=-a+b=5$ ، $f(2)=2a+b=-1$" "\n" r"بالطرح: $3a=-6 \Rightarrow a=-2$ ، $b=3$ ، والباقي $-2x+3$",
  truth=lambda: (lambda s_: s_[a]*x+s_[b])(solve([-a+b-5, 2*a+b+1], [a, b])), tag='باقي القسمة على مقدار تربيعي'),
Q('m1q3', U1[2], 'easy',
  F(r"أيّ الآتية يُمثّل تجزئة المقدار النسبي: $«0»$ إلى كسور جزئية؟", (r'\frac{4x+11}{(x+2)^{2}}', (4*x+11)/(x+2)**2)),
  [O(r'\frac{4}{x+2}+\frac{3}{(x+2)^{2}}', 4/(x+2)+3/(x+2)**2), O(r'\frac{3}{x+2}+\frac{4}{(x+2)^{2}}', 3/(x+2)+4/(x+2)**2),
   O(r'\frac{4}{x+2}-\frac{3}{(x+2)^{2}}', 4/(x+2)-3/(x+2)**2), O(r'\frac{11}{x+2}+\frac{4}{(x+2)^{2}}', 11/(x+2)+4/(x+2)**2)],
  r"$4x+11=A(x+2)+B$ ، عند $x=-2$: $B=3$ ، ومعامل $x$: $A=4$",
  truth=(4*x+11)/(x+2)**2, tag='تجزئة: عامل خطي مكرر'),
Q('m1q4', U1[2], 'hard',
  F(r"إذا كان: $«0»=\dfrac{A}{x+2}+\dfrac{3}{x-4}$ ، حيث $a,\ A$ ثابتان، فإنّ قيمة $a+A$ هي:", (r'\frac{ax-2}{(x+2)(x-4)}', (a*x-2)/((x+2)*(x-4)))),
  [O('7', 7), O('5', 5), O('2', 2), O('8', 8)],
  r"$ax-2=A(x-4)+3(x+2)$" "\n" r"عند $x=4$: $4a-2=18 \Rightarrow a=5$" "\n" r"عند $x=-2$: $-2a-2=-6A \Rightarrow -12=-6A \Rightarrow A=2$ ، إذن $a+A=7$",
  truth=lambda: (lambda s_: s_[a]+s_[b])(solve(Poly(expand(a*x-2-b*(x-4)-3*(x+2)), x).all_coeffs(), [a, b])), tag='إيجاد ثوابت في التجزئة'),
# ---------------- unit 2
Q('m1q5', U2[2], 'medium',
  r"إذا كان $\cos\theta=-\frac{7}{9}$ ، حيث $\pi<\theta<\frac{3\pi}{2}$ ، فإنّ قيمة $\sin\frac{\theta}{2}$ تساوي:",
  [O(r'\frac{2\sqrt{2}}{3}', 2*sqrt(2)/3), O(r'-\frac{2\sqrt{2}}{3}', -2*sqrt(2)/3), O(r'\frac{1}{3}', R(1, 3)), O(r'-\frac{1}{3}', -R(1, 3))],
  r"$\frac{\pi}{2}<\frac{\theta}{2}<\frac{3\pi}{4}$ ، أي في الربع الثاني فالجيب موجب" "\n"
  r"$\sin\frac{\theta}{2}=\sqrt{\dfrac{1-\cos\theta}{2}}=\sqrt{\dfrac{1+\frac79}{2}}=\sqrt{\dfrac89}=\dfrac{2\sqrt2}{3}$",
  truth=sin((pi+acos(R(7, 9)))/2), tag='نصف الزاوية مع تحديد الربع'),
Q('m1q6', U2[1], 'easy',
  F(r"أبسط صورة للمقدار: $«0»$ هي:", (r'\sin(x+\frac{\pi}{3})-\frac{\sqrt{3}}{2}\cos x', sin(x+pi/3)-sqrt(3)/2*cos(x))),
  [O(r'\frac{1}{2}\sin x', sin(x)/2), O(r'\frac{\sqrt{3}}{2}\sin x', sqrt(3)/2*sin(x)), O(r'\frac{1}{2}\cos x', cos(x)/2), O(r'\sin x', sin(x))],
  r"$\sin\left(x+\frac{\pi}{3}\right)=\sin x\cos\frac{\pi}{3}+\cos x\sin\frac{\pi}{3}=\frac12\sin x+\frac{\sqrt3}{2}\cos x$" "\n" r"بطرح $\frac{\sqrt3}{2}\cos x$ يبقى $\frac12\sin x$",
  truth=sin(x+pi/3)-sqrt(3)/2*cos(x), tag='تبسيط باستعمال متطابقات المجموع والفرق'),
Q('m1q7', U2[2], 'medium',
  r"إذا كان $\tan\theta=-\frac{3}{4}$ ، حيث $\frac{\pi}{2}<\theta<\pi$ ، فإنّ قيمة $\cos2\theta$ تساوي:",
  [O(r'\frac{7}{25}', R(7, 25)), O(r'-\frac{7}{25}', -R(7, 25)), O(r'\frac{24}{25}', R(24, 25)), O(r'-\frac{24}{25}', -R(24, 25))],
  r"$\cos2\theta=\dfrac{1-\tan^2\theta}{1+\tan^2\theta}=\dfrac{1-\frac{9}{16}}{1+\frac{9}{16}}=\dfrac{7}{25}$" "\n" r"(أو: $\cos\theta=-\frac45$ ، $\cos2\theta=2\cos^2\theta-1=\frac{32}{25}-1=\frac{7}{25}$)",
  truth=cos(2*(pi-atan(R(3, 4)))), tag='ضعف الزاوية بمعلومية نسبة'),
Q('m1q8', U2[2], 'easy',
  r"قيمة المقدار: $\cos75^\circ+\cos15^\circ$ هي:",
  [O(r'\frac{\sqrt{6}}{2}', sqrt(6)/2), O(r'\frac{\sqrt{2}}{2}', sqrt(2)/2), O(r'\frac{\sqrt{3}}{2}', sqrt(3)/2), O('1', 1)],
  r"$\cos A+\cos B=2\cos\dfrac{A+B}{2}\cos\dfrac{A-B}{2}=2\cos45^\circ\cos30^\circ=2\cdot\frac{\sqrt2}{2}\cdot\frac{\sqrt3}{2}=\frac{\sqrt6}{2}$",
  truth=cos(deg(75))+cos(deg(15)), tag='تحويل المجموع إلى ضرب'),
Q('m1q9', U2[3], 'easy',
  F(r"حلّ المعادلة: $«0»=0$ في الفترة $[0,\,2\pi)$ هو:", (r'2\sin^{2}x+5\sin x-3', 2*sin(x)**2+5*sin(x)-3)),
  [O(st(r'\frac{\pi}{6}', r'\frac{5\pi}{6}'), S_(P/6, 5*P/6), 'set'), O(st(r'\frac{7\pi}{6}', r'\frac{11\pi}{6}'), S_(7*P/6, 11*P/6), 'set'),
   O(st(r'\frac{\pi}{3}', r'\frac{2\pi}{3}'), S_(P/3, 2*P/3), 'set'), O(st(r'\frac{\pi}{6}', r'\frac{11\pi}{6}'), S_(P/6, 11*P/6), 'set')],
  r"بالتحليل: $(2\sin x-1)(\sin x+3)=0$" "\n" r"$\sin x=-3$ مرفوض، و $\sin x=\frac12 \Rightarrow x=\frac{\pi}{6},\ \frac{5\pi}{6}$",
  truth=lambda: sols(2*sin(x)**2+5*sin(x)-3, 0, 2*pi), tag='معادلة تربيعية في نسبة مثلثية مع رفض حل'),
Q('m1q10', U2[3], 'hard',
  F(r"حلول المعادلة: $«0»=0$ في الفترة $(0,\,\pi)$ هي:", (r'4\cos x+\sqrt{3}\csc x', 4*cos(x)+sqrt(3)*csc(x))),
  [O(st(r'\frac{2\pi}{3}', r'\frac{5\pi}{6}'), S_(2*P/3, 5*P/6), 'set'), O(st(r'\frac{2\pi}{3}', r'\frac{5\pi}{6}', r'\frac{5\pi}{3}', r'\frac{11\pi}{6}'), S_(2*P/3, 5*P/6, 5*P/3, 11*P/6), 'set'),
   O(st(r'\frac{\pi}{6}', r'\frac{\pi}{3}'), S_(P/6, P/3), 'set'), O(st(r'\frac{4\pi}{3}', r'\frac{5\pi}{3}'), S_(4*P/3, 5*P/3), 'set')],
  r"نضرب الطرفين في $\sin x$ ($\ne0$): $4\sin x\cos x+\sqrt3=0 \Rightarrow 2\sin2x=-\sqrt3 \Rightarrow \sin2x=-\frac{\sqrt3}{2}$" "\n"
  r"بما أن $0<x<\pi$ فإن $0<2x<2\pi$: $2x=\frac{4\pi}{3}$ أو $2x=\frac{5\pi}{3}$ ، إذن $x=\frac{2\pi}{3},\ \frac{5\pi}{6}$",
  truth=lambda: sols(4*cos(x)*sin(x)+sqrt(3), 0, pi, closed_lo=False), tag='معادلة فيها مقلوب نسبة وزاوية مضاعفة'),
# ---------------- unit 3
Q('m1q11', U3[1], 'easy',
  F(r"إذا كان: $f(x)=«0»$ ، فإنّ $\dfrac{f'(x)}{f(x)}$ يساوي:", (r'\sec x+\tan x', sec(x)+tan(x))),
  [O(r'\sec x', sec(x)), O(r'\tan x', tan(x)), O(r'\sec x\tan x', sec(x)*tan(x)), O(r'\csc x', csc(x))],
  r"$f'(x)=\sec x\tan x+\sec^2x=\sec x(\tan x+\sec x)=\sec x\cdot f(x)$ ، إذن $\dfrac{f'(x)}{f(x)}=\sec x$",
  truth=Dx(sec(x)+tan(x))/(sec(x)+tan(x)), tag='مشتقات الاقترانات المثلثية'),
Q('m1q12', U3[2], 'medium',
  F(r"إذا كان: $f(x)=«0»$ ، وكان: $f'(e)=4e$ ، فإنّ قيمة الثابت $b$ هي:", (r'x^{2}\ln x+bx', x**2*log(x)+b*x)),
  [O('e', E), O('4e', 4*E), O('-e', -E), O('2e', 2*E)],
  r"$f'(x)=2x\ln x+x+b$ ، إذن $f'(e)=2e+e+b=3e+b=4e \Rightarrow b=e$",
  truth=lambda: solve(Dx(x**2*log(x)+b*x).subs(x, E)-4*E, b)[0], tag='إيجاد ثابت بمعلومية قيمة المشتقة'),
Q('m1q13', U3[2], 'medium',
  F(r"إذا كان: $f(x)=«0»$ ، فإنّ $f''(x)-2f'(x)$ يساوي:", (r'e^{3x}+e^{-x}', exp(3*x)+exp(-x))),
  [O(r'3e^{3x}+3e^{-x}', 3*exp(3*x)+3*exp(-x)), O(r'3e^{3x}-e^{-x}', 3*exp(3*x)-exp(-x)), O(r'15e^{3x}+3e^{-x}', 15*exp(3*x)+3*exp(-x)), O(r'9e^{3x}+e^{-x}', 9*exp(3*x)+exp(-x))],
  r"$f'(x)=3e^{3x}-e^{-x}$ ، $f''(x)=9e^{3x}+e^{-x}$" "\n" r"$f''-2f'=9e^{3x}+e^{-x}-6e^{3x}+2e^{-x}=3e^{3x}+3e^{-x}$",
  truth=diff(exp(3*x)+exp(-x), x, 2)-2*Dx(exp(3*x)+exp(-x)), tag='المشتقات العليا وتراكيبها'),
Q('m1q14', U3[3], 'medium',
  F(r"إذا كان: $f(x)=«0»$ ، فإنّ $f'(2)$ تساوي:", (r'\log_{5}(x^{2}+1)', log(x**2+1, 5))),
  [O(r'\frac{4}{5\ln 5}', 4/(5*log(5))), O(r'\frac{4}{5}', R(4, 5)), O(r'\frac{4\ln 5}{5}', 4*log(5)/5), O(r'\frac{2}{5\ln 5}', 2/(5*log(5)))],
  r"$f'(x)=\dfrac{2x}{(x^2+1)\ln5} \Rightarrow f'(2)=\dfrac{4}{5\ln5}$",
  truth=Dx(log(x**2+1, 5)).subs(x, 2), tag='مشتقة اللوغاريتم لأساس غير e'),
Q('m1q15', U3[2], 'hard',
  F(r"المقطع $y$ للعمودي على المماس لمنحنى الاقتران: $f(x)=«0»$ عند $x=1$ هو:", (r'xe^{x}', x*exp(x))),
  [O(r'e+\frac{1}{2e}', E+1/(2*E)), O(r'e-\frac{1}{2e}', E-1/(2*E)), O(r'\frac{1}{2e}', 1/(2*E)), O('e', E)],
  r"$f(1)=e$ ، $f'(x)=e^x(1+x) \Rightarrow f'(1)=2e$ ، فميل العمودي $-\dfrac{1}{2e}$" "\n"
  r"معادلة العمودي: $y-e=-\dfrac{1}{2e}(x-1)$ ، وعند $x=0$: $y=e+\dfrac{1}{2e}$",
  truth=(lambda f_: f_.subs(x, 1) + (-1/Dx(f_).subs(x, 1))*(0-1))(x*exp(x)), tag='معادلة العمودي على المماس'),
IndexQ('m1q16', U3[1], 'medium',
  F(r"يتحرّك جُسيم في مسار مستقيم، ويُعطى موقعه بالاقتران: $s(t)=«0»$ ، حيث $t\ge0$ الزمن بالثواني، و $s$ الموقع بالأمتار. الفترة الزمنية التي يتحرّك فيها الجُسيم في الاتجاه السالب هي:", (r't^{3}-9t^{2}+24t', t**3-9*t**2+24*t)),
  [T(r'$(2,\ 4)$', Interval.open(2, 4)), T(r'$(0,\ 2)$', Interval.open(0, 2)), T(r'$(4,\ \infty)$', Interval.open(4, oo)), T(r'$(0,\ 4)$', Interval.open(0, 4))],
  r"$v(t)=3t^2-18t+24=3(t-2)(t-4)$" "\n" r"تكون $v(t)<0$ عندما $2<t<4$ ، فيتحرّك الجُسيم في الاتجاه السالب في الفترة $(2,\,4)$",
  truth=lambda vals: only(vals, lambda iv: iv == solve_univariate_inequality(diff(t**3-9*t**2+24*t, t) < 0, t, relational=False)), tag='الحركة: اتجاه الحركة والسكون'),
Q('m1q17', U3[2], 'medium',
  r"يُبيّن الشكل الآتي منحنيي الاقترانين $f(x)$ و $g(x)$. إذا كان: $h(x)=f(x)\cdot g(x)$ ، فإنّ $h'(1)$ تساوي:",
  [O('7', 7), O('13', 13), O('-7', -7), O('3', 3)],
  r"من الشكل: $f(1)=3$ ، $f'(1)=2$ (ميل القطعة من $(0,1)$ إلى $(2,5)$) ، $g(1)=5$ ، $g'(1)=-1$ (ميل القطعة من $(0,6)$ إلى $(4,2)$)" "\n"
  r"$h'(1)=f'(1)g(1)+f(1)g'(1)=2(5)+3(-1)=7$",
  truth=lambda: fs1_17(1)*g1_17(1)+f1_17(1)*gs1_17(1), figure=figure('m1q17', draw_two([(0, 1), (2, 5), (6, 3)], [(0, 6), (4, 2), (6, 6)], 6, 6, (0.3, 6.3), (5.0, 5.6))),
  tag='المشتقة من التمثيل البياني'),
Q('m1q18', U3[2], 'medium',
  F(r"يُمثّل الاقتران: $C(t)=«0»$ تركيز دواء في الدم بالمليغرام لكل لتر بعد $t$ ساعة من تناوله. معدّل تغيّر التركيز عندما $t=1$ هو:", (r'\frac{20t}{t^{2}+4}', 20*t/(t**2+4))),
  [O(r'\frac{12}{5}', R(12, 5), units='mg/L/h'), O(r'-\frac{12}{5}', -R(12, 5), units='mg/L/h'), O('4', 4, units='mg/L/h'), O(r'\frac{4}{5}', R(4, 5), units='mg/L/h')],
  r"$C'(t)=\dfrac{20(t^2+4)-20t(2t)}{(t^2+4)^2}=\dfrac{80-20t^2}{(t^2+4)^2}$ ، إذن $C'(1)=\dfrac{60}{25}=\dfrac{12}{5}$",
  truth=diff(20*t/(t**2+4), t).subs(t, 1), tag='معدل التغير في سياق حياتي'),
Q('m1q19', U3[3], 'medium',
  F(r"إذا أُعطي منحنى بالمعادلتين الوسيطيتين: $x=«0»$ ، $y=«1»$ ، حيث $0<t<\pi$ ، فإنّ $\dfrac{dy}{dx}$ عندما $t=\frac{\pi}{3}$ هي:", (r'3\csc t', 3*csc(t)), (r'\cot t-2', cot(t)-2)),
  [O(r'\frac{2}{3}', R(2, 3)), O(r'\frac{3}{2}', R(3, 2)), O(r'-\frac{2}{3}', -R(2, 3)), O(r'\frac{2\sqrt{3}}{3}', 2*sqrt(3)/3)],
  r"$\dfrac{dy}{dx}=\dfrac{-\csc^2t}{-3\csc t\cot t}=\dfrac{\csc t}{3\cot t}=\dfrac{1}{3\cos t}$" "\n" r"عند $t=\frac{\pi}{3}$: $\dfrac{1}{3\cdot\frac12}=\dfrac23$",
  truth=(diff(cot(t)-2, t)/diff(3*csc(t), t)).subs(t, pi/3), tag='مشتقة المعادلات الوسيطية'),
Q('m1q20', U3[4], 'medium',
  F(r"إذا كان: $«0»=2$ ، فإنّ $\dfrac{dy}{dx}$ عندما $y=1$ هو:", (r'3^{x}y+y^{2}', 3**x*y+y**2)),
  [O(r'-\frac{\ln 3}{3}', -log(3)/3), O(r'\frac{\ln 3}{3}', log(3)/3), O(r'-\ln 3', -log(3)), O(r'-\frac{1}{3}', -R(1, 3))],
  r"عندما $y=1$: $3^x+1=2 \Rightarrow x=0$ ، فالنقطة $(0,1)$" "\n"
  r"باشتقاق الطرفين: $3^x\ln3\cdot y+3^xy'+2yy'=0$ ، وعند $(0,1)$: $\ln3+y'+2y'=0 \Rightarrow y'=-\dfrac{\ln3}{3}$",
  truth=imp(3**x*y+y**2-2, (0, 1)), tag='الاشتقاق الضمني عند نقطة'),
Q('m1q21', U3[4], 'hard',
  F(r"إذا مثّل المستقيم $l$ مماسًّا لمنحنى العلاقة: $«0»=7$ عند النقطة $(-1,\,2)$ ، فإنّ المقطع $y$ للمستقيم $l$ هو:", (r'x^{2}-xy+y^{2}', x**2-x*y+y**2)),
  [O(r'\frac{14}{5}', R(14, 5)), O(r'\frac{6}{5}', R(6, 5)), O(r'\frac{4}{5}', R(4, 5)), O(r'-\frac{14}{5}', -R(14, 5))],
  r"$2x-y-xy'+2yy'=0 \Rightarrow y'=\dfrac{y-2x}{2y-x}$ ، وعند $(-1,2)$: $y'=\dfrac{2+2}{4+1}=\dfrac45$" "\n"
  r"المماس: $y-2=\frac45(x+1)$ ، وعند $x=0$: $y=2+\frac45=\frac{14}{5}$",
  truth=lambda: 2 + imp(x**2-x*y+y**2-7, (-1, 2))*(0+1), tag='مماس منحنى علاقة ضمنية'),
Q('m1q22', U3[5], 'medium',
  r"خزّان على شكل أسطوانة دائرية قائمة، طول قُطر قاعدتها $3\ \text{m}$. يُضَخّ إليه الماء بمعدّل $450\ \text{L/min}$ ، فإنّ معدّل ارتفاع الماء في الخزّان عند أيّ لحظة هو:",
  [O(r'\frac{1}{5\pi}', 1/(5*pi), units='m/min'), O(r'\frac{1}{20\pi}', 1/(20*pi), units='m/min'), O(r'\frac{200}{\pi}', 200/pi, units='m/min'), O(r'\frac{2}{5\pi}', 2/(5*pi), units='m/min')],
  r"$450\ \text{L}=0.45\ \text{m}^3$ ، ونصف القطر $r=1.5\ \text{m}$" "\n"
  r"$V=\pi r^2h=2.25\pi h \Rightarrow 0.45=2.25\pi\dfrac{dh}{dt} \Rightarrow \dfrac{dh}{dt}=\dfrac{0.45}{2.25\pi}=\dfrac{1}{5\pi}\ \text{m/min}$",
  truth=R(45, 100)/(pi*R(3, 2)**2), tag='معدلات مرتبطة مع تحويل الوحدات'),
# ---------------- unit 4
Q('m1q23', U4[1], 'medium',
  r"إذا كان: $z=a+2\sqrt{3}\,i$ ، حيث $a<0$ ، وكان: $|z|=4$ ، فإنّ الصورة المثلثية للعدد المُركَّب $z$ هي:",
  [O(trig('4', r'\frac{2\pi}{3}'), pol(4, 2*P/3)), O(trig('4', r'\frac{\pi}{3}'), pol(4, P/3)), O(trig('4', r'-\frac{2\pi}{3}'), pol(4, -2*P/3)), O(trig('4', r'\frac{5\pi}{6}'), pol(4, 5*P/6))],
  r"$a^2+12=16 \Rightarrow a=-2$ (لأن $a<0$) ، فيكون $z=-2+2\sqrt3\,i$ في الربع الثاني" "\n"
  r"زاوية الإسناد $\tan^{-1}\left(\frac{2\sqrt3}{2}\right)=\frac{\pi}{3}$ ، و $\text{Arg}(z)=\pi-\frac{\pi}{3}=\frac{2\pi}{3}$",
  truth=lambda: [r_ for r_ in solve(a**2+12-16, a) if r_ < 0][0] + 2*sqrt(3)*I, tag='الصورة المثلثية بشروط', lead=NOTE_I(23, 30)),
Q('m1q24', U4[2], 'easy',
  r"ناتج $2z-iw$ هو:",
  [O('3-7i', 3-7*I), O('1-7i', 1-7*I), O('3-i', 3-I), O('1+7i', 1+7*I)],
  r"$2z=2-4i$ ، $iw=i(3+i)=3i+i^2=-1+3i$" "\n" r"$2z-iw=(2-4i)-(-1+3i)=3-7i$",
  truth=expand(2*(1-2*I)-I*(3+I)), tag='العمليات على الأعداد المركبة (نص مشترك)', lead=shared(r"إذا كان: $z=1-2i$ ، $w=3+i$", 24, 25)),
Q('m1q25', U4[2], 'medium',
  r"ناتج $\dfrac{z}{w}$ في الصورة القياسية هو:",
  [O(r'\frac{1-7i}{10}', (1-7*I)/10), O(r'\frac{1+7i}{10}', (1+7*I)/10), O(r'\frac{1-i}{2}', (1-I)/2), O(r'\frac{-1-7i}{10}', (-1-7*I)/10)],
  r"$\dfrac{1-2i}{3+i}\cdot\dfrac{3-i}{3-i}=\dfrac{3-i-6i+2i^2}{10}=\dfrac{1-7i}{10}$",
  truth=(1-2*I)/(3+I), tag='العمليات على الأعداد المركبة (نص مشترك)'),
Q('m1q26', U4[1], 'medium',
  r"إذا كان: $z=\dfrac{2+bi}{1+2i}$ ، فإنّ قيمة الثابت الحقيقي $b$ التي تجعل $z$ عددًا تخيّليًّا بحتًا هي:",
  [O('-1', -1), O('4', 4), O('1', 1), O('-4', -4)],
  r"$z=\dfrac{(2+bi)(1-2i)}{5}=\dfrac{2-4i+bi+2b}{5}=\dfrac{(2+2b)+(b-4)i}{5}$" "\n" r"يكون $z$ تخيّليًّا بحتًا إذا انعدم الجزء الحقيقي: $2+2b=0 \Rightarrow b=-1$",
  truth=lambda: solve(re(expand((2+X*I)*(1-2*I))), X)[0], tag='قيمة ثابت تجعل العدد حقيقيًا أو تخيليًا'),
Q('m1q27', U4[2], 'hard',
  r"إذا كان العدد $3i$ أحد جذور المعادلة: $z^{3}-2z^{2}+9z-18=0$ ، فإنّ الجذر الحقيقي للمعادلة هو:",
  [O('2', 2), O('-2', -2), O('3', 3), O('18', 18)],
  r"المعاملات حقيقية، إذن $-3i$ جذر أيضًا، و $(z-3i)(z+3i)=z^2+9$" "\n" r"$z^3-2z^2+9z-18=z^2(z-2)+9(z-2)=(z^2+9)(z-2)$ ، فالجذر الحقيقي $2$",
  truth=lambda: [r_ for r_ in solve(z**3-2*z**2+9*z-18, z) if r_.is_real][0], tag='معادلة كثير حدود بجذر مركب'),
Q('m1q28', U4[2], 'medium',
  r"إذا كان: $z_1=-1+i$ ، $z_2=\sqrt{3}-i$ ، فإنّ قياس الزاوية الصغرى المحصورة بين $z_1$ و $z_2$ هو:",
  [O(r'\frac{11\pi}{12}', 11*P/12), O(r'\frac{13\pi}{12}', 13*P/12), O(r'\frac{7\pi}{12}', 7*P/12), O(r'\frac{5\pi}{12}', 5*P/12)],
  r"$\text{Arg}(z_1)=\frac{3\pi}{4}$ ، $\text{Arg}(z_2)=-\frac{\pi}{6}$ ، والفرق $\frac{3\pi}{4}+\frac{\pi}{6}=\frac{11\pi}{12}<\pi$ فهو الزاوية الصغرى",
  truth=acos(re(expand((-1+I)*conjugate(sqrt(3)-I)))/(Abs(-1+I)*Abs(sqrt(3)-I))), tag='الزاوية بين عددين مركبين'),
Q('m1q29', U4[3], 'medium',
  r"المعادلة الديكارتية للمحل الهندسي: $|z+2i|=|z-4|$ هي:",
  [O('y=-2x+3', -2*x+3, 'eq'), O('y=2x-3', 2*x-3, 'eq'), O('y=-2x-3', -2*x-3, 'eq'), O(r'y=\frac{1}{2}x+3', x/2+3, 'eq')],
  r"$x^2+(y+2)^2=(x-4)^2+y^2 \Rightarrow 4y+4=-8x+16 \Rightarrow y=-2x+3$",
  truth=lambda: solve(expand(X**2+(Y+2)**2-(X-4)**2-Y**2), Y)[0].subs(X, x), tag='المعادلة الديكارتية لمحل هندسي'),
Q('m1q30', U4[3], 'hard',
  r"نظام المتباينات (بدلالة $z$) الذي يُمثّل المحل الهندسي المُمثَّل بالمنطقة المُظلَّلة في الشكل الآتي هو:",
  [T(r'$|z-i|\le2$ ، $0\le\text{Arg}(z-i)\le\pi$'), T(r'$|z+i|\le2$ ، $0\le\text{Arg}(z+i)\le\pi$'), T(r'$|z-i|\le2$ ، $0\le\text{Arg}(z)\le\pi$'), T(r'$|z-i|\le4$ ، $0\le\text{Arg}(z-i)\le\pi$')],
  r"المنطقة نصف قرص مركزه $(0,1)$ أي العدد $i$ ونصف قطره $2$: $|z-i|\le2$" "\n"
  r"وهي فوق الخط الأفقي المارّ بالمركز، أي الزاوية من $0$ إلى $\pi$ مقيسة من المركز: $0\le\text{Arg}(z-i)\le\pi$ (والمركز نفسه دائرة مفرّغة لأن $\text{Arg}(0)$ غير معرّفة)",
  manual='half disc centre i radius 2 above horizontal through centre', figure=figure('m1q30', fig_region('halfdisk'), 3.4, 3.4), tag='منطقة في المستوى المركب من الشكل'),
]

# ================================================================== PAPER 2
f2_16, fs2_16 = pw([(0, 2), (3, 5), (7, 1)])
g2_16, gs2_16 = pw([(0, 4), (2, 0), (7, 5)])
P2 = [
Q('m2q1', U1[1], 'easy',
  F(r"مجموعة أصفار الاقتران: $f(x)=«0»$ هي:", (r'2x^{3}+3x^{2}-11x-6', 2*x**3+3*x**2-11*x-6)),
  [O(r'\{2,\ -3,\ -\frac{1}{2}\}', S_(2, -3, -R(1, 2)), 'set'), O(r'\{-2,\ 3,\ \frac{1}{2}\}', S_(-2, 3, R(1, 2)), 'set'),
   O(r'\{2,\ -3,\ \frac{1}{2}\}', S_(2, -3, R(1, 2)), 'set'), O(r'\{1,\ -3,\ -2\}', S_(1, -3, -2), 'set')],
  r"$f(2)=16+12-22-6=0$ ، وبالقسمة التركيبية على $(x-2)$: $2,\ 3,\ -11,\ -6 \to 2,\ 7,\ 3,\ 0$" "\n"
  r"$2x^2+7x+3=(2x+1)(x+3)=0 \Rightarrow x=-\frac12,\ x=-3$",
  truth=lambda: roots(2*x**3+3*x**2-11*x-6), tag='الأصفار النسبية وحل المعادلة'),
Q('m2q2', U1[1], 'medium',
  F(r"إذا كان: $f(x)=«0»$ ، وكان باقي قسمة $f(x)$ على $(x-3)$ يساوي مثلي باقي قسمته على $(x+1)$ ، فإنّ قيمة الثابت $k$ هي:", (r'x^{3}-2x^{2}+kx+5', x**3-2*x**2+k*x+5)),
  [O('-2', -2), O('2', 2), O('-3', -3), O('6', 6)],
  r"$f(3)=27-18+3k+5=14+3k$ ، $f(-1)=-1-2-k+5=2-k$" "\n" r"$14+3k=2(2-k) \Rightarrow 5k=-10 \Rightarrow k=-2$",
  truth=lambda: solve(rem(x**3-2*x**2+k*x+5, 3)-2*rem(x**3-2*x**2+k*x+5, -1), k)[0], tag='نظرية الباقي وإيجاد ثابت'),
Q('m2q3', U1[2], 'medium',
  F(r"أيّ الآتية يُمثّل تجزئة المقدار النسبي: $«0»$ إلى كسور جزئية؟", (r'\frac{x^{2}+5x+2}{(x+1)(x^{2}+1)}', (x**2+5*x+2)/((x+1)*(x**2+1)))),
  [O(r'-\frac{1}{x+1}+\frac{2x+3}{x^{2}+1}', -1/(x+1)+(2*x+3)/(x**2+1)), O(r'\frac{1}{x+1}+\frac{2x+3}{x^{2}+1}', 1/(x+1)+(2*x+3)/(x**2+1)),
   O(r'-\frac{1}{x+1}+\frac{2x-3}{x^{2}+1}', -1/(x+1)+(2*x-3)/(x**2+1)), O(r'-\frac{2}{x+1}+\frac{3x+1}{x^{2}+1}', -2/(x+1)+(3*x+1)/(x**2+1))],
  r"$x^2+5x+2=A(x^2+1)+(Bx+C)(x+1)$ ، عند $x=-1$: $-2=2A \Rightarrow A=-1$" "\n" r"معامل $x^2$: $1=A+B \Rightarrow B=2$ ، الحد الثابت: $2=A+C \Rightarrow C=3$",
  truth=(x**2+5*x+2)/((x+1)*(x**2+1)), tag='تجزئة: عامل تربيعي غير قابل للتحليل'),
Q('m2q4', U1[1], 'hard',
  r"باقي قسمة $x^{21}+3$ على $x^{2}-x$ هو:",
  [O('x+3', x+3), O('3', 3), O('4', 4), O('3x+1', 3*x+1)],
  r"$x^2-x=x(x-1)$ ، والباقي على الصورة $ax+b$: $x^{21}+3=x(x-1)q(x)+ax+b$" "\n" r"عند $x=0$: $b=3$ ، وعند $x=1$: $4=a+b \Rightarrow a=1$ ، والباقي $x+3$",
  truth=lambda: div(x**21+3, x**2-x, x)[1], tag='باقي القسمة على مقدار تربيعي'),
Q('m2q5', U2[1], 'easy',
  r"القيمة الدقيقة لـ $\cos\dfrac{7\pi}{12}$ هي:",
  [O(r'\frac{\sqrt{2}-\sqrt{6}}{4}', (sqrt(2)-sqrt(6))/4), O(r'\frac{\sqrt{6}-\sqrt{2}}{4}', (sqrt(6)-sqrt(2))/4), O(r'\frac{\sqrt{2}+\sqrt{6}}{4}', (sqrt(2)+sqrt(6))/4), O(r'-\frac{\sqrt{2}+\sqrt{6}}{4}', -(sqrt(2)+sqrt(6))/4)],
  r"$\cos\frac{7\pi}{12}=\cos\left(\frac{\pi}{3}+\frac{\pi}{4}\right)=\frac12\cdot\frac{\sqrt2}{2}-\frac{\sqrt3}{2}\cdot\frac{\sqrt2}{2}=\dfrac{\sqrt2-\sqrt6}{4}$",
  truth=cos(7*pi/12), tag='قيم دقيقة بمتطابقات المجموع والفرق'),
Q('m2q6', U2[1], 'easy',
  F(r"أيّ الآتية مكافئ للمقدار: $«0»$ ؟", (r'\tan x+\cot x', tan(x)+cot(x))),
  [O(r'\sec x\csc x', sec(x)*csc(x)), O('1', 1), O(r'\sin x\cos x', sin(x)*cos(x)), O(r'\sec^{2}x', sec(x)**2)],
  r"$\tan x+\cot x=\dfrac{\sin x}{\cos x}+\dfrac{\cos x}{\sin x}=\dfrac{\sin^2x+\cos^2x}{\sin x\cos x}=\dfrac{1}{\sin x\cos x}=\sec x\csc x$",
  truth=tan(x)+cot(x), tag='المتطابقات الأساسية'),
Q('m2q7', U2[1], 'medium',
  r"إذا كان $\sin A=-\frac{3}{5}$ حيث $\pi<A<\frac{3\pi}{2}$ ، و $\cos B=\frac{12}{13}$ حيث $\frac{3\pi}{2}<B<2\pi$ ، فإنّ قيمة $\sin(A+B)$ هي:",
  [O(r'-\frac{16}{65}', -R(16, 65)), O(r'\frac{16}{65}', R(16, 65)), O(r'-\frac{56}{65}', -R(56, 65)), O(r'\frac{56}{65}', R(56, 65))],
  r"$\cos A=-\frac45$ (الربع الثالث) ، $\sin B=-\frac{5}{13}$ (الربع الرابع)" "\n"
  r"$\sin(A+B)=\sin A\cos B+\cos A\sin B=\left(-\frac35\right)\frac{12}{13}+\left(-\frac45\right)\left(-\frac{5}{13}\right)=\frac{-36+20}{65}=-\frac{16}{65}$",
  truth=sin((pi+asin(R(3, 5))) + (2*pi-acos(R(12, 13)))), tag='المجموع والفرق بمعلومية نسب في أرباع مختلفة'),
Q('m2q8', U2[2], 'medium',
  r"إذا كان: $\sin x-\cos x=\frac{1}{2}$ ، فإنّ قيمة $\sin2x$ هي:",
  [O(r'\frac{3}{4}', R(3, 4)), O(r'\frac{1}{4}', R(1, 4)), O(r'-\frac{3}{4}', -R(3, 4)), O(r'\frac{5}{4}', R(5, 4))],
  r"بالتربيع: $\sin^2x-2\sin x\cos x+\cos^2x=\frac14 \Rightarrow 1-\sin2x=\frac14 \Rightarrow \sin2x=\frac34$",
  truth=1-R(1, 4), tag='ضعف الزاوية بالتربيع'),
IndexQ('m2q9', U2[3], 'medium',
  F(r"أحد الآتية **لا** يُعَدّ حلًّا للمعادلة: $«0»=-\sqrt{3}$", (r'\tan x', tan(x))),
  [O(r'\frac{7\pi}{3}', 7*P/3), O(r'\frac{5\pi}{3}', 5*P/3), O(r'-\frac{\pi}{3}', -P/3), O(r'\frac{8\pi}{3}', 8*P/3)],
  r"الحل العام: $x=\frac{2\pi}{3}+n\pi$" "\n" r"$\frac{5\pi}{3}=\frac{2\pi}{3}+\pi$ ✔ ، $-\frac{\pi}{3}=\frac{2\pi}{3}-\pi$ ✔ ، $\frac{8\pi}{3}=\frac{2\pi}{3}+2\pi$ ✔" "\n" r"أما $\frac{7\pi}{3}=\frac{\pi}{3}+2\pi$ فظلّها $\sqrt3$ ، إذن ليست حلًّا",
  truth=lambda vals: only(vals, lambda v_: not same(tan(v_)+sqrt(3), 0)), tag='الحل العام: أيّ القيم ليست حلًّا'),
Q('m2q10', U2[3], 'hard',
  F(r"مجموعة حلّ المعادلة: $«0»=0$ في الفترة $[0,\,2\pi)$ هي:", (r'\cos 2x+3\sin x-2', cos(2*x)+3*sin(x)-2)),
  [O(st(r'\frac{\pi}{6}', r'\frac{\pi}{2}', r'\frac{5\pi}{6}'), S_(P/6, P/2, 5*P/6), 'set'), O(st(r'\frac{\pi}{6}', r'\frac{5\pi}{6}'), S_(P/6, 5*P/6), 'set'),
   O(st(r'\frac{7\pi}{6}', r'\frac{3\pi}{2}', r'\frac{11\pi}{6}'), S_(7*P/6, 3*P/2, 11*P/6), 'set'), O(st(r'\frac{\pi}{2}'), S_(P/2), 'set')],
  r"$1-2\sin^2x+3\sin x-2=0 \Rightarrow 2\sin^2x-3\sin x+1=0 \Rightarrow (2\sin x-1)(\sin x-1)=0$" "\n" r"$\sin x=\frac12 \Rightarrow x=\frac{\pi}{6},\frac{5\pi}{6}$ ، $\sin x=1 \Rightarrow x=\frac{\pi}{2}$",
  truth=lambda: sols(cos(2*x)+3*sin(x)-2, 0, 2*pi), tag='معادلة باستعمال متطابقة ضعف الزاوية'),
Q('m2q11', U3[1], 'easy',
  F(r"إذا كان: $f(x)=«0»$ ، فإنّ $f'(1)$ تساوي:", (r'4^{x}-\log_{4}x', 4**x-log(x, 4))),
  [O(r'4\ln 4-\frac{1}{\ln 4}', 4*log(4)-1/log(4)), O(r'4-\frac{1}{4}', 4-R(1, 4)), O(r'4\ln 4-\ln 4', 3*log(4)), O(r'4\ln 4+\frac{1}{\ln 4}', 4*log(4)+1/log(4))],
  r"$f'(x)=4^x\ln4-\dfrac{1}{x\ln4} \Rightarrow f'(1)=4\ln4-\dfrac{1}{\ln4}$",
  truth=Dx(4**x-log(x, 4)).subs(x, 1), tag='مشتقة الاقتران الأسي واللوغاريتمي'),
Q('m2q12', U3[3], 'medium',
  F(r"يتحرّك جُسيم في مسار مستقيم، ويُعطى موقعه بالاقتران: $s(t)=«0»$ ، حيث $t\ge0$ بالثواني و $s$ بالأمتار. تسارع الجُسيم في اللحظة التي يكون فيها في حالة سكون لحظي هو:", (r'2t-4\ln(t+1)', 2*t-4*log(t+1))),
  [O('1', 1, units='m/s^2'), O('4', 4, units='m/s^2'), O('2', 2, units='m/s^2'), O('0', 0, units='m/s^2')],
  r"$v(t)=2-\dfrac{4}{t+1}=0 \Rightarrow t=1$" "\n" r"$a(t)=\dfrac{4}{(t+1)^2} \Rightarrow a(1)=\dfrac44=1\ \text{m/s}^2$",
  truth=lambda: diff(2*t-4*log(t+1), t, 2).subs(t, solve(diff(2*t-4*log(t+1), t), t)[0]), tag='الحركة: السرعة والتسارع'),
Q('m2q13', U3[1], 'hard',
  F(r"النقطة الواقعة على منحنى الاقتران: $y=«0»$ ، حيث $x>0$ ، والتي يكون المماس عندها موازيًا للمستقيم $y=x+1$ هي:", (r'x^{2}-3\ln x', x**2-3*log(x))),
  [O(r'(\frac{3}{2},\ \frac{9}{4}-3\ln\frac{3}{2})', Tuple(R(3, 2), R(9, 4)-3*log(R(3, 2))), 'tuple'), O(r'(1,\ 1)', Tuple(1, 1), 'tuple'),
   O(r'(\frac{3}{2},\ \frac{9}{4}+3\ln\frac{3}{2})', Tuple(R(3, 2), R(9, 4)+3*log(R(3, 2))), 'tuple'), O(r'(-1,\ 1)', Tuple(-1, 1), 'tuple')],
  r"$y'=2x-\dfrac3x=1 \Rightarrow 2x^2-x-3=0 \Rightarrow (2x-3)(x+1)=0 \Rightarrow x=\frac32$ (لأن $x>0$)" "\n" r"$y\left(\frac32\right)=\frac94-3\ln\frac32$",
  truth=lambda: (lambda r_: Tuple(r_, r_**2-3*log(r_)))([q for q in solve(Dx(x**2-3*log(x))-1, x) if q > 0][0]), tag='مماس يوازي مستقيمًا معلومًا'),
Q('m2q14', U3[2], 'easy',
  F(r"إذا كان: $f(x)=«0»$ ، فإنّ المشتقة الخامسة $f^{(5)}(x)$ تساوي:", (r'e^{-2x}', exp(-2*x))),
  [O(r'-32e^{-2x}', -32*exp(-2*x)), O(r'32e^{-2x}', 32*exp(-2*x)), O(r'-10e^{-2x}', -10*exp(-2*x)), O(r'-16e^{-2x}', -16*exp(-2*x))],
  r"كل اشتقاق يضرب في $-2$: $f^{(5)}(x)=(-2)^5e^{-2x}=-32e^{-2x}$",
  truth=diff(exp(-2*x), x, 5), tag='المشتقات العليا'),
Q('m2q15', U3[2], 'medium',
  F(r"إذا كان: $f(x)=«0»$ ، وكان: $f'(2)=-3$ ، فإنّ قيمة الثابت $a$ هي:", (r'\frac{x+a}{x-1}', (x+a)/(x-1))),
  [O('2', 2), O('-2', -2), O('4', 4), O('3', 3)],
  r"$f'(x)=\dfrac{(x-1)-(x+a)}{(x-1)^2}=\dfrac{-1-a}{(x-1)^2}$ ، إذن $f'(2)=-1-a=-3 \Rightarrow a=2$",
  truth=lambda: solve(Dx((x+a)/(x-1)).subs(x, 2)+3, a)[0], tag='إيجاد ثابت بمعلومية قيمة المشتقة'),
Q('m2q16', U3[3], 'hard',
  r"يُبيّن الشكل الآتي منحنيي الاقترانين $f(x)$ و $g(x)$. إذا كان: $h(x)=f^{2}(x)-3g(x)$ ، فإنّ $h'(5)$ تساوي:",
  [O('-9', -9), O('-3', -3), O('9', 9), O('-6', -6)],
  r"$h'(x)=2f(x)f'(x)-3g'(x)$" "\n" r"من الشكل: $f(5)=3$ ، $f'(5)=-1$ (ميل القطعة من $(3,5)$ إلى $(7,1)$) ، $g'(5)=1$ (ميل القطعة من $(2,0)$ إلى $(7,5)$)" "\n" r"$h'(5)=2(3)(-1)-3(1)=-9$",
  truth=lambda: 2*f2_16(5)*fs2_16(5)-3*gs2_16(5), figure=figure('m2q16', draw_two([(0, 2), (3, 5), (7, 1)], [(0, 4), (2, 0), (7, 5)], 7, 5, (0.4, 3.2), (5.9, 4.4))), tag='المشتقة من التمثيل البياني'),
Q('m2q17', U3[3], 'medium',
  F(r"إذا كان: $f(x)=«0»$ ، فإنّ $f'(1)$ تساوي:", (r'\ln\sqrt{x^{2}+3}', log(sqrt(x**2+3)))),
  [O(r'\frac{1}{4}', R(1, 4)), O(r'\frac{1}{2}', R(1, 2)), O(r'\frac{1}{8}', R(1, 8)), O('2', 2)],
  r"$f(x)=\frac12\ln(x^2+3) \Rightarrow f'(x)=\dfrac{x}{x^2+3} \Rightarrow f'(1)=\dfrac14$",
  truth=Dx(log(sqrt(x**2+3))).subs(x, 1), tag='قاعدة السلسلة مع اللوغاريتم'),
Q('m2q18', U3[4], 'hard',
  F(r"إذا كان: $x=«0»$ ، $y=«1»$ ، فإنّ $\dfrac{d^{2}y}{dx^{2}}$ عندما $t=1$ تساوي:", (r'2t+1', 2*t+1), (r't^{3}-12t', t**3-12*t)),
  [O(r'\frac{3}{2}', R(3, 2)), O('3', 3), O('6', 6), O(r'-\frac{9}{2}', -R(9, 2))],
  r"$\dfrac{dy}{dx}=\dfrac{3t^2-12}{2}$ ، و $\dfrac{d^2y}{dx^2}=\dfrac{\frac{d}{dt}\left(\frac{3t^2-12}{2}\right)}{dx/dt}=\dfrac{3t}{2}$ ، وعند $t=1$: $\frac32$",
  truth=(diff(diff(t**3-12*t, t)/diff(2*t+1, t), t)/diff(2*t+1, t)).subs(t, 1), tag='المشتقة الثانية للمعادلات الوسيطية'),
Q('m2q19', U3[4], 'medium',
  F(r"إذا كان: $«0»=4x$ ، فإنّ $\dfrac{d^{2}y}{dx^{2}}$ عند النقطة $(1,\,2)$ تساوي:", (r'y^{2}', y**2)),
  [O(r'-\frac{1}{2}', -R(1, 2)), O(r'\frac{1}{2}', R(1, 2)), O(r'-\frac{1}{4}', -R(1, 4)), O('-1', -1)],
  r"$2yy'=4 \Rightarrow y'=\dfrac2y=1$ عند $(1,2)$" "\n" r"$y''=-\dfrac{2y'}{y^2}=-\dfrac{2}{4}=-\dfrac12$",
  truth=imp(y**2-4*x, (1, 2), 2), tag='المشتقة الثانية بالاشتقاق الضمني'),
Q('m2q20', U3[4], 'medium',
  F(r"إذا كان: $«0»=e+1$ ، فإنّ $\dfrac{dy}{dx}$ عند النقطة $(1,\,1)$ تساوي:", (r'e^{y}+xy', exp(y)+x*y)),
  [O(r'-\frac{1}{e+1}', -1/(E+1)), O(r'\frac{1}{e+1}', 1/(E+1)), O(r'-\frac{1}{e}', -1/E), O('-e', -E)],
  r"$e^yy'+y+xy'=0 \Rightarrow y'=\dfrac{-y}{e^y+x}$ ، وعند $(1,1)$: $y'=-\dfrac{1}{e+1}$",
  truth=imp(exp(y)+x*y-E-1, (1, 1)), tag='الاشتقاق الضمني عند نقطة'),
Q('m2q21', U3[5], 'medium',
  r"يُنفَخ بالون كروي فيزداد حجمه بمعدّل $100\pi\ \text{cm}^3/\text{s}$. معدّل تزايد مساحة سطحه عندما يكون نصف قطره $5\ \text{cm}$ هو:",
  [O(r'40\pi', 40*pi, units='cm^2/s'), O(r'20\pi', 20*pi, units='cm^2/s'), O(r'100\pi', 100*pi, units='cm^2/s'), O(r'4\pi', 4*pi, units='cm^2/s')],
  r"$V=\frac43\pi r^3 \Rightarrow 100\pi=4\pi(25)\dfrac{dr}{dt} \Rightarrow \dfrac{dr}{dt}=1\ \text{cm/s}$" "\n" r"$S=4\pi r^2 \Rightarrow \dfrac{dS}{dt}=8\pi r\dfrac{dr}{dt}=8\pi(5)(1)=40\pi\ \text{cm}^2/\text{s}$",
  truth=8*pi*5*(100*pi/(4*pi*25)), tag='معدلات مرتبطة: كرة'),
Q('m2q22', U3[5], 'hard',
  r"يرتفع صاروخ رأسيًّا بسرعة $0.6\ \text{km/s}$ ، ويرصده جهاز على بُعد $3\ \text{km}$ من نقطة الإطلاق. معدّل تغيّر زاوية الارتفاع $\theta$ عندما يكون الصاروخ على ارتفاع $4\ \text{km}$ هو:",
  [D('0.072', 'rad/s'), D('0.2', 'rad/s'), D('0.12', 'rad/s'), D('0.048', 'rad/s')],
  r"$\tan\theta=\dfrac{h}{3} \Rightarrow \sec^2\theta\,\dfrac{d\theta}{dt}=\dfrac13\cdot\dfrac{dh}{dt}$" "\n"
  r"عند $h=4$: الوتر $5$ ، $\sec^2\theta=\frac{25}{9}$ ، إذن $\dfrac{d\theta}{dt}=\dfrac{0.6}{3}\cdot\dfrac{9}{25}=0.072\ \text{rad/s}$",
  truth=R(6, 10)/3*R(9, 25), tag='معدلات مرتبطة: معدل تغير زاوية'),
Q('m2q23', U4[1], 'easy',
  r"قيمة المقدار: $i^{-1}+i^{2026}$ هي:",
  [O('-1-i', -1-I), O('1-i', 1-I), O('-1+i', -1+I), O('1+i', 1+I)],
  r"$i^{-1}=\dfrac1i=\dfrac{-i}{1}=-i$ ، و $2026=4(506)+2 \Rightarrow i^{2026}=i^2=-1$ ، إذن المجموع $-1-i$",
  truth=1/I+I**2026, tag='قوى i', lead=NOTE_I(23, 30)),
Q('m2q24', U4[1], 'medium',
  r"السعة الرئيسة للعدد المُركَّب $z=(1-i)^{2}$ هي:",
  [O(r'-\frac{\pi}{2}', -P/2), O(r'\frac{\pi}{2}', P/2), O(r'\frac{3\pi}{2}', 3*P/2), O(r'-\frac{\pi}{4}', -P/4)],
  r"$z=(1-i)^2=1-2i+i^2=-2i$ ، وهو على الجزء السالب من المحور التخيلي، فالسعة الرئيسة $-\frac{\pi}{2}$ ($\frac{3\pi}{2}$ ليست ضمن المدى $(-\pi,\pi]$)",
  truth=arg(expand((1-I)**2)), tag='السعة الرئيسة'),
Q('m2q25', U4[2], 'medium',
  r"الجذران التربيعيان للعدد المُركَّب $-8+6i$ هما:",
  [O(r'\pm(1+3i)', S_(1+3*I, -1-3*I), 'set'), O(r'\pm(3+i)', S_(3+I, -3-I), 'set'), O(r'\pm(1-3i)', S_(1-3*I, -1+3*I), 'set'), O(r'\pm(3-i)', S_(3-I, -3+I), 'set')],
  r"$(a+bi)^2=-8+6i \Rightarrow a^2-b^2=-8$ ، $ab=3$ ، $a^2-\frac{9}{a^2}=-8 \Rightarrow a^4+8a^2-9=0 \Rightarrow a^2=1$" "\n" r"$a=\pm1$ ، $b=\pm3$ ، تحقق: $(1+3i)^2=1+6i-9=-8+6i$ ✔",
  truth=lambda: croots(z**2+8-6*I), tag='الجذور التربيعية للعدد المركب'),
Q('m2q26', U4[2], 'easy',
  r"المعادلة التربيعية ذات المعاملات الحقيقية التي أحد جذريها العدد المُركَّب $(3-i)$ هي:",
  [O('x^{2}-6x+10=0', x**2-6*x+10, 'rel'), O('x^{2}+6x+10=0', x**2+6*x+10, 'rel'), O('x^{2}-6x+8=0', x**2-6*x+8, 'rel'), O('x^{2}-3x+10=0', x**2-3*x+10, 'rel')],
  r"الجذر الآخر هو المرافق $3+i$ ، المجموع $6$ ، وحاصل الضرب $(3-i)(3+i)=10$" "\n" r"المعادلة: $x^2-6x+10=0$",
  truth=expand((x-(3-I))*(x-(3+I))), tag='معادلة تربيعية بمعلومية جذر مركب'),
Q('m2q27', U4[2], 'medium',
  r"إذا كان: $z=8\left(\cos\frac{\pi}{12}+i\sin\frac{\pi}{12}\right)$ ، $w=2\left(\cos\left(-\frac{\pi}{4}\right)+i\sin\left(-\frac{\pi}{4}\right)\right)$ ، فإنّ الصورة القياسية لناتج $\dfrac{z}{w}$ هي:",
  [O(r'2+2\sqrt{3}i', 2+2*sqrt(3)*I), O(r'2\sqrt{3}+2i', 2*sqrt(3)+2*I), O(r'-2+2\sqrt{3}i', -2+2*sqrt(3)*I), O(r'2-2\sqrt{3}i', 2-2*sqrt(3)*I)],
  r"$\dfrac{z}{w}=4\left(\cos\left(\frac{\pi}{12}+\frac{\pi}{4}\right)+i\sin\left(\frac{\pi}{12}+\frac{\pi}{4}\right)\right)=4\left(\cos\frac{\pi}{3}+i\sin\frac{\pi}{3}\right)=2+2\sqrt3\,i$",
  truth=expand(pol(8, pi/12)/pol(2, -pi/4)), tag='الضرب والقسمة بالصورة المثلثية'),
Q('m2q28', U4[1], 'medium',
  r"إذا كان: $z-2\bar{z}=3+6i$ ، فإنّ العدد المُركَّب $z$ هو:",
  [O('-3+2i', -3+2*I), O('3+2i', 3+2*I), O('-3-2i', -3-2*I), O('3-6i', 3-6*I)],
  r"نفرض $z=x+iy$: $(x+iy)-2(x-iy)=-x+3iy=3+6i$" "\n" r"$-x=3 \Rightarrow x=-3$ ، $3y=6 \Rightarrow y=2$ ، إذن $z=-3+2i$",
  truth=lambda: (lambda s_: s_[X]+I*s_[Y])(solve([re(expand(X+I*Y-2*(X-I*Y)-3-6*I)), im(expand(X+I*Y-2*(X-I*Y)-3-6*I))], [X, Y])), tag='معادلة فيها العدد ومرافقه'),
Q('m2q29', U4[3], 'hard',
  r"الأعداد المُركَّبة $z$ التي تُحقّق المعادلتين: $|z-2i|=|z+2|$ و $|z|=2$ معًا هي:",
  [O(r'\sqrt{2}-\sqrt{2}i,\ -\sqrt{2}+\sqrt{2}i', S_(sqrt(2)-sqrt(2)*I, -sqrt(2)+sqrt(2)*I), 'set'), O(r'\sqrt{2}+\sqrt{2}i,\ -\sqrt{2}-\sqrt{2}i', S_(sqrt(2)+sqrt(2)*I, -sqrt(2)-sqrt(2)*I), 'set'),
   O(r'2-2i,\ -2+2i', S_(2-2*I, -2+2*I), 'set'), O(r'\sqrt{2}-\sqrt{2}i', S_(sqrt(2)-sqrt(2)*I), 'set')],
  r"$|z-2i|=|z+2|$: العمود المنصّف للقطعة بين $(0,2)$ و $(-2,0)$: $x^2+(y-2)^2=(x+2)^2+y^2 \Rightarrow y=-x$" "\n"
  r"مع $|z|=2$: $x^2+x^2=4 \Rightarrow x=\pm\sqrt2$ ، فالعددان: $\sqrt2-\sqrt2\,i$ و $-\sqrt2+\sqrt2\,i$",
  truth=lambda: FiniteSet(*[sx+I*sy for sx, sy in solve([Eq(X**2+(Y-2)**2, (X+2)**2+Y**2), X**2+Y**2-4], [X, Y])]), tag='تقاطع محلين هندسيين'),
Q('m2q30', U4[3], 'hard',
  r"نظام المتباينات (بدلالة $z$) الذي يُمثّل المحل الهندسي المُمثَّل بالمنطقة المُظلَّلة في الشكل الآتي (الخط الرأسي هو العمود المنصّف للقطعة الواصلة بين نقطة الأصل والنقطة $(2,0)$) هو:",
  [T(r'$|z|\le3$ ، $|z-2|\le|z|$'), T(r'$|z|\le3$ ، $|z-2|\ge|z|$'), T(r'$|z|\ge3$ ، $|z-2|\le|z|$'), T(r'$|z-2|\le3$ ، $|z-2|\le|z|$')],
  r"المنطقة داخل الدائرة التي مركزها الأصل ونصف قطرها $3$: $|z|\le3$" "\n"
  r"وتقع على يمين العمود المنصّف $x=1$ ، أي أقرب إلى النقطة $2$ منها إلى الأصل: $|z-2|\le|z|$ (الخطوط متصلة فتشمل المساواة)",
  manual='region drawn: inside |z|<=3 and x>=1 (closer to 2 than to 0)', figure=figure('m2q30', fig_region('disk_right'), 3.4, 3.4), tag='منطقة في المستوى المركب من الشكل'),
]
# ================================================================== PAPER 3
f3_16, fs3_16 = pw([(0, 0), (3, 6), (6, 3)])
g3_16, gs3_16 = pw([(0, 5), (4, 1), (6, 3)])
V3 = x**3 + 6*x**2 + 3*x - 10
P3 = [
Q('m3q1', U1[1], 'medium',
  F(r"عند قسمة $f(x)=«0»$ على $(3x-2)$ ، فإنّ ناتج القسمة $q(x)$ والباقي $r$ هما:", (r'6x^{3}-x^{2}+4x-3', 6*x**3-x**2+4*x-3)),
  [O(r'q(x)=2x^{2}+x+2,\ r=1', Tuple(2*x**2+x+2, 1), 'pairs'), O(r'q(x)=6x^{2}+3x+6,\ r=1', Tuple(6*x**2+3*x+6, 1), 'pairs'),
   O(r'q(x)=2x^{2}+x+2,\ r=3', Tuple(2*x**2+x+2, 3), 'pairs'), O(r'q(x)=2x^{2}-x+2,\ r=1', Tuple(2*x**2-x+2, 1), 'pairs')],
  r"نقسم قسمةً تركيبية على $x=\frac23$: $6,\ -1,\ 4,\ -3 \to 6,\ 3,\ 6$ والباقي $1$" "\n"
  r"ناتج القسمة على $\left(x-\frac23\right)$ هو $6x^2+3x+6$ ، وبما أن $3x-2=3\left(x-\frac23\right)$ نقسمه على $3$: $q(x)=2x^2+x+2$ ، والباقي $1$",
  truth=lambda: Tuple(*div(6*x**3-x**2+4*x-3, 3*x-2, x)), tag='القسمة التركيبية على (ax−b)'),
Q('m3q2', U1[1], 'medium',
  F(r"يُمثّل الاقتران: $V(x)=«0»$ حجم صندوق على شكل متوازي مستطيلات. إذا كان ارتفاع الصندوق $(x-1)$ ، فإنّ البعدين الآخرين له هما:", (r'x^{3}+6x^{2}+3x-10', V3)),
  [T(r'$(x+2)$ و $(x+5)$', (x+2)*(x+5)), T(r'$(x-2)$ و $(x-5)$', (x-2)*(x-5)), T(r'$(x+1)$ و $(x+10)$', (x+1)*(x+10)), T(r'$(x+2)$ و $(x+3)$', (x+2)*(x+3))],
  r"بالقسمة التركيبية على $(x-1)$: $1,\ 6,\ 3,\ -10 \to 1,\ 7,\ 10,\ 0$" "\n" r"$x^2+7x+10=(x+2)(x+5)$",
  truth=lambda: cancel(V3/(x-1)), tag='تطبيق حياتي على نظرية العوامل'),
Q('m3q3', U1[2], 'hard',
  F(r"المقدار: $«0»$ يساوي:", (r'\frac{x^{3}-2x^{2}+3}{x^{2}-x}', (x**3-2*x**2+3)/(x**2-x))),
  [O(r'x-1-\frac{3}{x}+\frac{2}{x-1}', x-1-3/x+2/(x-1)), O(r'x-1+\frac{3}{x}-\frac{2}{x-1}', x-1+3/x-2/(x-1)),
   O(r'x+1-\frac{3}{x}+\frac{2}{x-1}', x+1-3/x+2/(x-1)), O(r'-\frac{3}{x}+\frac{2}{x-1}', -3/x+2/(x-1))],
  r"بالقسمة الطويلة: $x^3-2x^2+3=(x^2-x)(x-1)+(-x+3)$" "\n"
  r"$\dfrac{-x+3}{x(x-1)}=\dfrac{A}{x}+\dfrac{B}{x-1}$ ، عند $x=0$: $A=-3$ ، عند $x=1$: $B=2$",
  truth=(x**3-2*x**2+3)/(x**2-x), tag='تجزئة: كسر غير فعلي'),
Q('m3q4', U1[2], 'medium',
  F(r"إذا كان: $«0»=\dfrac{A}{x}+\dfrac{B}{x-1}+\dfrac{C}{x+1}$ ، فإنّ قيمة $ABC$ هي:", (r'\frac{x^{2}+4x+1}{x^{3}-x}', (x**2+4*x+1)/(x**3-x))),
  [O('3', 3), O('-3', -3), O('1', 1), O('6', 6)],
  r"$x^3-x=x(x-1)(x+1)$ ، و $x^2+4x+1=A(x-1)(x+1)+Bx(x+1)+Cx(x-1)$" "\n"
  r"عند $x=0$: $1=-A \Rightarrow A=-1$ ، عند $x=1$: $6=2B \Rightarrow B=3$ ، عند $x=-1$: $-2=2C \Rightarrow C=-1$" "\n" r"$ABC=(-1)(3)(-1)=3$",
  truth=lambda: (lambda F_: F_.subs(x, 0))(cancel((x**2+4*x+1)/((x-1)*(x+1)))) * cancel((x**2+4*x+1)/(x*(x+1))).subs(x, 1) * cancel((x**2+4*x+1)/(x*(x-1))).subs(x, -1),
  tag='إيجاد ثوابت في التجزئة'),
IndexQ('m3q5', U2[1], 'easy',
  r"إحدى المعادلات الآتية **ليست** متطابقة:",
  [O(r'\tan(\pi-x)=\tan x', tan(pi-x)-tan(x), 'rel'), O(r'\cos(\pi-x)=-\cos x', cos(pi-x)+cos(x), 'rel'),
   O(r'\sin(\pi+x)=-\sin x', sin(pi+x)+sin(x), 'rel'), O(r'\cot(-x)=-\cot x', cot(-x)+cot(x), 'rel')],
  r"$\tan(\pi-x)=\dfrac{\sin(\pi-x)}{\cos(\pi-x)}=\dfrac{\sin x}{-\cos x}=-\tan x$ ، فالمعادلة $\tan(\pi-x)=\tan x$ ليست متطابقة" "\n" r"أما البقية فمتطابقات صحيحة.",
  truth=lambda vals: only(vals, lambda d_: not same(d_, 0)), tag='المتطابقات: الزوايا المنتسبة والزوجية والفردية'),
Q('m3q6', U2[1], 'hard',
  F(r"أبسط صورة للمقدار: $«0»$ هي:", (r'\tan(\frac{\pi}{4}+x)-\tan(\frac{\pi}{4}-x)', tan(pi/4+x)-tan(pi/4-x))),
  [O(r'2\tan 2x', 2*tan(2*x)), O(r'\tan 2x', tan(2*x)), O(r'2\tan x', 2*tan(x)), O('0', 0)],
  r"نفرض $t=\tan x$: $\dfrac{1+t}{1-t}-\dfrac{1-t}{1+t}=\dfrac{(1+t)^2-(1-t)^2}{1-t^2}=\dfrac{4t}{1-t^2}$" "\n" r"$=2\cdot\dfrac{2\tan x}{1-\tan^2x}=2\tan2x$",
  truth=tan(pi/4+x)-tan(pi/4-x), tag='تبسيط باستعمال متطابقات المجموع والفرق'),
Q('m3q7', U2[2], 'medium',
  r"إذا كان $\sin\theta=-\frac{4}{5}$ ، حيث $\pi<\theta<\frac{3\pi}{2}$ ، فإنّ قيمة $\tan\frac{\theta}{2}$ تساوي:",
  [O('-2', -2), O('2', 2), O(r'-\frac{1}{2}', -R(1, 2)), O(r'\frac{1}{2}', R(1, 2))],
  r"$\cos\theta=-\frac35$ ، و $\frac{\pi}{2}<\frac{\theta}{2}<\frac{3\pi}{4}$ فالظل سالب" "\n"
  r"$\tan\frac{\theta}{2}=\dfrac{\sin\theta}{1+\cos\theta}=\dfrac{-\frac45}{\frac25}=-2$",
  truth=tan((pi+asin(R(4, 5)))/2), tag='نصف الزاوية مع تحديد الربع'),
Q('m3q8', U2[2], 'medium',
  r"قيمة المقدار: $\sin105^\circ\cos15^\circ$ هي:",
  [O(r'\frac{2+\sqrt{3}}{4}', (2+sqrt(3))/4), O(r'\frac{2-\sqrt{3}}{4}', (2-sqrt(3))/4), O(r'\frac{1+\sqrt{3}}{4}', (1+sqrt(3))/4), O(r'\frac{\sqrt{3}}{4}', sqrt(3)/4)],
  r"$\sin A\cos B=\frac12[\sin(A+B)+\sin(A-B)]=\frac12[\sin120^\circ+\sin90^\circ]=\frac12\left(\frac{\sqrt3}{2}+1\right)=\dfrac{2+\sqrt3}{4}$",
  truth=sin(deg(105))*cos(deg(15)), tag='تحويل الضرب إلى مجموع'),
Q('m3q9', U2[3], 'medium',
  F(r"عدد حلول المعادلة: $«0»=«1»$ في الفترة $[0,\,2\pi]$ هو:", (r'2\cos^{2}x', 2*cos(x)**2), (r'1+\cos x', 1+cos(x))),
  [O('4', 4), O('3', 3), O('2', 2), O('5', 5)],
  r"$2\cos^2x-\cos x-1=0 \Rightarrow (2\cos x+1)(\cos x-1)=0$" "\n"
  r"$\cos x=1 \Rightarrow x=0,\ 2\pi$ (الفترة مغلقة) ، $\cos x=-\frac12 \Rightarrow x=\frac{2\pi}{3},\ \frac{4\pi}{3}$ ، إذن $4$ حلول",
  truth=lambda: len(sols(2*cos(x)**2-1-cos(x), 0, 2*pi, closed_hi=True)), tag='عدد الحلول في فترة مغلقة'),
Q('m3q10', U2[3], 'medium',
  F(r"مجموعة حلّ المعادلة: $«0»=\frac{1}{2}$ في الفترة $[0,\,4\pi)$ هي:", (r'\cos\frac{x}{2}', cos(x/2))),
  [O(st(r'\frac{2\pi}{3}', r'\frac{10\pi}{3}'), S_(2*P/3, 10*P/3), 'set'), O(st(r'\frac{\pi}{3}', r'\frac{5\pi}{3}'), S_(P/3, 5*P/3), 'set'),
   O(st(r'\frac{2\pi}{3}', r'\frac{4\pi}{3}'), S_(2*P/3, 4*P/3), 'set'), O(st(r'\frac{2\pi}{3}'), S_(2*P/3), 'set')],
  r"بما أن $0\le x<4\pi$ فإن $0\le\frac{x}{2}<2\pi$: $\frac{x}{2}=\frac{\pi}{3}$ أو $\frac{x}{2}=\frac{5\pi}{3}$" "\n" r"إذن $x=\frac{2\pi}{3}$ أو $x=\frac{10\pi}{3}$",
  truth=lambda: sols(cos(x/2)-R(1, 2), 0, 4*pi), tag='معادلة بنصف الزاوية'),
Q('m3q11', U3[1], 'easy',
  F(r"إذا كان: $f(x)=«0»$ ، فإنّ $f'(1)$ تساوي:", (r'x^{e}+e^{x}', x**E+exp(x))),
  [O('2e', 2*E), O('e', E), O('e+1', E+1), O(r'e^{2}', E**2)],
  r"$f'(x)=ex^{e-1}+e^x \Rightarrow f'(1)=e+e=2e$",
  truth=Dx(x**E+exp(x)).subs(x, 1), tag='مشتقة الاقتران الأسي والقوة'),
Q('m3q12', U3[3], 'medium',
  F(r"إذا كان: $f(x)=«0»$ ، حيث $0<x<\frac{\pi}{2}$ ، فإنّ $f''(x)-\big(f'(x)\big)^{2}$ يساوي:", (r'\ln(\sec x)', log(sec(x)))),
  [O('1', 1), O('0', 0), O(r'\sec^{2}x', sec(x)**2), O(r'2\tan^{2}x', 2*tan(x)**2)],
  r"$f'(x)=\dfrac{\sec x\tan x}{\sec x}=\tan x$ ، $f''(x)=\sec^2x$" "\n" r"$f''-(f')^2=\sec^2x-\tan^2x=1$",
  truth=diff(log(sec(x)), x, 2)-Dx(log(sec(x)))**2, tag='المشتقات العليا وتراكيبها'),
Q('m3q13', U3[1], 'hard',
  F(r"معادلة المماس لمنحنى الاقتران: $y=«0»$ ، والمارّ بنقطة الأصل، هي:", (r'\ln x', log(x))),
  [O(r'y=\frac{1}{e}x', x/E, 'eq'), O(r'y=x-1', x-1, 'eq'), O(r'y=ex', E*x, 'eq'), O(r'y=\frac{1}{e}x+1', x/E+1, 'eq')],
  r"نفرض نقطة التماس $(a,\ln a)$ ، والميل $\frac1a$: $y-\ln a=\frac1a(x-a)$" "\n" r"يمرّ بالأصل: $-\ln a=-1 \Rightarrow a=e$ ، فالمماس: $y-1=\frac1e(x-e) \Rightarrow y=\frac1ex$",
  truth=lambda: (lambda a0: log(a0)+(x-a0)/a0)(solve(-log(a)+1, a)[0]), tag='مماس من نقطة خارج المنحنى'),
Q('m3q14', U3[1], 'easy',
  F(r"يتحرّك جُسيم في مسار مستقيم، ويُعطى موقعه بالاقتران: $s(t)=«0»$ ، حيث $t$ بالثواني و $s$ بالأمتار. سرعة الجُسيم المتجهة عندما $t=\frac{1}{3}$ هي:", (r'\sin(\pi t)+t', sin(pi*t)+t)),
  [O(r'\frac{\pi}{2}+1', pi/2+1, units='m/s'), O(r'\frac{\pi}{2}', pi/2, units='m/s'), O(r'\frac{\sqrt{3}\pi}{2}+1', sqrt(3)*pi/2+1, units='m/s'), O(r'\pi+1', pi+1, units='m/s')],
  r"$v(t)=\pi\cos(\pi t)+1 \Rightarrow v\left(\frac13\right)=\pi\cos\frac{\pi}{3}+1=\frac{\pi}{2}+1$",
  truth=diff(sin(pi*t)+t, t).subs(t, R(1, 3)), tag='الحركة: السرعة والتسارع'),
Q('m3q15', U3[2], 'medium',
  F(r"إذا كان: $f(x)=«0»$ ، وكان: $f''(0)=6$ ، فإنّ قيمة الثابت $a$ هي:", (r'axe^{x}', a*x*exp(x))),
  [O('3', 3), O('6', 6), O('2', 2), O(r'\frac{1}{3}', R(1, 3))],
  r"$f'(x)=ae^x(1+x)$ ، $f''(x)=ae^x(2+x)$ ، إذن $f''(0)=2a=6 \Rightarrow a=3$",
  truth=lambda: solve(diff(a*x*exp(x), x, 2).subs(x, 0)-6, a)[0], tag='إيجاد ثابت بمعلومية قيمة المشتقة'),
Q('m3q16', U3[3], 'medium',
  r"يُبيّن الشكل الآتي منحنيي الاقترانين $f(x)$ و $g(x)$. إذا كان: $p(x)=f\big(g(x)\big)$ ، فإنّ $p'(5)$ تساوي:",
  [O('2', 2), O('-2', -2), O('4', 4), O('1', 1)],
  r"$p'(5)=f'\big(g(5)\big)\cdot g'(5)$" "\n" r"من الشكل: $g(5)=2$ ، $g'(5)=1$ (ميل القطعة من $(4,1)$ إلى $(6,3)$) ، $f'(2)=2$ (ميل القطعة من $(0,0)$ إلى $(3,6)$)" "\n" r"$p'(5)=2(1)=2$",
  truth=lambda: fs3_16(g3_16(5))*gs3_16(5), figure=figure('m3q16', draw_two([(0, 0), (3, 6), (6, 3)], [(0, 5), (4, 1), (6, 3)], 6, 6, (1.1, 5.6), (0.2, 5.3))), tag='المشتقة من التمثيل البياني'),
Q('m3q17', U3[3], 'medium',
  F(r"إذا كان: $f(x)=«0»$ ، حيث $0<x<\frac{\pi}{2}$ ، فإنّ $f'\left(\frac{\pi}{4}\right)$ تساوي:", (r'\log_{2}(\cos x)', log(cos(x), 2))),
  [O(r'-\frac{1}{\ln 2}', -1/log(2)), O(r'\frac{1}{\ln 2}', 1/log(2)), O(r'-\ln 2', -log(2)), O(r'-\frac{\sqrt{2}}{\ln 2}', -sqrt(2)/log(2))],
  r"$f'(x)=\dfrac{-\sin x}{\cos x\,\ln2}=-\dfrac{\tan x}{\ln2} \Rightarrow f'\left(\frac{\pi}{4}\right)=-\dfrac{1}{\ln2}$",
  truth=Dx(log(cos(x), 2)).subs(x, pi/4), tag='مشتقة اللوغاريتم لأساس غير e'),
Q('m3q18', U3[3], 'easy',
  F(r"يُمثّل الاقتران: $P(t)=«0»$ عدد سكان مدينة (بالآلاف) بعد $t$ سنة. معدّل تغيّر عدد السكان (ألف نسمة/سنة) عندما $t=20$ هو:", (r'1000e^{0.05t}', 1000*exp(R(5, 100)*t))),
  [O('50e', 50*E), O('1000e', 1000*E), O('50', 50), O('20e', 20*E)],
  r"$P'(t)=1000(0.05)e^{0.05t}=50e^{0.05t}$ ، إذن $P'(20)=50e^{1}=50e$",
  truth=diff(1000*exp(R(5, 100)*t), t).subs(t, 20), tag='معدل التغير في سياق حياتي'),
Q('m3q19', U3[3], 'medium',
  F(r"معادلة المماس لمنحنى المعادلتين الوسيطيتين: $x=«0»$ ، $y=«1»$ عندما $t=0$ هي:", (r'e^{t}+1', exp(t)+1), (r'e^{2t}', exp(2*t))),
  [O('y=2x-3', 2*x-3, 'eq'), O('y=2x+1', 2*x+1, 'eq'), O('y=2x-1', 2*x-1, 'eq'), O(r'y=\frac{1}{2}x', x/2, 'eq')],
  r"عند $t=0$: النقطة $(2,\,1)$ ، و $\dfrac{dy}{dx}=\dfrac{2e^{2t}}{e^t}=2e^t=2$" "\n" r"المماس: $y-1=2(x-2) \Rightarrow y=2x-3$",
  truth=1 + (diff(exp(2*t), t)/diff(exp(t)+1, t)).subs(t, 0)*(x-2), tag='مماس منحنى وسيطي'),
Q('m3q20', U3[4], 'hard',
  F(r"مساحة المثلث المحصور بين المحورين الإحداثيين والمماس لمنحنى العلاقة: $«0»=4$ عند النقطة $(2,\,2)$ تساوي:", (r'xy', x*y)),
  [O('8', 8), O('4', 4), O('16', 16), O('2', 2)],
  r"$y+xy'=0 \Rightarrow y'=-\dfrac{y}{x}=-1$ عند $(2,2)$ ، فالمماس: $y-2=-(x-2) \Rightarrow x+y=4$" "\n" r"المقطعان $4$ و $4$ ، والمساحة $=\frac12(4)(4)=8$ وحدات مربعة",
  truth=lambda: (lambda tl: R(1, 2)*tl.subs(x, 0)*solve(tl, x)[0])(2 + imp(x*y-4, (2, 2))*(x-2)), tag='مساحة مثلث يصنعه المماس مع المحورين'),
Q('m3q21', U3[4], 'medium',
  F(r"إذا كان: $«0»=4$ ، فإنّ $\dfrac{dy}{dx}$ عند النقطة $(0,\,2)$ تساوي:", (r'x\ln y+y^{2}', x*log(y)+y**2)),
  [O(r'-\frac{\ln 2}{4}', -log(2)/4), O(r'\frac{\ln 2}{4}', log(2)/4), O(r'-\ln 2', -log(2)), O(r'-\frac{1}{4}', -R(1, 4))],
  r"باشتقاق الطرفين: $\ln y+\dfrac{x}{y}y'+2yy'=0$ ، وعند $(0,2)$: $\ln2+0+4y'=0 \Rightarrow y'=-\dfrac{\ln2}{4}$",
  truth=imp(x*log(y)+y**2-4, (0, 2)), tag='الاشتقاق الضمني عند نقطة'),
Q('m3q22', U3[5], 'easy',
  r"أُلقي حجر في بركة ماء ساكن فتكوّنت موجة دائرية يزداد نصف قطرها بمعدّل $3\ \text{cm/s}$. معدّل تزايد المساحة داخل الموجة في اللحظة التي يكون فيها محيطها $12\pi\ \text{cm}$ هو:",
  [O(r'36\pi', 36*pi, units='cm^2/s'), O(r'18\pi', 18*pi, units='cm^2/s'), O(r'108\pi', 108*pi, units='cm^2/s'), O(r'12\pi', 12*pi, units='cm^2/s')],
  r"المحيط $2\pi r=12\pi \Rightarrow r=6$" "\n" r"$\dfrac{dA}{dt}=2\pi r\dfrac{dr}{dt}=2\pi(6)(3)=36\pi\ \text{cm}^2/\text{s}$",
  truth=2*pi*6*3, tag='معدلات مرتبطة: دائرة'),
Q('m3q23', U4[1], 'medium',
  r"إذا كان: $z=-3+bi$ ، حيث $b<0$ ، وكان: $|z|=6$ ، فإنّ الصورة المثلثية للعدد المُركَّب $z$ هي:",
  [O(trig('6', r'-\frac{2\pi}{3}'), pol(6, -2*P/3)), O(trig('6', r'\frac{2\pi}{3}'), pol(6, 2*P/3)), O(trig('6', r'-\frac{\pi}{3}'), pol(6, -P/3)), O(trig('6', r'-\frac{5\pi}{6}'), pol(6, -5*P/6))],
  r"$9+b^2=36 \Rightarrow b=-3\sqrt3$ (لأن $b<0$) ، فيكون $z=-3-3\sqrt3\,i$ في الربع الثالث" "\n" r"زاوية الإسناد $\tan^{-1}\sqrt3=\frac{\pi}{3}$ ، و $\text{Arg}(z)=-\pi+\frac{\pi}{3}=-\frac{2\pi}{3}$",
  truth=lambda: -3 + I*[r_ for r_ in solve(9+b**2-36, b) if r_ < 0][0], tag='الصورة المثلثية بشروط', lead=NOTE_I(23, 30)),
Q('m3q24', U4[1], 'medium',
  r"إذا كان: $z=\dfrac{a+3i}{2-i}$ ، فإنّ قيمة الثابت الحقيقي $a$ التي تجعل $z$ عددًا حقيقيًّا هي:",
  [O('-6', -6), O('6', 6), O(r'-\frac{3}{2}', -R(3, 2)), O(r'\frac{3}{2}', R(3, 2))],
  r"$z=\dfrac{(a+3i)(2+i)}{5}=\dfrac{2a+ai+6i-3}{5}=\dfrac{(2a-3)+(a+6)i}{5}$" "\n" r"يكون حقيقيًّا إذا انعدم الجزء التخيلي: $a+6=0 \Rightarrow a=-6$",
  truth=lambda: solve(im(expand((X+3*I)*(2+I))), X)[0], tag='قيمة ثابت تجعل العدد حقيقيًا أو تخيليًا'),
Q('m3q25', U4[2], 'hard',
  r"إذا كان العدد $1+i$ أحد جذور المعادلة: $z^{3}-4z^{2}+6z-4=0$ ، فإنّ مجموعة حلّ المعادلة هي:",
  [O(r'\{1+i,\ 1-i,\ 2\}', S_(1+I, 1-I, 2), 'set'), O(r'\{1+i,\ 1-i,\ -2\}', S_(1+I, 1-I, -2), 'set'), O(r'\{1+i,\ -1-i,\ 2\}', S_(1+I, -1-I, 2), 'set'), O(r'\{1+i,\ 1-i,\ 4\}', S_(1+I, 1-I, 4), 'set')],
  r"المرافق $1-i$ جذر أيضًا، و $(z-1-i)(z-1+i)=z^2-2z+2$" "\n" r"$z^3-4z^2+6z-4=(z^2-2z+2)(z-2)$ ، فالجذر الثالث $2$",
  truth=lambda: croots(z**3-4*z**2+6*z-4), tag='معادلة كثير حدود بجذر مركب'),
Q('m3q26', U4[1], 'easy',
  r"قيمة $|z-w|$ هي:",
  [O(r'\sqrt{10}', sqrt(10)), O(r'\sqrt{26}', sqrt(26)), O('4', 4), O(r'\sqrt{13}-\sqrt{5}', sqrt(13)-sqrt(5))],
  r"$z-w=(2+3i)-(-1+2i)=3+i$ ، و $|3+i|=\sqrt{9+1}=\sqrt{10}$",
  truth=Abs((2+3*I)-(-1+2*I)), tag='المقياس والعمليات (نص مشترك)', lead=shared(r"إذا كان: $z=2+3i$ ، $w=-1+2i$", 26, 27)),
Q('m3q27', U4[2], 'medium',
  r"الجزء الحقيقي للعدد $z\bar{w}$ هو:",
  [O('4', 4), O('-8', -8), O('-7', -7), O('8', 8)],
  r"$\bar w=-1-2i$ ، و $z\bar w=(2+3i)(-1-2i)=-2-4i-3i-6i^2=4-7i$ ، فالجزء الحقيقي $4$",
  truth=re(expand((2+3*I)*(-1-2*I))), tag='المقياس والعمليات (نص مشترك)'),
Q('m3q28', U4[2], 'hard',
  r"إذا كان: $z_1=2i$ ، $z_2=-\sqrt{3}-i$ ، فإنّ قياس الزاوية الصغرى المحصورة بين $z_1$ و $z_2$ هو:",
  [O(r'\frac{2\pi}{3}', 2*P/3), O(r'\frac{4\pi}{3}', 4*P/3), O(r'\frac{\pi}{3}', P/3), O(r'\frac{5\pi}{6}', 5*P/6)],
  r"$\text{Arg}(z_1)=\frac{\pi}{2}$ ، $\text{Arg}(z_2)=-\frac{5\pi}{6}$ ، والفرق $\frac{\pi}{2}+\frac{5\pi}{6}=\frac{4\pi}{3}>\pi$" "\n" r"فالزاوية الصغرى $2\pi-\frac{4\pi}{3}=\frac{2\pi}{3}$",
  truth=acos(re(expand(2*I*conjugate(-sqrt(3)-I)))/(2*Abs(-sqrt(3)-I))), tag='الزاوية بين عددين مركبين'),
IndexQ('m3q29', U4[3], 'medium',
  r"أيّ الأعداد المُركَّبة الآتية يقع على المحل الهندسي: $\text{Arg}(z-2+i)=-\dfrac{\pi}{4}$ ؟",
  [O('3-2i', 3-2*I), O('2-i', 2-I), O('1', 1), O('3', 3)],
  r"المحل شعاع يبدأ بالنقطة $(2,-1)$ (لا يشملها) ويصنع زاوية $-\frac{\pi}{4}$" "\n"
  r"$3-2i-2+i=1-i$ وسعته $-\frac{\pi}{4}$ ✔ ، أما $2-i$ فهي بداية الشعاع (غير مشمولة) ، و $1$: $-1+i$ سعته $\frac{3\pi}{4}$ ، و $3$: $1+i$ سعته $\frac{\pi}{4}$",
  truth=lambda vals: only(vals, lambda w_: simplify(w_-2+I) != 0 and same(arg(w_-2+I), -pi/4)), tag='المحل الهندسي: الشعاع'),
Q('m3q30', U4[3], 'hard',
  r"نظام المتباينات (بدلالة $z$) الذي يُمثّل المحل الهندسي المُمثَّل بالمنطقة المُظلَّلة في الشكل الآتي هو:",
  [T(r'$1<|z|\le3$ ، $0\le\text{Arg}(z)\le\frac{\pi}{2}$'), T(r'$1\le|z|<3$ ، $0\le\text{Arg}(z)\le\frac{\pi}{2}$'), T(r'$1<|z|\le3$ ، $0<\text{Arg}(z)<\frac{\pi}{2}$'), T(r'$|z|\le3$ ، $0\le\text{Arg}(z)\le\frac{\pi}{2}$')],
  r"المنطقة بين دائرتين مركزهما الأصل: الداخلية نصف قطرها $1$ مرسومة بخط متقطّع (غير مشمولة) والخارجية نصف قطرها $3$ بخط متصل (مشمولة): $1<|z|\le3$" "\n"
  r"وهي في الربع الأول بين المحورين الموجبين المرسومين بخط متصل: $0\le\text{Arg}(z)\le\frac{\pi}{2}$",
  manual='quarter annulus 1<|z|<=3 first quadrant, inner dashed', figure=figure('m3q30', fig_region('quarter_ring'), 3.4, 3.4), tag='منطقة في المستوى المركب من الشكل'),
]
# ================================================================== PAPER 4
f4_16, fs4_16 = pw([(0, 3), (2, 1), (6, 5)])
g4_16, gs4_16 = pw([(0, 0), (3, 6), (6, 3)])
g42 = 2*x**3 + a*x**2 + b*x - 6
P4 = [
Q('m4q1', U1[1], 'easy',
  F(r"إذا كان $x=\frac{1}{2}$ حلًّا للمعادلة: $«0»=0$ ، فإنّ لها حلّين آخرين هما:", (r'2x^{3}-3x^{2}-3x+2', 2*x**3-3*x**2-3*x+2)),
  [O(r'x=2,\ x=-1', S_(2, -1), 'set'), O(r'x=-2,\ x=1', S_(-2, 1), 'set'), O(r'x=2,\ x=1', S_(2, 1), 'set'), O(r'x=-2,\ x=-1', S_(-2, -1), 'set')],
  r"بالقسمة التركيبية على $\left(x-\frac12\right)$: $2,\ -3,\ -3,\ 2 \to 2,\ -2,\ -4,\ 0$" "\n" r"$2x^2-2x-4=2(x-2)(x+1)=0 \Rightarrow x=2$ أو $x=-1$",
  truth=lambda: other_roots(2*x**3-3*x**2-3*x+2, R(1, 2)), tag='حل معادلة كثير حدود بمعلومية أحد جذورها'),
Q('m4q2', U1[1], 'hard',
  F(r"إذا كان الاقتران: $f(x)=«0»$ يقبل القسمة على $x^{2}-x-2$ ، فإنّ قيمة الثابت $b$ هي:", (r'2x^{3}+ax^{2}+bx-6', g42)),
  [O('-7', -7), O('7', 7), O('1', 1), O('-5', -5)],
  r"$x^2-x-2=(x-2)(x+1)$ ، فكلٌّ من $(x-2)$ و $(x+1)$ عامل:" "\n"
  r"$f(2)=16+4a+2b-6=0 \Rightarrow 2a+b=-5$ ، $f(-1)=-2+a-b-6=0 \Rightarrow a-b=8$" "\n" r"بالجمع: $3a=3 \Rightarrow a=1$ ، و $b=-7$",
  truth=lambda: solve([rem(g42, 2), rem(g42, -1)], [a, b])[b], tag='نظرية العوامل وإيجاد ثابتين'),
Q('m4q3', U1[2], 'easy',
  F(r"أيّ الآتية يُمثّل تجزئة المقدار النسبي: $«0»$ إلى كسور جزئية؟", (r'\frac{x+14}{x^{2}-4}', (x+14)/(x**2-4))),
  [O(r'\frac{4}{x-2}-\frac{3}{x+2}', 4/(x-2)-3/(x+2)), O(r'\frac{3}{x-2}-\frac{4}{x+2}', 3/(x-2)-4/(x+2)), O(r'\frac{4}{x-2}+\frac{3}{x+2}', 4/(x-2)+3/(x+2)), O(r'-\frac{4}{x-2}+\frac{3}{x+2}', -4/(x-2)+3/(x+2))],
  r"$x+14=A(x+2)+B(x-2)$ ، عند $x=2$: $16=4A \Rightarrow A=4$ ، عند $x=-2$: $12=-4B \Rightarrow B=-3$",
  truth=(x+14)/(x**2-4), tag='تجزئة: عوامل خطية مختلفة'),
Q('m4q4', U1[2], 'medium',
  F(r"إذا كان: $«0»=\dfrac{A}{x+1}+\dfrac{B}{x-2}+\dfrac{C}{(x-2)^{2}}$ ، فإنّ قيمة $C$ هي:", (r'\frac{2x^{2}-3x+5}{(x+1)(x-2)^{2}}', (2*x**2-3*x+5)/((x+1)*(x-2)**2))),
  [O(r'\frac{7}{3}', R(7, 3)), O(r'\frac{10}{9}', R(10, 9)), O(r'\frac{8}{9}', R(8, 9)), O('3', 3)],
  r"$2x^2-3x+5=A(x-2)^2+B(x+1)(x-2)+C(x+1)$" "\n" r"عند $x=2$: $8-6+5=3C \Rightarrow C=\frac73$",
  truth=cancel((2*x**2-3*x+5)/(x+1)).subs(x, 2), tag='تجزئة: عامل خطي مكرر'),
Q('m4q5', U2[1], 'easy',
  F(r"أبسط صورة للمقدار: $«0»$ هي:", (r'\cos(x-\frac{\pi}{6})+\cos(x+\frac{\pi}{6})', cos(x-pi/6)+cos(x+pi/6))),
  [O(r'\sqrt{3}\cos x', sqrt(3)*cos(x)), O(r'\cos x', cos(x)), O(r'\sqrt{3}\sin x', sqrt(3)*sin(x)), O(r'2\cos x', 2*cos(x))],
  r"بجمع المفكوكين يختفي حدّا الجيب: $2\cos x\cos\frac{\pi}{6}=2\cdot\frac{\sqrt3}{2}\cos x=\sqrt3\cos x$",
  truth=cos(x-pi/6)+cos(x+pi/6), tag='تبسيط باستعمال متطابقات المجموع والفرق'),
Q('m4q6', U2[1], 'medium',
  F(r"أيّ الآتية مكافئ للمقدار: $«0»$ ؟", (r'\frac{\sin x}{1+\cos x}+\frac{1+\cos x}{\sin x}', sin(x)/(1+cos(x))+(1+cos(x))/sin(x))),
  [O(r'2\csc x', 2*csc(x)), O(r'2\sec x', 2*sec(x)), O('2', 2), O(r'\csc x', csc(x))],
  r"$\dfrac{\sin^2x+(1+\cos x)^2}{(1+\cos x)\sin x}=\dfrac{\sin^2x+1+2\cos x+\cos^2x}{(1+\cos x)\sin x}=\dfrac{2(1+\cos x)}{(1+\cos x)\sin x}=\dfrac{2}{\sin x}=2\csc x$",
  truth=sin(x)/(1+cos(x))+(1+cos(x))/sin(x), tag='المتطابقات الأساسية'),
Q('m4q7', U2[2], 'medium',
  r"إذا كان $\cos2\theta=\frac{1}{8}$ ، حيث $\theta$ زاوية حادّة، فإنّ قيمة $\cos\theta$ هي:",
  [O(r'\frac{3}{4}', R(3, 4)), O(r'\frac{\sqrt{7}}{4}', sqrt(7)/4), O(r'\frac{9}{16}', R(9, 16)), O(r'\frac{1}{4}', R(1, 4))],
  r"$\cos2\theta=2\cos^2\theta-1=\frac18 \Rightarrow \cos^2\theta=\frac{9}{16} \Rightarrow \cos\theta=\frac34$ (لأن $\theta$ حادّة)",
  truth=cos(acos(R(1, 8))/2), tag='ضعف الزاوية بمعلومية نسبة'),
Q('m4q8', U2[2], 'medium',
  F(r"أبسط صورة للمقدار: $«0»$ هي:", (r'\frac{\sin 5x+\sin 3x}{\cos 5x+\cos 3x}', (sin(5*x)+sin(3*x))/(cos(5*x)+cos(3*x)))),
  [O(r'\tan 4x', tan(4*x)), O(r'\tan x', tan(x)), O(r'\cot 4x', cot(4*x)), O(r'\tan 8x', tan(8*x))],
  r"$\dfrac{2\sin4x\cos x}{2\cos4x\cos x}=\dfrac{\sin4x}{\cos4x}=\tan4x$",
  truth=(sin(5*x)+sin(3*x))/(cos(5*x)+cos(3*x)), tag='تحويل المجموع إلى ضرب'),
Q('m4q9', U2[3], 'medium',
  F(r"حلول المعادلة: $«0»=«1»$ في الفترة $(0,\,\pi)$ هي:", (r'2\sin x', 2*sin(x)), (r'\csc x', csc(x))),
  [O(st(r'\frac{\pi}{4}', r'\frac{3\pi}{4}'), S_(P/4, 3*P/4), 'set'), O(st(r'\frac{\pi}{4}', r'\frac{3\pi}{4}', r'\frac{5\pi}{4}', r'\frac{7\pi}{4}'), S_(P/4, 3*P/4, 5*P/4, 7*P/4), 'set'),
   O(st(r'\frac{\pi}{4}'), S_(P/4), 'set'), O(st(r'\frac{\pi}{6}', r'\frac{5\pi}{6}'), S_(P/6, 5*P/6), 'set')],
  r"بالضرب في $\sin x$: $2\sin^2x=1 \Rightarrow \sin x=\pm\frac{\sqrt2}{2}$" "\n" r"في الفترة $(0,\pi)$ الجيب موجب: $x=\frac{\pi}{4},\ \frac{3\pi}{4}$",
  truth=lambda: sols(2*sin(x)**2-1, 0, pi, closed_lo=False), tag='معادلة فيها مقلوب نسبة'),
Q('m4q10', U2[3], 'hard',
  F(r"مجموعة حلّ المعادلة: $«0»=1$ في الفترة $[0,\,2\pi)$ هي:", (r'\sin 3x', sin(3*x))),
  [O(st(r'\frac{\pi}{6}', r'\frac{5\pi}{6}', r'\frac{3\pi}{2}'), S_(P/6, 5*P/6, 3*P/2), 'set'), O(st(r'\frac{\pi}{6}'), S_(P/6), 'set'),
   O(st(r'\frac{\pi}{2}', r'\frac{5\pi}{2}', r'\frac{9\pi}{2}'), S_(P/2, 5*P/2, 9*P/2), 'set'), O(st(r'\frac{\pi}{6}', r'\frac{\pi}{2}', r'\frac{5\pi}{6}'), S_(P/6, P/2, 5*P/6), 'set')],
  r"بما أن $0\le x<2\pi$ فإن $0\le3x<6\pi$: $3x=\frac{\pi}{2},\ \frac{5\pi}{2},\ \frac{9\pi}{2}$" "\n" r"إذن $x=\frac{\pi}{6},\ \frac{5\pi}{6},\ \frac{3\pi}{2}$",
  truth=lambda: sols(sin(3*x)-1, 0, 2*pi), tag='معادلة بزاوية مضاعفة في فترة'),
Q('m4q11', U3[1], 'easy',
  F(r"إذا كان: $f(x)=«0»$ ، حيث $x>0$ ، فإنّ $f'(x)$ تساوي:", (r'\ln(5x)', log(5*x))),
  [O(r'\frac{1}{x}', 1/x), O(r'\frac{5}{x}', 5/x), O(r'\frac{1}{5x}', 1/(5*x)), O('5', 5)],
  r"$\ln(5x)=\ln5+\ln x$ ، و $\ln5$ ثابت مشتقته صفر، إذن $f'(x)=\dfrac1x$",
  truth=Dx(log(5*x)), tag='مشتقة الاقتران اللوغاريتمي'),
Q('m4q12', U3[2], 'medium',
  F(r"إذا كان: $f(x)=«0»$ ، فإنّ $f'''(2)$ تساوي:", (r'x^{2}\ln x', x**2*log(x))),
  [O('1', 1), O('2', 2), O(r'\frac{1}{2}', R(1, 2)), O('3', 3)],
  r"$f'(x)=2x\ln x+x$ ، $f''(x)=2\ln x+3$ ، $f'''(x)=\dfrac2x \Rightarrow f'''(2)=1$",
  truth=diff(x**2*log(x), x, 3).subs(x, 2), tag='المشتقات العليا'),
Q('m4q13', U3[3], 'medium',
  F(r"معادلة العمودي على المماس لمنحنى الاقتران: $y=«0»$ عند $x=4$ هي:", (r'\sqrt{x}', sqrt(x))),
  [O('y=-4x+18', -4*x+18, 'eq'), O(r'y=\frac{1}{4}x+1', x/4+1, 'eq'), O('y=-4x+2', -4*x+2, 'eq'), O('y=4x-14', 4*x-14, 'eq')],
  r"نقطة التماس $(4,2)$ ، $y'=\dfrac{1}{2\sqrt x} \Rightarrow$ ميل المماس $\frac14$ ، فميل العمودي $-4$" "\n" r"$y-2=-4(x-4) \Rightarrow y=-4x+18$",
  truth=(lambda f_: f_.subs(x, 4) - (x-4)/Dx(f_).subs(x, 4))(sqrt(x)), tag='معادلة العمودي على المماس'),
Q('m4q14', U3[2], 'hard',
  F(r"يتحرّك جُسيم في مسار مستقيم، ويُعطى موقعه بالاقتران: $s(t)=«0»$ ، حيث $t\ge0$ بالثواني و $s$ بالأمتار. تسارع الجُسيم عندما تنعدم سرعته هو:", (r'te^{-t}', t*exp(-t))),
  [O(r'-\frac{1}{e}', -1/E, units='m/s^2'), O(r'\frac{1}{e}', 1/E, units='m/s^2'), O('0', 0, units='m/s^2'), O('-e', -E, units='m/s^2')],
  r"$v(t)=e^{-t}-te^{-t}=e^{-t}(1-t)=0 \Rightarrow t=1$" "\n" r"$a(t)=e^{-t}(t-2) \Rightarrow a(1)=-e^{-1}=-\dfrac1e\ \text{m/s}^2$",
  truth=lambda: diff(t*exp(-t), t, 2).subs(t, solve(diff(t*exp(-t), t), t)[0]), tag='الحركة: السرعة والتسارع'),
Q('m4q15', U3[2], 'medium',
  F(r"إذا كان: $f(x)=«0»$ ، فإنّ $f^{(2027)}(x)$ تساوي:", (r'\sin x+\cos x', sin(x)+cos(x))),
  [O(r'\sin x-\cos x', sin(x)-cos(x)), O(r'\cos x-\sin x', cos(x)-sin(x)), O(r'-\sin x-\cos x', -sin(x)-cos(x)), O(r'\sin x+\cos x', sin(x)+cos(x))],
  r"المشتقات تتكرر كل 4: $f'=\cos x-\sin x$ ، $f''=-\sin x-\cos x$ ، $f'''=\sin x-\cos x$ ، $f^{(4)}=f$" "\n" r"$2027=4(506)+3$ ، إذن $f^{(2027)}=f'''=\sin x-\cos x$",
  truth=diff(sin(x)+cos(x), x, 2027), tag='المشتقات العليا: النمط الدوري'),
Q('m4q16', U3[3], 'hard',
  r"يُبيّن الشكل الآتي منحنيي الاقترانين $f(x)$ و $g(x)$. إذا كان: $h(x)=f^{2}(x)-g(x)$ ، فإنّ $h'(1)$ تساوي:",
  [O('-6', -6), O('-2', -2), O('6', 6), O('-4', -4)],
  r"$h'(x)=2f(x)f'(x)-g'(x)$" "\n" r"من الشكل: $f(1)=2$ ، $f'(1)=-1$ (ميل القطعة من $(0,3)$ إلى $(2,1)$) ، $g'(1)=2$ (ميل القطعة من $(0,0)$ إلى $(3,6)$)" "\n" r"$h'(1)=2(2)(-1)-2=-6$",
  truth=lambda: 2*f4_16(1)*fs4_16(1)-gs4_16(1), figure=figure('m4q16', draw_two([(0, 3), (2, 1), (6, 5)], [(0, 0), (3, 6), (6, 3)], 6, 6, (5.0, 4.4), (2.0, 6.2))), tag='المشتقة من التمثيل البياني'),
Q('m4q17', U3[3], 'medium',
  F(r"إذا كان: $f(x)=«0»$ ، حيث $x>1$ ، فإنّ $f'(2)$ تساوي:", (r'\ln\left(\frac{x+1}{x-1}\right)', log((x+1)/(x-1)))),
  [O(r'-\frac{2}{3}', -R(2, 3)), O(r'\frac{2}{3}', R(2, 3)), O(r'\frac{1}{3}', R(1, 3)), O(r'-\frac{1}{3}', -R(1, 3))],
  r"بخصائص اللوغاريتم: $f(x)=\ln(x+1)-\ln(x-1) \Rightarrow f'(x)=\dfrac{1}{x+1}-\dfrac{1}{x-1}$" "\n" r"$f'(2)=\frac13-1=-\frac23$",
  truth=Dx(log((x+1)/(x-1))).subs(x, 2), tag='قاعدة السلسلة مع اللوغاريتم'),
Q('m4q18', U3[3], 'medium',
  F(r"تُعطى درجة حرارة كوب من الشاي (بالسيليسيوس) بعد $t$ دقيقة بالاقتران: $T(t)=«0»$. معدّل تغيّر درجة حرارة الشاي عندما $t=2$ هو:", (r'25+60e^{-0.5t}', 25+60*exp(-t/2))),
  [O(r'-\frac{30}{e}', -30/E, units='°C/min'), O(r'\frac{30}{e}', 30/E, units='°C/min'), O(r'-\frac{60}{e}', -60/E, units='°C/min'), O('-30e', -30*E, units='°C/min')],
  r"$T'(t)=60(-0.5)e^{-0.5t}=-30e^{-0.5t}$ ، إذن $T'(2)=-30e^{-1}=-\dfrac{30}{e}$ (الإشارة السالبة تعني أن الشاي يبرد)",
  truth=diff(25+60*exp(-t/2), t).subs(t, 2), tag='معدل التغير في سياق حياتي'),
Q('m4q19', U3[3], 'easy',
  F(r"إذا أُعطي منحنى بالمعادلتين الوسيطيتين: $x=«0»$ ، $y=«1»$ ، فإنّ ميل المماس عندما $t=\frac{\pi}{6}$ هو:", (r'4\cos t', 4*cos(t)), (r'3\sin t', 3*sin(t))),
  [O(r'-\frac{3\sqrt{3}}{4}', -3*sqrt(3)/4), O(r'\frac{3\sqrt{3}}{4}', 3*sqrt(3)/4), O(r'-\frac{\sqrt{3}}{4}', -sqrt(3)/4), O(r'-\frac{4\sqrt{3}}{9}', -4*sqrt(3)/9)],
  r"$\dfrac{dy}{dx}=\dfrac{3\cos t}{-4\sin t}=-\frac34\cot t$ ، وعند $t=\frac{\pi}{6}$: $-\frac34\sqrt3=-\dfrac{3\sqrt3}{4}$",
  truth=(diff(3*sin(t), t)/diff(4*cos(t), t)).subs(t, pi/6), tag='مشتقة المعادلات الوسيطية'),
Q('m4q20', U3[4], 'medium',
  F(r"إذا كان: $x=«0»$ ، $y=«1»$ ، حيث $t>0$ ، فإنّ $\dfrac{d^{2}y}{dx^{2}}$ عندما $t=1$ تساوي:", (r'\ln t', log(t)), (r't^{2}', t**2)),
  [O('4', 4), O('2', 2), O('8', 8), O('1', 1)],
  r"$\dfrac{dy}{dx}=\dfrac{2t}{1/t}=2t^2$ ، و $\dfrac{d^2y}{dx^2}=\dfrac{4t}{1/t}=4t^2$ ، وعند $t=1$: $4$",
  truth=(diff(diff(t**2, t)/diff(log(t), t), t)/diff(log(t), t)).subs(t, 1), tag='المشتقة الثانية للمعادلات الوسيطية'),
Q('m4q21', U3[4], 'medium',
  F(r"إذا كان: $«0»=«1»$ ، فإنّ $\dfrac{dy}{dx}$ عند النقطة $(0,\,1)$ تساوي:", (r'ye^{x}+x^{2}', y*exp(x)+x**2), (r'y^{2}', y**2)),
  [O('1', 1), O('-1', -1), O(r'\frac{1}{2}', R(1, 2)), O('2', 2)],
  r"باشتقاق الطرفين: $y'e^x+ye^x+2x=2yy'$" "\n" r"عند $(0,1)$: $y'+1+0=2y' \Rightarrow y'=1$",
  truth=imp(y*exp(x)+x**2-y**2, (0, 1)), tag='الاشتقاق الضمني عند نقطة'),
Q('m4q22', U3[5], 'hard',
  r"خزّان على شكل أسطوانة دائرية قائمة نصف قطر قاعدتها $50\ \text{cm}$ ، يتسرّب منه الماء بمعدّل $3\ \text{L/min}$. معدّل انخفاض مستوى الماء في الخزّان هو:",
  [O(r'\frac{6}{5\pi}', 6/(5*pi), units='cm/min'), O(r'\frac{3}{2500\pi}', 3/(2500*pi), units='cm/min'), O(r'\frac{120}{\pi}', 120/pi, units='cm/min'), O(r'\frac{3}{50\pi}', 3/(50*pi), units='cm/min')],
  r"$3\ \text{L}=3000\ \text{cm}^3$ ، و $V=\pi r^2h=2500\pi h$" "\n" r"$\dfrac{dV}{dt}=2500\pi\dfrac{dh}{dt} \Rightarrow -3000=2500\pi\dfrac{dh}{dt} \Rightarrow \dfrac{dh}{dt}=-\dfrac{6}{5\pi}$ ، أي ينخفض بمعدّل $\dfrac{6}{5\pi}\ \text{cm/min}$",
  truth=R(3000, 2500)/pi, tag='معدلات مرتبطة مع تحويل الوحدات'),
Q('m4q23', U4[1], 'hard',
  r"إذا كان: $z=-2\left(\cos\frac{\pi}{5}+i\sin\frac{\pi}{5}\right)$ ، فإنّ السعة الرئيسة للعدد $z$ هي:",
  [O(r'-\frac{4\pi}{5}', -4*P/5), O(r'\frac{\pi}{5}', P/5), O(r'\frac{6\pi}{5}', 6*P/5), O(r'\frac{4\pi}{5}', 4*P/5)],
  r"المقياس لا يكون سالبًا: $z=2\left(-\cos\frac{\pi}{5}-i\sin\frac{\pi}{5}\right)=2\left(\cos\frac{6\pi}{5}+i\sin\frac{6\pi}{5}\right)$" "\n"
  r"و $\frac{6\pi}{5}>\pi$ ، فالسعة الرئيسة $\frac{6\pi}{5}-2\pi=-\frac{4\pi}{5}$",
  truth=arg(expand(-2*(cos(pi/5)+I*sin(pi/5)))), tag='السعة الرئيسة', lead=NOTE_I(23, 30)),
Q('m4q24', U4[1], 'easy',
  r"ناتج $\bar{z}-2w$ هو:",
  [O('1-3i', 1-3*I), O('1+5i', 1+5*I), O('5-3i', 5-3*I), O('1+3i', 1+3*I)],
  r"$\bar z=3+i$ ، $2w=2+4i$ ، إذن $\bar z-2w=1-3i$",
  truth=conjugate(3-I)-2*(1+2*I), tag='العمليات على الأعداد المركبة (نص مشترك)', lead=shared(r"إذا كان: $z=3-i$ ، $w=1+2i$", 24, 25)),
Q('m4q25', U4[2], 'easy',
  r"ناتج $zw$ هو:",
  [O('5+5i', 5+5*I), O('1+5i', 1+5*I), O('5-5i', 5-5*I), O('3-2i', 3-2*I)],
  r"$zw=(3-i)(1+2i)=3+6i-i-2i^2=5+5i$",
  truth=expand((3-I)*(1+2*I)), tag='العمليات على الأعداد المركبة (نص مشترك)'),
Q('m4q26', U4[2], 'medium',
  r"الجذران التربيعيان للعدد المُركَّب $7-24i$ هما:",
  [O(r'\pm(4-3i)', S_(4-3*I, -4+3*I), 'set'), O(r'\pm(3-4i)', S_(3-4*I, -3+4*I), 'set'), O(r'\pm(4+3i)', S_(4+3*I, -4-3*I), 'set'), O(r'\pm(3+4i)', S_(3+4*I, -3-4*I), 'set')],
  r"$a^2-b^2=7$ ، $ab=-12$ ، $a^2-\frac{144}{a^2}=7 \Rightarrow a^4-7a^2-144=0 \Rightarrow a^2=16$" "\n" r"$a=\pm4$ ، $b=\mp3$ ، تحقق: $(4-3i)^2=16-24i-9=7-24i$ ✔",
  truth=lambda: croots(z**2-(7-24*I)), tag='الجذور التربيعية للعدد المركب'),
Q('m4q27', U4[2], 'easy',
  r"المعادلة التربيعية ذات المعاملات الحقيقية التي أحد جذريها العدد المُركَّب $(-1+2i)$ هي:",
  [O('x^{2}+2x+5=0', x**2+2*x+5, 'rel'), O('x^{2}-2x+5=0', x**2-2*x+5, 'rel'), O('x^{2}+2x+3=0', x**2+2*x+3, 'rel'), O('x^{2}+2x-5=0', x**2+2*x-5, 'rel')],
  r"الجذر الآخر $-1-2i$ ، المجموع $-2$ ، وحاصل الضرب $1+4=5$ ، والمعادلة: $x^2+2x+5=0$",
  truth=expand((x-(-1+2*I))*(x-(-1-2*I))), tag='معادلة تربيعية بمعلومية جذر مركب'),
Q('m4q28', U4[2], 'medium',
  r"إذا كان: $z=3\left(\cos\frac{2\pi}{5}+i\sin\frac{2\pi}{5}\right)$ ، $w=2\left(\cos\frac{3\pi}{5}+i\sin\frac{3\pi}{5}\right)$ ، فإنّ الصورة القياسية لناتج $zw$ هي:",
  [O('-6', -6), O('6', 6), O('6i', 6*I), O('-6i', -6*I)],
  r"$zw=6\left(\cos\left(\frac{2\pi}{5}+\frac{3\pi}{5}\right)+i\sin\left(\frac{2\pi}{5}+\frac{3\pi}{5}\right)\right)=6(\cos\pi+i\sin\pi)=-6$",
  truth=expand(pol(3, 2*pi/5)*pol(2, 3*pi/5)), tag='الضرب والقسمة بالصورة المثلثية'),
Q('m4q29', U4[3], 'medium',
  r"المعادلة الديكارتية للمحل الهندسي: $|z-3i|=|z+1|$ هي:",
  [O(r'y=-\frac{1}{3}x+\frac{4}{3}', -x/3+R(4, 3), 'eq'), O(r'y=\frac{1}{3}x+\frac{4}{3}', x/3+R(4, 3), 'eq'), O(r'y=-3x+4', -3*x+4, 'eq'), O(r'y=-\frac{1}{3}x-\frac{4}{3}', -x/3-R(4, 3), 'eq')],
  r"$x^2+(y-3)^2=(x+1)^2+y^2 \Rightarrow -6y+9=2x+1 \Rightarrow y=-\frac13x+\frac43$",
  truth=lambda: solve(expand(X**2+(Y-3)**2-(X+1)**2-Y**2), Y)[0].subs(X, x), tag='المعادلة الديكارتية لمحل هندسي'),
Q('m4q30', U4[3], 'hard',
  r"نظام المتباينات (بدلالة $z$) الذي يُمثّل المحل الهندسي المُمثَّل بالمنطقة المُظلَّلة في الشكل الآتي (الخط الرأسي هو العمود المنصّف للقطعة الواصلة بين نقطة الأصل والنقطة $(2,0)$) هو:",
  [T(r'$|z-2i|\le2$ ، $|z|\le|z-2|$'), T(r'$|z-2i|\le2$ ، $|z|\ge|z-2|$'), T(r'$|z+2i|\le2$ ، $|z|\le|z-2|$'), T(r'$|z-2|\le2$ ، $|z|\le|z-2i|$')],
  r"المنطقة داخل الدائرة التي مركزها $(0,2)$ ونصف قطرها $2$: $|z-2i|\le2$" "\n" r"وتقع على يسار المستقيم $x=1$ ، أي أقرب إلى الأصل منها إلى النقطة $2$: $|z|\le|z-2|$",
  manual='region drawn: inside |z-2i|<=2 and x<=1', figure=figure('m4q30', fig_region('disk_left'), 3.4, 3.4), tag='منطقة في المستوى المركب من الشكل'),
]

# ================================================================== PAPER 5
f5_16, fs5_16 = pw([(0, 6), (4, 2), (7, 5)])
g5_16, gs5_16 = pw([(0, 1), (5, 6), (7, 2)])
f52 = x**3 + a*x**2 - 4*x + b
P5 = [
Q('m5q1', U1[1], 'medium',
  F(r"التحليل الكامل لكثير الحدود: $«0»$ هو:", (r'x^{4}-2x^{3}-7x^{2}+8x+12', x**4-2*x**3-7*x**2+8*x+12)),
  [O('(x+1)(x-2)(x-3)(x+2)', (x+1)*(x-2)*(x-3)*(x+2)), O('(x-1)(x+2)(x+3)(x-2)', (x-1)*(x+2)*(x+3)*(x-2)),
   O('(x+1)(x-2)(x+3)(x-2)', (x+1)*(x-2)*(x+3)*(x-2)), O('(x+1)(x+2)(x-3)(x-1)', (x+1)*(x+2)*(x-3)*(x-1))],
  r"$f(-1)=1+2-7-8+12=0$ و $f(2)=16-16-28+16+12=0$ ، إذن $(x+1)(x-2)=x^2-x-2$ عامل" "\n"
  r"بالقسمة: $x^4-2x^3-7x^2+8x+12=(x^2-x-2)(x^2-x-6)=(x+1)(x-2)(x-3)(x+2)$",
  truth=x**4-2*x**3-7*x**2+8*x+12, tag='التحليل الكامل لكثير حدود'),
Q('m5q2', U1[1], 'hard',
  F(r"إذا كان $(x-2)$ أحد عوامل الاقتران: $f(x)=«0»$ ، وكان باقي قسمة $f(x)$ على $(x+1)$ يساوي $6$ ، فإنّ قيمة $ab$ هي:", (r'x^{3}+ax^{2}-4x+b', f52)),
  [O('-4', -4), O('4', 4), O('-3', -3), O('3', 3)],
  r"$f(2)=8+4a-8+b=0 \Rightarrow 4a+b=0$ ، $f(-1)=-1+a+4+b=6 \Rightarrow a+b=3$" "\n" r"بالطرح: $3a=-3 \Rightarrow a=-1$ ، $b=4$ ، إذن $ab=-4$",
  truth=lambda: (lambda s_: s_[a]*s_[b])(solve([rem(f52, 2), rem(f52, -1)-6], [a, b])), tag='نظرية الباقي والعوامل معًا'),
Q('m5q3', U1[2], 'medium',
  F(r"أيّ الآتية يُمثّل تجزئة المقدار النسبي: $«0»$ إلى كسور جزئية؟", (r'\frac{2x^{2}+x+6}{x^{3}+2x}', (2*x**2+x+6)/(x**3+2*x))),
  [O(r'\frac{3}{x}+\frac{1-x}{x^{2}+2}', 3/x+(1-x)/(x**2+2)), O(r'\frac{3}{x}+\frac{x-1}{x^{2}+2}', 3/x+(x-1)/(x**2+2)), O(r'\frac{2}{x}+\frac{1}{x^{2}+2}', 2/x+1/(x**2+2)), O(r'\frac{6}{x}+\frac{1-4x}{x^{2}+2}', 6/x+(1-4*x)/(x**2+2))],
  r"$x^3+2x=x(x^2+2)$ ، و $2x^2+x+6=A(x^2+2)+(Bx+C)x$" "\n" r"عند $x=0$: $6=2A \Rightarrow A=3$ ، معامل $x^2$: $2=3+B \Rightarrow B=-1$ ، معامل $x$: $C=1$",
  truth=(2*x**2+x+6)/(x**3+2*x), tag='تجزئة: عامل تربيعي غير قابل للتحليل'),
Q('m5q4', U1[2], 'hard',
  F(r"المقدار: $«0»$ يساوي:", (r'\frac{x^{3}+1}{(x-1)^{2}}', (x**3+1)/(x-1)**2)),
  [O(r'x+2+\frac{3}{x-1}+\frac{2}{(x-1)^{2}}', x+2+3/(x-1)+2/(x-1)**2), O(r'x+2+\frac{2}{x-1}+\frac{3}{(x-1)^{2}}', x+2+2/(x-1)+3/(x-1)**2),
   O(r'x-2+\frac{3}{x-1}+\frac{2}{(x-1)^{2}}', x-2+3/(x-1)+2/(x-1)**2), O(r'x+2+\frac{3}{x-1}-\frac{2}{(x-1)^{2}}', x+2+3/(x-1)-2/(x-1)**2)],
  r"بالقسمة الطويلة على $x^2-2x+1$: $x^3+1=(x^2-2x+1)(x+2)+(3x-1)$" "\n" r"$\dfrac{3x-1}{(x-1)^2}=\dfrac{3(x-1)+2}{(x-1)^2}=\dfrac{3}{x-1}+\dfrac{2}{(x-1)^2}$",
  truth=(x**3+1)/(x-1)**2, tag='تجزئة: كسر غير فعلي'),
Q('m5q5', U2[1], 'easy',
  r"القيمة الدقيقة لـ $\tan\dfrac{5\pi}{12}$ هي:",
  [O(r'2+\sqrt{3}', 2+sqrt(3)), O(r'2-\sqrt{3}', 2-sqrt(3)), O(r'\sqrt{3}+1', sqrt(3)+1), O(r'\frac{\sqrt{3}+1}{2}', (sqrt(3)+1)/2)],
  r"$\tan\frac{5\pi}{12}=\tan\left(\frac{\pi}{4}+\frac{\pi}{6}\right)=\dfrac{1+\frac{1}{\sqrt3}}{1-\frac{1}{\sqrt3}}=\dfrac{\sqrt3+1}{\sqrt3-1}=\dfrac{(\sqrt3+1)^2}{2}=2+\sqrt3$",
  truth=tan(5*pi/12), tag='قيم دقيقة بمتطابقات المجموع والفرق'),
Q('m5q6', U2[1], 'hard',
  r"إذا كان $\tan A=\frac{3}{4}$ حيث $\pi<A<\frac{3\pi}{2}$ ، و $\cos B=-\frac{5}{13}$ حيث $\frac{\pi}{2}<B<\pi$ ، فإنّ قيمة $\tan(A+B)$ هي:",
  [O(r'-\frac{33}{56}', -R(33, 56)), O(r'\frac{33}{56}', R(33, 56)), O(r'-\frac{63}{16}', -R(63, 16)), O(r'\frac{63}{16}', R(63, 16))],
  r"$B$ في الربع الثاني: $\sin B=\frac{12}{13}$ ، $\tan B=-\frac{12}{5}$" "\n"
  r"$\tan(A+B)=\dfrac{\frac34-\frac{12}{5}}{1+\frac34\cdot\frac{12}{5}}=\dfrac{-\frac{33}{20}}{\frac{56}{20}}=-\dfrac{33}{56}$",
  truth=tan((pi+atan(R(3, 4)))+(pi-acos(R(5, 13)))), tag='المجموع والفرق بمعلومية نسب في أرباع مختلفة'),
Q('m5q7', U2[2], 'medium',
  r"إذا كان $\cos\theta=\frac{1}{3}$ ، حيث $\frac{3\pi}{2}<\theta<2\pi$ ، فإنّ قيمة $\cos\frac{\theta}{2}$ هي:",
  [O(r'-\frac{\sqrt{6}}{3}', -sqrt(6)/3), O(r'\frac{\sqrt{6}}{3}', sqrt(6)/3), O(r'-\frac{\sqrt{3}}{3}', -sqrt(3)/3), O(r'\frac{\sqrt{3}}{3}', sqrt(3)/3)],
  r"$\frac{3\pi}{4}<\frac{\theta}{2}<\pi$ (الربع الثاني) فجيب التمام سالب" "\n" r"$\cos\frac{\theta}{2}=-\sqrt{\dfrac{1+\frac13}{2}}=-\sqrt{\dfrac23}=-\dfrac{\sqrt6}{3}$",
  truth=cos((2*pi-acos(R(1, 3)))/2), tag='نصف الزاوية مع تحديد الربع'),
Q('m5q8', U2[2], 'medium',
  F(r"إذا كانت $0<x<\frac{\pi}{8}$ ، فإنّ أبسط صورة للمقدار $«0»$ هي:", (r'\sqrt{2+2\cos 4x}', sqrt(2+2*cos(4*x)))),
  [O(r'2\cos 2x', 2*cos(2*x)), O(r'2\cos 4x', 2*cos(4*x)), O(r'\sqrt{2}\cos 2x', sqrt(2)*cos(2*x)), O(r'2\sin 2x', 2*sin(2*x))],
  r"$2+2\cos4x=2(1+\cos4x)=2\cdot2\cos^22x=4\cos^22x$ ، فالمقدار $=|2\cos2x|=2\cos2x$ (لأن $0<2x<\frac{\pi}{4}$)",
  truth=2*cos(2*x), tag='تقليص القوة ونصف الزاوية'),
Q('m5q9', U2[3], 'medium',
  F(r"مجموع حلول المعادلة: $«0»=«1»$ في الفترة $[0,\,2\pi)$ هو:", (r'\sin^{2}x', sin(x)**2), (r'\sin x', sin(x))),
  [O(r'\frac{3\pi}{2}', 3*P/2), O(r'\frac{\pi}{2}', P/2), O(r'\pi', P), O(r'\frac{5\pi}{2}', 5*P/2)],
  r"$\sin x(\sin x-1)=0$: $\sin x=0 \Rightarrow x=0,\ \pi$ ، $\sin x=1 \Rightarrow x=\frac{\pi}{2}$" "\n" r"المجموع $=0+\pi+\frac{\pi}{2}=\frac{3\pi}{2}$ (لا نقسم على $\sin x$)",
  truth=lambda: sum(sols(sin(x)**2-sin(x), 0, 2*pi)), tag='مجموع الحلول في فترة'),
Q('m5q10', U2[3], 'hard',
  F(r"مجموعة حلّ المعادلة: $«0»=\sqrt{3}$ في الفترة $[0,\,2\pi)$ هي:", (r'\sec x+\tan x', sec(x)+tan(x))),
  [O(st(r'\frac{\pi}{6}'), S_(P/6), 'set'), O(st(r'\frac{\pi}{6}', r'\frac{3\pi}{2}'), S_(P/6, 3*P/2), 'set'), O(st(r'\frac{\pi}{6}', r'\frac{5\pi}{6}'), S_(P/6, 5*P/6), 'set'), O(st(r'\frac{\pi}{3}'), S_(P/3), 'set')],
  r"$\dfrac{1+\sin x}{\cos x}=\sqrt3 \Rightarrow 1+\sin x=\sqrt3\cos x$ ، وبالتربيع: $1+2\sin x+\sin^2x=3(1-\sin^2x)$" "\n"
  r"$4\sin^2x+2\sin x-2=0 \Rightarrow (2\sin x-1)(\sin x+1)=0$" "\n"
  r"$\sin x=-1 \Rightarrow x=\frac{3\pi}{2}$ مرفوض ($\cos x=0$ والمعادلة غير معرّفة) ، و $\sin x=\frac12$: $x=\frac{\pi}{6}$ يحقق ، أما $\frac{5\pi}{6}$ فيعطي $-\sqrt3$ (حل دخيل من التربيع)" "\n" r"إذن الحل $x=\frac{\pi}{6}$ فقط",
  truth=lambda: sols(sec(x)+tan(x)-sqrt(3), 0, 2*pi), tag='معادلة تحتاج تحققًا من الحلول الدخيلة'),
Q('m5q11', U3[1], 'easy',
  F(r"إذا كان: $f(x)=«0»$ ، فإنّ $f'(0)$ تساوي:", (r'e^{x}\ln 3+3^{x}', exp(x)*log(3)+3**x)),
  [O(r'2\ln 3', 2*log(3)), O(r'\ln 3', log(3)), O(r'1+\ln 3', 1+log(3)), O(r'3\ln 3', 3*log(3))],
  r"$f'(x)=e^x\ln3+3^x\ln3 \Rightarrow f'(0)=\ln3+\ln3=2\ln3$",
  truth=Dx(exp(x)*log(3)+3**x).subs(x, 0), tag='مشتقة الاقتران الأسي'),
Q('m5q12', U3[2], 'medium',
  F(r"إذا كان: $f(x)=«0»$ ، فإنّ $f'(x)$ تساوي:", (r'e^{x}(\cos x-\sin x)', exp(x)*(cos(x)-sin(x)))),
  [O(r'-2e^{x}\sin x', -2*exp(x)*sin(x)), O(r'2e^{x}\cos x', 2*exp(x)*cos(x)), O(r'-2e^{x}\cos x', -2*exp(x)*cos(x)), O(r'e^{x}(\cos x+\sin x)', exp(x)*(cos(x)+sin(x)))],
  r"$f'(x)=e^x(\cos x-\sin x)+e^x(-\sin x-\cos x)=-2e^x\sin x$",
  truth=Dx(exp(x)*(cos(x)-sin(x))), tag='مشتقة الضرب'),
Q('m5q13', U3[1], 'hard',
  F(r"يتحرّك جُسيم في مسار مستقيم، ويُعطى موقعه بالاقتران: $s(t)=«0»$ ، حيث $t$ بالثواني و $s$ بالأمتار. المسافة الكلية التي يقطعها الجُسيم في الفترة $[0,\,4]$ هي:", (r't^{3}-6t^{2}+9t+2', t**3-6*t**2+9*t+2)),
  [O('12', 12, units='m'), O('4', 4, units='m'), O('6', 6, units='m'), O('8', 8, units='m')],
  r"$v(t)=3(t-1)(t-3)$ ، فيغيّر الجُسيم اتجاهه عند $t=1$ و $t=3$" "\n"
  r"$s(0)=2$ ، $s(1)=6$ ، $s(3)=2$ ، $s(4)=6$" "\n" r"المسافة $=|6-2|+|2-6|+|6-2|=12\ \text{m}$ (أما الإزاحة فهي $4\ \text{m}$)",
  truth=(lambda s_: sum(abs(s_.subs(t, b_)-s_.subs(t, a_)) for a_, b_ in [(0, 1), (1, 3), (3, 4)]))(t**3-6*t**2+9*t+2), tag='الحركة: المسافة الكلية والإزاحة'),
Q('m5q14', U3[1], 'medium',
  F(r"المقطع $x$ للمماس لمنحنى الاقتران: $f(x)=«0»$ عند $x=1$ هو:", (r'x-2\ln x', x-2*log(x))),
  [O('2', 2), O('1', 1), O('-2', -2), O(r'\frac{1}{2}', R(1, 2))],
  r"$f(1)=1$ ، $f'(x)=1-\dfrac2x \Rightarrow f'(1)=-1$ ، فالمماس: $y-1=-(x-1) \Rightarrow y=-x+2$" "\n" r"عند $y=0$: $x=2$",
  truth=lambda: solve(1 + Dx(x-2*log(x)).subs(x, 1)*(x-1), x)[0], tag='معادلة المماس ومقاطعه'),
Q('m5q15', U3[2], 'hard',
  F(r"إذا كان: $f(x)=«0»$ ، حيث $k>0$ ، وكان: $f'(1)=\frac{5}{9}$ ، فإنّ قيمة $k$ هي:", (r'\frac{x^{2}}{x+k}', x**2/(x+k))),
  [O('2', 2), O(r'\frac{2}{5}', R(2, 5)), O('1', 1), O('4', 4)],
  r"$f'(x)=\dfrac{2x(x+k)-x^2}{(x+k)^2}$ ، $f'(1)=\dfrac{1+2k}{(1+k)^2}=\frac59$" "\n" r"$9+18k=5+10k+5k^2 \Rightarrow 5k^2-8k-4=0 \Rightarrow (5k+2)(k-2)=0 \Rightarrow k=2$ (لأن $k>0$)",
  truth=lambda: [r_ for r_ in solve(Dx(x**2/(x+k)).subs(x, 1)-R(5, 9), k) if r_ > 0][0], tag='إيجاد ثابت بمعلومية قيمة المشتقة'),
Q('m5q16', U3[2], 'medium',
  r"يُبيّن الشكل الآتي منحنيي الاقترانين $f(x)$ و $g(x)$. إذا كان: $k(x)=\dfrac{f(x)}{g(x)}$ ، فإنّ $k'(1)$ تساوي:",
  [O(r'-\frac{7}{4}', -R(7, 4)), O(r'\frac{7}{4}', R(7, 4)), O(r'-\frac{3}{4}', -R(3, 4)), O(r'-\frac{1}{4}', -R(1, 4))],
  r"من الشكل: $f(1)=5$ ، $f'(1)=-1$ ، $g(1)=2$ ، $g'(1)=1$" "\n" r"$k'(1)=\dfrac{f'(1)g(1)-f(1)g'(1)}{g(1)^2}=\dfrac{(-1)(2)-(5)(1)}{4}=-\dfrac74$",
  truth=lambda: (fs5_16(1)*g5_16(1)-f5_16(1)*gs5_16(1))/g5_16(1)**2, figure=figure('m5q16', draw_two([(0, 6), (4, 2), (7, 5)], [(0, 1), (5, 6), (7, 2)], 7, 6, (0.3, 6.3), (5.3, 6.1))), tag='المشتقة من التمثيل البياني'),
Q('m5q17', U3[3], 'medium',
  F(r"إذا كان: $f(x)=«0»$ ، فإنّ $f'(1)$ تساوي:", (r'\log_{3}(x+\sqrt{x})', log(x+sqrt(x), 3))),
  [O(r'\frac{3}{4\ln 3}', 3/(4*log(3))), O(r'\frac{3}{4}', R(3, 4)), O(r'\frac{1}{\ln 3}', 1/log(3)), O(r'\frac{3}{2\ln 3}', 3/(2*log(3)))],
  r"$f'(x)=\dfrac{1+\frac{1}{2\sqrt x}}{(x+\sqrt x)\ln3} \Rightarrow f'(1)=\dfrac{\frac32}{2\ln3}=\dfrac{3}{4\ln3}$",
  truth=Dx(log(x+sqrt(x), 3)).subs(x, 1), tag='مشتقة اللوغاريتم لأساس غير e'),
Q('m5q18', U3[3], 'medium',
  F(r"يُمثّل الاقتران: $C(t)=«0»$ تركيز دواء في الدم بعد $t$ ساعة من تناوله. الزمن الذي يكون عنده معدّل تغيّر التركيز صفرًا هو:", (r'10te^{-0.5t}', 10*t*exp(-t/2))),
  [O('2', 2, units='h'), O('0.5', R(1, 2), units='h'), O('10', 10, units='h'), O('1', 1, units='h')],
  r"$C'(t)=10e^{-0.5t}+10t(-0.5)e^{-0.5t}=10e^{-0.5t}(1-0.5t)=0 \Rightarrow t=2$",
  truth=lambda: solve(diff(10*t*exp(-t/2), t), t)[0], tag='معدل التغير في سياق حياتي'),
Q('m5q19', U3[3], 'hard',
  F(r"إذا أُعطي منحنى بالمعادلتين الوسيطيتين: $x=«0»$ ، $y=«1»$ ، حيث $t>0$ ، فإنّ النقطة التي يكون عندها المماس أفقيًّا هي:", (r't^{2}-2t', t**2-2*t), (r't^{3}-12t', t**3-12*t)),
  [O(r'(0,\ -16)', Tuple(0, -16), 'tuple'), O(r'(0,\ 16)', Tuple(0, 16), 'tuple'), O(r'(8,\ 16)', Tuple(8, 16), 'tuple'), O(r'(-1,\ -11)', Tuple(-1, -11), 'tuple')],
  r"المماس أفقي عندما $\dfrac{dy}{dt}=3t^2-12=0 \Rightarrow t=2$ (لأن $t>0$) ، و $\dfrac{dx}{dt}=2t-2=2\ne0$" "\n" r"النقطة: $x=4-4=0$ ، $y=8-24=-16$",
  truth=lambda: (lambda r_: Tuple(r_**2-2*r_, r_**3-12*r_))([q for q in solve(diff(t**3-12*t, t), t) if q > 0][0]), tag='مماس أفقي لمنحنى وسيطي'),
Q('m5q20', U3[4], 'hard',
  F(r"إذا كان: $«0»=3$ ، فإنّ $\dfrac{d^{2}y}{dx^{2}}$ عند النقطة $(2,\,1)$ تساوي:", (r'x^{2}-y^{2}', x**2-y**2)),
  [O('-3', -3), O('3', 3), O('2', 2), O('-1', -1)],
  r"$2x-2yy'=0 \Rightarrow y'=\dfrac{x}{y}=2$ عند $(2,1)$" "\n" r"$y''=\dfrac{y-xy'}{y^2}=\dfrac{1-2(2)}{1}=-3$",
  truth=imp(x**2-y**2-3, (2, 1), 2), tag='المشتقة الثانية بالاشتقاق الضمني'),
Q('m5q21', U3[4], 'medium',
  F(r"إذا مثّل المستقيم $l$ مماسًّا لمنحنى العلاقة: $«0»=9$ عند النقطة $(1,\,2)$ ، فإنّ المقطع $y$ للمستقيم $l$ هو:", (r'x^{3}+y^{3}', x**3+y**3)),
  [O(r'\frac{9}{4}', R(9, 4)), O(r'\frac{7}{4}', R(7, 4)), O(r'-\frac{1}{4}', -R(1, 4)), O('9', 9)],
  r"$3x^2+3y^2y'=0 \Rightarrow y'=-\dfrac{x^2}{y^2}=-\dfrac14$ عند $(1,2)$" "\n" r"المماس: $y-2=-\frac14(x-1)$ ، وعند $x=0$: $y=2+\frac14=\frac94$",
  truth=lambda: 2 + imp(x**3+y**3-9, (1, 2))*(0-1), tag='مماس منحنى علاقة ضمنية'),
Q('m5q22', U3[5], 'medium',
  r"كرة ثلج تذوب فيتناقص حجمها بمعدّل $8\pi\ \text{cm}^3/\text{min}$ وتبقى محافظة على شكلها الكروي. معدّل تناقص نصف قطرها عندما يكون نصف قطرها $2\ \text{cm}$ هو:",
  [O(r'\frac{1}{2}', R(1, 2), units='cm/min'), O('2', 2, units='cm/min'), O(r'\frac{1}{8}', R(1, 8), units='cm/min'), O(r'\frac{1}{4}', R(1, 4), units='cm/min')],
  r"$V=\frac43\pi r^3 \Rightarrow \dfrac{dV}{dt}=4\pi r^2\dfrac{dr}{dt} \Rightarrow -8\pi=16\pi\dfrac{dr}{dt} \Rightarrow \dfrac{dr}{dt}=-\dfrac12$" "\n" r"أي يتناقص نصف القطر بمعدّل $\frac12\ \text{cm/min}$",
  truth=8*pi/(4*pi*4), tag='معدلات مرتبطة: كرة'),
Q('m5q23', U4[2], 'easy',
  r"ناتج $(1-i)^{10}$ هو:",
  [O('-32i', -32*I), O('32i', 32*I), O('-32', -32), O('32', 32)],
  r"$(1-i)^2=1-2i+i^2=-2i$ ، إذن $(1-i)^{10}=(-2i)^5=-32i^5=-32i$",
  truth=expand((1-I)**10), tag='قوى العدد المركب', lead=NOTE_I(23, 30)),
Q('m5q24', U4[2], 'hard',
  r"الصورة المثلثية للعدد المُركَّب $z=\dfrac{\sqrt{3}+i}{1-i}$ هي:",
  [O(trig(r'\sqrt{2}', r'\frac{5\pi}{12}'), sqrt(2)*pol(1, 5*P/12)), O(trig(r'\sqrt{2}', r'-\frac{\pi}{12}'), sqrt(2)*pol(1, -P/12)),
   O(trig('2', r'\frac{5\pi}{12}'), pol(2, 5*P/12)), O(trig(r'\sqrt{2}', r'\frac{\pi}{12}'), sqrt(2)*pol(1, P/12))],
  r"$\sqrt3+i=2\left(\cos\frac{\pi}{6}+i\sin\frac{\pi}{6}\right)$ ، و $1-i=\sqrt2\left(\cos\left(-\frac{\pi}{4}\right)+i\sin\left(-\frac{\pi}{4}\right)\right)$" "\n"
  r"بالقسمة: المقياس $\frac{2}{\sqrt2}=\sqrt2$ ، والسعة $\frac{\pi}{6}-\left(-\frac{\pi}{4}\right)=\frac{5\pi}{12}$",
  truth=(sqrt(3)+I)/(1-I), tag='الضرب والقسمة بالصورة المثلثية'),
Q('m5q25', U4[1], 'medium',
  r"إذا كان: $z=(a^{2}-4)+(a+2)i$ ، حيث $a$ عدد حقيقي، فإنّ قيمة $a$ التي تجعل $z$ عددًا تخيّليًّا بحتًا (غير صفري) هي:",
  [O('2', 2), O(r'\pm 2', S_(2, -2), 'set'), O('-2', -2), O('4', 4)],
  r"العدد تخيّلي بحت إذا كان الجزء الحقيقي صفرًا والجزء التخيلي غير صفري:" "\n"
  r"$a^2-4=0 \Rightarrow a=\pm2$ ، لكن عند $a=-2$ يكون $z=0$ (الجزء التخيلي صفر) ، إذن $a=2$",
  truth=lambda: [r_ for r_ in solve(X**2-4, X) if r_+2 != 0][0], tag='قيمة ثابت تجعل العدد حقيقيًا أو تخيليًا'),
Q('m5q26', U4[1], 'hard',
  r"العدد المُركَّب $z$ هو:",
  [O('-15+8i', -15+8*I), O('15+8i', 15+8*I), O('-8+15i', -8+15*I), O('2+8i', 2+8*I)],
  r"بمساواة الجزأين التخيليين: $z=x+8i$ ، و $\sqrt{x^2+64}+x=2 \Rightarrow \sqrt{x^2+64}=2-x$" "\n"
  r"بالتربيع: $x^2+64=4-4x+x^2 \Rightarrow x=-15$ (تحقق: $\sqrt{225+64}=17=2+15$ ✔) ، إذن $z=-15+8i$",
  truth=lambda: [sx + 8*I for sx in solve(sqrt(X**2+64)+X-2, X)][0], tag='معادلة فيها المقياس (نص مشترك)', lead=shared(r"إذا كان العدد المُركَّب $z$ يُحقّق المعادلة: $|z|+z=2+8i$", 26, 27)),
Q('m5q27', U4[2], 'medium',
  r"ناتج $\dfrac{z}{1+i}$ في الصورة القياسية هو:",
  [O(r'\frac{-7+23i}{2}', (-7+23*I)/2), O(r'\frac{-23+7i}{2}', (-23+7*I)/2), O(r'\frac{-7-23i}{2}', (-7-23*I)/2), O(r'-7+23i', -7+23*I)],
  r"$z=-15+8i$ ، و $\dfrac{-15+8i}{1+i}\cdot\dfrac{1-i}{1-i}=\dfrac{-15+15i+8i-8i^2}{2}=\dfrac{-7+23i}{2}$",
  truth=(-15+8*I)/(1+I), tag='معادلة فيها المقياس (نص مشترك)'),
Q('m5q28', U4[3], 'hard',
  r"الأعداد المُركَّبة $z$ التي تُحقّق المعادلتين: $\text{Arg}(z)=\frac{\pi}{4}$ و $|z-4|=4$ معًا هي:",
  [O(r'\{4+4i\}', S_(4+4*I), 'set'), O(r'\{0,\ 4+4i\}', S_(0, 4+4*I), 'set'), O(r'\{2+2i\}', S_(2+2*I), 'set'), O(r'\{4+4i,\ -4-4i\}', S_(4+4*I, -4-4*I), 'set')],
  r"$\text{Arg}(z)=\frac{\pi}{4}$: الشعاع $y=x$ حيث $x>0$ (نقطة الأصل غير مشمولة)" "\n"
  r"بالتعويض في الدائرة: $(x-4)^2+x^2=16 \Rightarrow 2x^2-8x=0 \Rightarrow x=0$ أو $x=4$" "\n" r"$x=0$ مرفوض لأن $\text{Arg}(0)$ غير معرّفة، إذن $z=4+4i$ فقط",
  truth=lambda: FiniteSet(*[sx+I*sx for sx in solve((X-4)**2+X**2-16, X) if sx > 0]), tag='تقاطع محلين هندسيين'),
Q('m5q29', U4[3], 'medium',
  r"معادلة الدائرة التي مركزها النقطة التي تُمثّل العدد $2-i$ ، وتمرّ بنقطة الأصل، هي:",
  [T(r'$|z-2+i|=\sqrt{5}$', Tuple(2-I, sqrt(5))), T(r'$|z+2-i|=\sqrt{5}$', Tuple(-2+I, sqrt(5))), T(r'$|z-2+i|=5$', Tuple(2-I, 5)), T(r'$|z-2-i|=\sqrt{5}$', Tuple(2+I, sqrt(5)))],
  r"نصف القطر = بُعد المركز عن الأصل $=|2-i|=\sqrt5$ ، والمعادلة $|z-(2-i)|=\sqrt5$ أي $|z-2+i|=\sqrt5$",
  truth=Tuple(2-I, Abs(2-I)), tag='كتابة معادلة محل هندسي'),
Q('m5q30', U4[3], 'hard',
  r"المتباينة (بدلالة $z$) التي تُمثّل المحل الهندسي المُمثَّل بالمنطقة المُظلَّلة في الشكل الآتي هي:",
  [T(r'$\frac{\pi}{6}\le\text{Arg}(z+1-i)\le\frac{2\pi}{3}$'), T(r'$\frac{\pi}{6}\le\text{Arg}(z-1+i)\le\frac{2\pi}{3}$'), T(r'$\frac{\pi}{6}\le\text{Arg}(z)\le\frac{2\pi}{3}$'), T(r'$\frac{\pi}{3}\le\text{Arg}(z+1-i)\le\frac{2\pi}{3}$')],
  r"المنطقة محصورة بين شعاعين يبدآن بالنقطة $(-1,1)$ أي العدد $-1+i$: $\text{Arg}(z-(-1+i))=\text{Arg}(z+1-i)$" "\n"
  r"الشعاع الأدنى يصنع زاوية $\frac{\pi}{6}$ والأعلى $\frac{2\pi}{3}$ مع الاتجاه الموجب لمستقيم يوازي المحور الحقيقي، والخطوط متصلة: $\frac{\pi}{6}\le\text{Arg}(z+1-i)\le\frac{2\pi}{3}$",
  manual='wedge from -1+i between pi/6 and 2pi/3', figure=figure('m5q30', fig_region('wedge'), 3.4, 3.4), tag='منطقة في المستوى المركب من الشكل'),
]

papers = [dict(id='s1-m1', model=1, title='النموذج (1)', minutes=90, questions=P1),
          dict(id='s1-m2', model=2, title='النموذج (2)', minutes=90, questions=P2),
          dict(id='s1-m3', model=3, title='النموذج (3)', minutes=90, questions=P3),
          dict(id='s1-m4', model=4, title='النموذج (4)', minutes=90, questions=P4),
          dict(id='s1-m5', model=5, title='النموذج (5)', minutes=90, questions=P5)]

SKILLS = {
  'حل معادلات كثيرات الحدود وتحليلها': ['حل معادلة كثير حدود بمعلومية أحد جذورها', 'الأصفار النسبية وحل المعادلة', 'التحليل الكامل لكثير حدود', 'تطبيق حياتي على نظرية العوامل'],
  'نظريتا الباقي والعوامل وإيجاد الثوابت': ['باقي القسمة على مقدار تربيعي', 'نظرية الباقي وإيجاد ثابت', 'نظرية العوامل وإيجاد ثابتين', 'نظرية الباقي والعوامل معًا', 'القسمة التركيبية على (ax−b)'],
  'الكسور الجزئية': ['تجزئة: عامل خطي مكرر', 'إيجاد ثوابت في التجزئة', 'تجزئة: عامل تربيعي غير قابل للتحليل', 'تجزئة: كسر غير فعلي', 'تجزئة: عوامل خطية مختلفة'],
  'المتطابقات الأساسية والتبسيط': ['المتطابقات الأساسية', 'المتطابقات: الزوايا المنتسبة والزوجية والفردية', 'تبسيط باستعمال متطابقات المجموع والفرق'],
  'المجموع والفرق: قيم دقيقة وأرباع': ['قيم دقيقة بمتطابقات المجموع والفرق', 'المجموع والفرق بمعلومية نسب في أرباع مختلفة'],
  'ضعف الزاوية ونصفها وتقليص القوة': ['نصف الزاوية مع تحديد الربع', 'ضعف الزاوية بمعلومية نسبة', 'ضعف الزاوية بالتربيع', 'تقليص القوة ونصف الزاوية'],
  'تحويل الضرب إلى مجموع وبالعكس': ['تحويل المجموع إلى ضرب', 'تحويل الضرب إلى مجموع'],
  'حل المعادلات المثلثية': ['معادلة تربيعية في نسبة مثلثية مع رفض حل', 'معادلة فيها مقلوب نسبة وزاوية مضاعفة', 'الحل العام: أيّ القيم ليست حلًّا', 'معادلة باستعمال متطابقة ضعف الزاوية', 'عدد الحلول في فترة مغلقة', 'معادلة بنصف الزاوية', 'معادلة فيها مقلوب نسبة', 'معادلة بزاوية مضاعفة في فترة', 'مجموع الحلول في فترة', 'معادلة تحتاج تحققًا من الحلول الدخيلة'],
  'مشتقات الاقترانات الخاصة': ['مشتقات الاقترانات المثلثية', 'مشتقة الاقتران الأسي واللوغاريتمي', 'مشتقة الاقتران اللوغاريتمي', 'مشتقة الاقتران الأسي والقوة', 'مشتقة الاقتران الأسي', 'مشتقة اللوغاريتم لأساس غير e'],
  'الضرب والقسمة والمشتقات العليا': ['مشتقة الضرب', 'المشتقات العليا', 'المشتقات العليا وتراكيبها', 'المشتقات العليا: النمط الدوري', 'إيجاد ثابت بمعلومية قيمة المشتقة'],
  'المماس والعمودي': ['معادلة العمودي على المماس', 'مماس يوازي مستقيمًا معلومًا', 'مماس من نقطة خارج المنحنى', 'معادلة المماس ومقاطعه'],
  'الحركة في مسار مستقيم': ['الحركة: اتجاه الحركة والسكون', 'الحركة: السرعة والتسارع', 'الحركة: المسافة الكلية والإزاحة'],
  'قاعدة السلسلة والتطبيقات الحياتية': ['قاعدة السلسلة مع اللوغاريتم', 'معدل التغير في سياق حياتي'],
  'المشتقة من التمثيل البياني': ['المشتقة من التمثيل البياني'],
  'المعادلات الوسيطية': ['مشتقة المعادلات الوسيطية', 'المشتقة الثانية للمعادلات الوسيطية', 'مماس منحنى وسيطي', 'مماس أفقي لمنحنى وسيطي'],
  'الاشتقاق الضمني': ['الاشتقاق الضمني عند نقطة', 'مماس منحنى علاقة ضمنية', 'المشتقة الثانية بالاشتقاق الضمني', 'مساحة مثلث يصنعه المماس مع المحورين'],
  'المعدلات المرتبطة': ['معدلات مرتبطة مع تحويل الوحدات', 'معدلات مرتبطة: كرة', 'معدلات مرتبطة: معدل تغير زاوية', 'معدلات مرتبطة: دائرة'],
  'الصورة القياسية والقوى والمرافق': ['قوى i', 'قوى العدد المركب', 'معادلة فيها العدد ومرافقه', 'معادلة فيها المقياس (نص مشترك)', 'قيمة ثابت تجعل العدد حقيقيًا أو تخيليًا'],
  'المقياس والسعة والصورة المثلثية': ['الصورة المثلثية بشروط', 'السعة الرئيسة', 'الضرب والقسمة بالصورة المثلثية', 'الزاوية بين عددين مركبين', 'المقياس والعمليات (نص مشترك)'],
  'العمليات والجذور والمعادلات المركبة': ['العمليات على الأعداد المركبة (نص مشترك)', 'الجذور التربيعية للعدد المركب', 'معادلة تربيعية بمعلومية جذر مركب', 'معادلة كثير حدود بجذر مركب'],
  'المحل الهندسي في المستوى المركب': ['المعادلة الديكارتية لمحل هندسي', 'المحل الهندسي: الشعاع', 'تقاطع محلين هندسيين', 'كتابة معادلة محل هندسي', 'منطقة في المستوى المركب من الشكل'],
}
PATTERN_TO_SKILL = {pt: sk for sk, pts in SKILLS.items() for pt in pts}
for paper in papers:
    for q_ in paper['questions']:
        assert q_.tag in PATTERN_TO_SKILL, f'{q_.id}: pattern {q_.tag} not grouped'
        q_.pattern, q_.tag = q_.tag, PATTERN_TO_SKILL[q_.tag]

if __name__ == '__main__':
    meta = dict(id='s1', title='امتحانات تجريبية — الفصل الأول', subtitle='الوحدات 1–4 · 30 فقرة · 90 دقيقة')
    build_mock(meta, papers, 's1')
